import io
import xml.etree.ElementTree as ET
from ..utils import (
    _add_created_with_comment,
    _add_path_text,
    _add_path_attr, 
    _ensure_path,
)


def construct_atsn_ua(rows: list) -> bytes:
    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/atsn')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    root.set('xmlns:ats', 'http://www.sec.gov/edgar/atsncommon')

    header_row = next((r for r in rows if r.get('_table') == 'atsn_ua'), rows[0] if rows else {})

    # --- headerData ---
    _add_path_text(root, ['headerData', 'accessionNumber'], header_row.get('accessionNumber'))
    _add_path_text(root, ['headerData', 'dateCeaseToOperate'], header_row.get('dateCeaseToOperate'))
    _add_path_text(root, ['headerData', 'rbOperatesPursuantToFormATS'], header_row.get('rbOperatesPursuantToFormAts'))
    _add_path_text(root, ['headerData', 'submissionType'], header_row.get('submissionType'))
    _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], header_row.get('liveTestFlag'))
    _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactEmailAddress'], header_row.get('contactEmailAddress'))
    _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactName'], header_row.get('contactName'))
    _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactPhoneNumber'], header_row.get('contactPhoneNumber'))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'MPID'], header_row.get('mpid'))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'NMSStockATSName'], header_row.get('nmsStockAtsName'))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], header_row.get('fileNumber'))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], header_row.get('ccc'))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], header_row.get('cik'))
    _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'confirmingCopyFlag'], header_row.get('confirmingCopyFlag'))
    _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], header_row.get('overrideInternetFlag'))

    # --- formData / cover ---
    _add_path_text(root, ['formData', 'cover', 'rbOperatesPursuantToFormATS'], header_row.get('coverRbOperatesPursuantToFormAts'))
    _add_path_text(root, ['formData', 'cover', 'taStatementAboutAmendment'], header_row.get('taStatementAboutAmendment'))
    _add_path_text(root, ['formData', 'cover', 'txNMSStockATSName'], header_row.get('txNMSStockATSName'))

    # --- formData / partOne ---
    _add_path_text(root, ['formData', 'partOne', 'rbPart1Item1IsBd'], header_row.get('rbPart1Item1IsBd'))
    _add_path_text(root, ['formData', 'partOne', 'txPart1Item2ATSName'], header_row.get('txPart1Item2ATSName'))
    _add_path_attr(root, ['formData', 'partOne', 'atsNames', 'atsName'], 'txPart1Item3ATSName', header_row.get('txPart1Item3ATSName'))
    _add_path_text(root, ['formData', 'partOne', 'txPart1Item4aBdCrdNumber'], header_row.get('txPart1Item4aBdCrdNumber'))
    _add_path_text(root, ['formData', 'partOne', 'txPart1Item4aBdFileNumber'], header_row.get('txPart1Item4aBdFileNumber'))
    _add_path_text(root, ['formData', 'partOne', 'txPart1Item5aNsaFullName'], header_row.get('txPart1Item5aNsaFullName'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item5bEffectiveMembershipDate'], header_row.get('part1Item5bEffectiveMembershipDate'))
    _add_path_text(root, ['formData', 'partOne', 'txtPart1Item5cNmsStockMPID'], header_row.get('txtPart1Item5cNmsStockMPID'))
    _add_path_text(root, ['formData', 'partOne', 'txtPart1Item6uwebsite'], header_row.get('txtPart1Item6uwebsite'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'street1'], header_row.get('street1'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'street2'], header_row.get('street2'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'city'], header_row.get('city'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'state'], header_row.get('state'))
    _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'zip'], header_row.get('zip'))
    _add_path_text(root, ['formData', 'partOne', 'cbPart1Item8Exhibit1atWebsite'], header_row.get('cbPart1Item8Exhibit1atWebsite'))
    _add_path_text(root, ['formData', 'partOne', 'cbPart1Item9Exhibit2atWebsite'], header_row.get('cbPart1Item9Exhibit2atWebsite'))

    # secondary sites — repeating rows
    for row in rows:
        if row.get('_table') != 'atsn_ua_secondary_site':
            continue
        site = _ensure_path(
            _ensure_path(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords']),
            ['secondarySiteI7'],
            create_leaf=True,
        )
        _add_path_text(site, ['street1'], row.get('secondarySite7Street1'))
        _add_path_text(site, ['street2'], row.get('secondarySite7Street2'))
        _add_path_text(site, ['city'], row.get('secondarySite7City'))
        _add_path_text(site, ['state'], row.get('secondarySite7State'))
        _add_path_text(site, ['zip'], row.get('secondarySite7Zip'))

    # --- formData / partTwo ---
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest'], 'rbPart2Item1aArePermittedToEnterInterest', header_row.get('part2Item1AArePermittedToEnterInterestRbPart2Item1AArePermittedToEnterInterest'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item1aArePermittedToEnterInterest'], header_row.get('rbPart2Item1AArePermittedToEnterInterest'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'part2Item1bAreSevicesSametoAllSubscribers'], 'rbPart2Item1bAreSevicesSametoAllSubscribers', header_row.get('part2Item1BAreSevicesSametoAllSubscribersRbPart2Item1BAreSevicesSametoAllSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'rbPart2Item1bAreSevicesSametoAllSubscribers'], header_row.get('rbPart2Item1BAreSevicesSametoAllSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'rbPart2Item1cAreThereArrangements'], header_row.get('rbPart2Item1CAreThereArrangements'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'taPart2Item1aUnitNamesEnterInterest'], header_row.get('taPart2Item1AUnitNamesEnterInterest'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'part2Item1bAreSevicesSametoAllSubscribers', 'taPart2Item2bExplainDiff'], header_row.get('part2Item1BAreSevicesSametoAllSubscribersTaPart2Item2BExplainDiff'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item1dCanOATInterestBeRouted'], header_row.get('rbPart2Item1dCanOATInterestBeRouted'))
    _add_path_attr(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest'], 'rbPart2Item2aAreAfflPermittedToEnterInterest', header_row.get('affiliatesPermittedToEnterInterestRbPart2Item2AAreAfflPermittedToEnterInterest'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item2aAreAfflPermittedToEnterInterest'], header_row.get('rbPart2Item2AAreAfflPermittedToEnterInterest'))
    _add_path_attr(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'part2Item2bAreSevicestoAfflSametoSubscribers'], 'rbPart2Item2bAreSevicestoAfflSametoSubscribers', header_row.get('part2Item2BAreSevicestoAfflSametoSubscribersRbPart2Item2BAreSevicestoAfflSametoSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'rbPart2Item2bAreSevicestoAfflSametoSubscribers'], header_row.get('rbPart2Item2BAreSevicestoAfflSametoSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'rbPart2Item2cAreThereArrangementsWithAffl'], header_row.get('rbPart2Item2CAreThereArrangementsWithAffl'))
    _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'taPart2Item2aAfflThatEnterInterest'], header_row.get('taPart2Item2AAfflThatEnterInterest'))
    _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'part2Item2bAreSevicestoAfflSametoSubscribers', 'taPart2Item2bExplainDiff'], header_row.get('taPart2Item2BExplainDiff'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item2dCanOATIBeRoutedByAffl'], header_row.get('rbPart2Item2dCanOATIBeRoutedByAffl'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfBD'], 'rbPart2Item3aCanSubscrOptOutWithOATIOfBD', header_row.get('part2Item3ACanSubscrOptOutWithOatiOfBdRbPart2Item3ACanSubscrOptOutWithOatiOfBd'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3aCanSubscrOptOutWithOATIOfBD'], header_row.get('rbPart2Item3ACanSubscrOptOutWithOatiOfBd'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfBD', 'taPart2Item3aExplianOptOut'], header_row.get('taPart2Item3AExplianOptOut'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfAffl'], 'rbPart2Item3aCanSubscrOptOutWithOATIOfAffl', header_row.get('part2Item3ACanSubscrOptOutWithOatiOfAfflRbPart2Item3ACanSubscrOptOutWithOatiOfAffl'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3aCanSubscrOptOutWithOATIOfAffl'], header_row.get('rbPart2Item3ACanSubscrOptOutWithOatiOfAffl'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfAffl', 'taPart2Item3bExplianOptOut'], header_row.get('taPart2Item3BExplianOptOut'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item3cAreOptOutSametoAllSubscribers'], 'rbPart2Item3cAreOptOutSametoAllSubscribers', header_row.get('part2Item3CAreOptOutSametoAllSubscribersRbPart2Item3CAreOptOutSametoAllSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3cAreOptOutSametoAllSubscribers'], header_row.get('rbPart2Item3CAreOptOutSametoAllSubscribers'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item3cAreOptOutSametoAllSubscribers', 'taPart2Item3cExplainDiff'], header_row.get('taPart2Item3CExplainDiff'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item4aAreThereArrangementsBtwBDAndTC'], 'rbPart2Item4aAreThereArrangementsBtwBDAndTC', header_row.get('part2Item4AAreThereArrangementsBtwBdAndTcRbPart2Item4AAreThereArrangementsBtwBdAndTc'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item4aAreThereArrangementsBtwBDAndTC'], header_row.get('rbPart2Item4AAreThereArrangementsBtwBdAndTc'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item4aAreThereArrangementsBtwBDAndTC', 'rbPart2Item4bAreThereArrangementsBtwAfflAndTC'], header_row.get('rbPart2Item4BAreThereArrangementsBtwAfflAndTc'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item4aAreThereArrangementsBtwBDAndTC', 'taPart2Item4aTDAndATSServices'], header_row.get('taPart2Item4ATdAndAtsServices'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices'], 'rbPart2Item5aDoesOfferProductsAndServices', header_row.get('rbPart2Item5aDoesOfferProductsAndServices'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'taPart2Item5aProductsAndServices'], header_row.get('taPart2Item5aProductsAndServices'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'part2Item5bAreSevicesSametoAllSubscribersAndBD'], 'rbPart2Item5bAreSevicesSametoAllSubscribersAndBD', header_row.get('part2Item5BAreSevicesSametoAllSubscribersAndBdRbPart2Item5BAreSevicesSametoAllSubscribersAndBd'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item5cDoesAfflOfferProductsAndServices'], header_row.get('rbPart2Item5cDoesAfflOfferProductsAndServices'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'part2Item5bAreSevicesSametoAllSubscribersAndBD', 'taPart2Item5bExplainDiff'], header_row.get('taPart2Item5BExplainDiff'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item6aDoesEmployeeAccessConfidentialInfo'], 'rbPart2Item6aDoesEmployeeAccessConfidentialInfo', header_row.get('rbPart2Item6aDoesEmployeeAccessConfidentialInfo'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item6aDoesEmployeeAccessConfidentialInfo', 'taPart2Item6aUnitAfflEmployeeServices'], header_row.get('taPart2Item6aUnitAfflEmployeeServices'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices'], 'rbPart2Item6bDoesAnyEntitySupportServices', header_row.get('rbPart2Item6bDoesAnyEntitySupportServices'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'taPart2Item6bServiceProvider'], header_row.get('taPart2Item6bServiceProvider'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'part2Item6cDoesServiceProviderUseATSServices'], 'rbPart2Item6cDoesServiceProviderUseATSServices', header_row.get('part2Item6CDoesServiceProviderUseAtsServicesRbPart2Item6CDoesServiceProviderUseAtsServices'))
    _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item7bCanSubscriberConsentToDisclosure'], header_row.get('rbPart2Item7BCanSubscriberConsentToDisclosure'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'part2Item6cDoesServiceProviderUseATSServices', 'rbPart2Item6dAreATSSevicesSametoAll'], header_row.get('rbPart2Item6DAreAtsSevicesSametoAll'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'part2Item6cDoesServiceProviderUseATSServices', 'taPart2Item6cProviderAfflAndServicesUsed'], header_row.get('taPart2Item6CProviderAfflAndServicesUsed'))
    _add_path_text(root, ['formData', 'partTwo', 'taPart2Item7aDescrOfSafeGaurdsAndProcedures'], header_row.get('taPart2Item7aDescrOfSafeGaurdsAndProcedures'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure'], 'rbPart2Item7bCanSubscriberConsentToDisclosure', header_row.get('part2Item7BCanSubscriberConsentToDisclosureRbPart2Item7BCanSubscriberConsentToDisclosure'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure', 'taPart2Item7bExplainHowAndConditions'], header_row.get('taPart2Item7BExplainHowAndConditions'))
    _add_path_attr(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure', 'part2Item7cCanSubscriberWithdrawConsent'], 'rbPart2Item7cCanSubscriberWithdrawConsent', header_row.get('rbPart2Item7CCanSubscriberWithdrawConsent'))
    _add_path_text(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure', 'part2Item7cCanSubscriberWithdrawConsent', 'taPart2Item7cExplainHowAndConditions'], header_row.get('taPart2Item7CExplainHowAndConditions'))
    _add_path_text(root, ['formData', 'partTwo', 'taPart2Item7dSummaryOfRolesRespOfPersons'], header_row.get('taPart2Item7dSummaryOfRolesRespOfPersons'))

    # --- formData / partThree ---
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item2aRegisteredBD'], header_row.get('rbPart3Item2aRegisteredBD'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions'], 'rbPart3Item2bIsThereOtherConditions', header_row.get('rbPart3Item2bIsThereOtherConditions'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'taPart3Item2bSummaryOfCndtns'], header_row.get('taPart3Item2bSummaryOfCndtns'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'part3Item2cSummaryOfConditions'], 'rbPart3Item2cIsConditionsSameForAll', header_row.get('part3Item2CSummaryOfConditionsRbPart3Item2CIsConditionsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item2dIsThereWrittenAgreement'], header_row.get('rbPart3Item2dIsThereWrittenAgreement'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'rbPart3Item2cIsConditionsSameForAll'], header_row.get('rbPart3Item2CIsConditionsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'part3Item2cSummaryOfConditions', 'taPart3Item2cSummaryOfDifferences'], header_row.get('taPart3Item2CSummaryOfDifferences'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns'], 'rbPart3Item3aIsExcludeSubscriber', header_row.get('rbPart3Item3aIsExcludeSubscriber'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'taPart3Item3aExcludngSumryDtls'], header_row.get('taPart3Item3aExcludngSumryDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'part3Item3bSummaryOfConditions'], 'rbPart3Item3bIsCondtnsSameForAll', header_row.get('part3Item3BSummaryOfConditionsRbPart3Item3BIsCondtnsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'rbPart3Item3bIsCondtnsSameForAll'], header_row.get('rbPart3Item3BIsCondtnsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'part3Item3bSummaryOfConditions', 'taPart3Item3bSummaryOfDifferences'], header_row.get('taPart3Item3BSummaryOfDifferences'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item4bIsHrsOfOperationsame'], header_row.get('rbPart3Item4bIsHrsOfOperationsame'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item4aHrsOfOperation'], header_row.get('taPart3Item4aHrsOfOperation'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item5aProtocolDetails'], 'rbPart3Item5aIsPermitOrdrTradng', header_row.get('rbPart3Item5aIsPermitOrdrTradng'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item5aIsPermitOrdrTradng'], header_row.get('rbPart3Item5AIsPermitOrdrTradng'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'taPart3Item5aProtocolused'], header_row.get('taPart3Item5aProtocolused'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'part3Item5bProtocolDetails'], 'rbPart3Item5bIsProtclsameForAll', header_row.get('part3Item5BProtocolDetailsRbPart3Item5BIsProtclsameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'rbPart3Item5bIsProtclsameForAll'], header_row.get('rbPart3Item5BIsProtclsameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'part3Item5bProtocolDetails', 'taPart3Item5aProtocolSumryDtls'], header_row.get('taPart3Item5AProtocolSumryDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item5cOthrDtls'], 'rbPart3Item5cIsAnyOtherMeans', header_row.get('part3Item5COthrDtlsRbPart3Item5CIsAnyOtherMeans'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item5cIsAnyOtherMeans'], header_row.get('rbPart3Item5CIsAnyOtherMeans'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'taPart3Item5cOthrMeansDtls'], header_row.get('taPart3Item5COthrMeansDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'part3Item5dTnCDetails'], 'rbPart3Item5dIsTnCSameForAll', header_row.get('part3Item5DTnCDetailsRbPart3Item5DIsTnCSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'rbPart3Item5dIsTnCSameForAll'], header_row.get('rbPart3Item5DIsTnCSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'part3Item5dTnCDetails', 'taPart3Item5dTnCSumryDtls'], header_row.get('taPart3Item5DTnCSumryDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item6aProtocolDetails'], 'rbPart3Item6aIsCoLocRltdSrvcsOfrd', header_row.get('part3Item6AProtocolDetailsRbPart3Item6AIsCoLocRltdSrvcsOfrd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item6aIsCoLocRltdSrvcsOfrd'], header_row.get('rbPart3Item6AIsCoLocRltdSrvcsOfrd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'taPart3Item6aCoLocRltdSrvcsDtls'], header_row.get('taPart3Item6ACoLocRltdSrvcsDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'part3Item6bTNCDetails'], 'rbPart3Item6bIsTNCsameForAll', header_row.get('part3Item6BTncDetailsRbPart3Item6BIsTnCsameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'rbPart3Item6cIsAnyOtherMeans'], header_row.get('rbPart3Item6cIsAnyOtherMeans'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'part3Item6bTNCDetails', 'taPart3Item6bTNCSumryDtls'], header_row.get('taPart3Item6BTncSumryDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item6eIsAnyRducdSpOfCom'], header_row.get('rbPart3Item6eIsAnyRducdSpOfCom'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item7bTnCDetails'], 'rbPart3Item7bIsTnCSameForAll', header_row.get('part3Item7BTnCDetailsRbPart3Item7BIsTnCSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item7AOrdrTypExplain'], header_row.get('taPart3Item7AOrdrTypExplain'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item7bIsTnCSameForAll'], header_row.get('rbPart3Item7BIsTnCSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item7bTnCDetails', 'taPart3Item7bTnCSumryDtls'], header_row.get('taPart3Item7BTnCSumryDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts'], 'rbPart3Item8aIsMinOrMaxSizeReqd', header_row.get('rbPart3Item8aIsMinOrMaxSizeReqd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'taPart3Item8aOtiSizeReqrmns'], header_row.get('taPart3Item8aOtiSizeReqrmns'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'part3Item8bReqProcDetails'], 'rbPart3Item8bIsReqProcSameForAll', header_row.get('part3Item8BReqProcDetailsRbPart3Item8BIsReqProcSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'rbPart3Item8bIsReqProcSameForAll'], header_row.get('rbPart3Item8BIsReqProcSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'part3Item8bReqProcDetails', 'taPart3Item8bDiffrncsInOtiReqrmnts'], header_row.get('taPart3Item8BDiffrncsInOtiReqrmnts'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs'], 'rbPart3Item8cIsOddLotsAcptdExecutd', header_row.get('part3Item8COddltOrdrReqsRbPart3Item8CIsOddLotsAcptdExecutd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item8cIsOddLotsAcptdExecutd'], header_row.get('rbPart3Item8CIsOddLotsAcptdExecutd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs', 'taPart3Item8cOddLtOrdrReqsnProcdurs'], header_row.get('taPart3Item8COddLtOrdrReqsnProcdurs'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs', 'part3Item8dReqsProcdurDtls'], 'rbPart3Item8dIsReqsProcdurSameForAll', header_row.get('rbPart3Item8DIsReqsProcdurSameForAll'))  # no compound key in original; using direct
    _add_path_text(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs', 'rbPart3Item8dIsReqsProcdurSameForAll'], header_row.get('rbPart3Item8DIsReqsProcdurSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item8eMixltOrdrDetails'], 'rbPart3Item8eIsMixLotOrdrsAcptdExecutd', header_row.get('rbPart3Item8eIsMixLotOrdrsAcptdExecutd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item8eIsMixLotOrdrsAcptdExecutd'], header_row.get('rbPart3Item8EIsMixLotOrdrsAcptdExecutd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8eMixltOrdrDetails', 'taPart3Item8eMixltOrdrReqsProcDtls'], header_row.get('taPart3Item8eMixltOrdrReqsProcDtls'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item8eMixltOrdrDetails', 'rbPart3Item8fIsRecProcSameForAll'], header_row.get('rbPart3Item8fIsRecProcSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item9aMsgDtls'], 'rbPart3Item9aIsAnyMsgToIndicTI', header_row.get('part3Item9AMsgDtlsRbPart3Item9AIsAnyMsgToIndicTi'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item9aIsAnyMsgToIndicTI'], header_row.get('rbPart3Item9AIsAnyMsgToIndicTi'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item9aMsgDtls', 'taPart3Item9aMsgUsgDtls'], header_row.get('taPart3Item9AMsgUsgDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item9bMsgDtls'], 'rbPart3Item9bIsIndIntrstSameForAll', header_row.get('part3Item9BMsgDtlsRbPart3Item9BIsIndIntrstSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item9bIsIndIntrstSameForAll'], header_row.get('rbPart3Item9BIsIndIntrstSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item9bMsgDtls', 'taPart3Item9bMsgUsgDtls'], header_row.get('taPart3Item9BMsgUsgDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item1SubscriberType'], header_row.get('taPart3Item1SubscriberType'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item1OtherSubscrbrDtls'], header_row.get('taPart3Item1OtherSubscrbrDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item10aOpenReOpenDtls'], header_row.get('taPart3Item10aOpenReOpenDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10bIsOpnReopnSameForAll'], header_row.get('rbPart3Item10bIsOpnReopnSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item10cUnexeOrdrTIDtls'], header_row.get('taPart3Item10cUnexeOrdrTIDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10dIsAnyDifBtwnExeProcTrdHrs'], header_row.get('rbPart3Item10dIsAnyDifBtwnExeProcTrdHrs'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item10eDiffDtls'], 'rbPart3Item10eIsAnyDifBtwnPreOpExecFlwngStpg', header_row.get('rbPart3Item10EIsAnyDifBtwnPreOpExecFlwngStpg'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10eIsAnyDifBtwnPreOpExecFlwngStpg'], header_row.get('rbPart3Item10eIsAnyDifBtwnPreOpExecFlwngStpg'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item10eDiffDtls', 'taPart3Item10eDiffDtls'], header_row.get('taPart3Item10EDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item11aStrucOfNmsStk'], header_row.get('taPart3Item11aStrucOfNmsStk'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item11bMeansFeciltsDtls'], 'rbPart3Item11bIsMeansFeciltsSameForAll', header_row.get('part3Item11BMeansFeciltsDtlsRbPart3Item11BIsMeansFeciltsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item11bIsMeansFeciltsSameForAll'], header_row.get('rbPart3Item11BIsMeansFeciltsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item11bMeansFeciltsDtls', 'taPart3Item11bMeansFeciltsDtls'], header_row.get('taPart3Item11BMeansFeciltsDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item11cRulsProcsOfNmsStk'], header_row.get('taPart3Item11cRulsProcsOfNmsStk'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item11dDiffDtls'], 'rbPart3Item11dIsProcsRulsSameForAll', header_row.get('part3Item11DDiffDtlsRbPart3Item11DIsProcsRulsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item11dIsProcsRulsSameForAll'], header_row.get('rbPart3Item11DIsProcsRulsSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item11dDiffDtls', 'taPart3Item11dDiffDtls'], header_row.get('taPart3Item11DDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item12aIsAnyFrmlInfrmlArngmnts'], header_row.get('rbPart3Item12aIsAnyFrmlInfrmlArngmnts'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item13aSegmntDtls'], 'rbPart3Item13aIsOrdrTiSegmntd', header_row.get('part3Item13ASegmntDtlsRbPart3Item13AIsOrdrTiSegmntd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item13aIsOrdrTiSegmntd'], header_row.get('rbPart3Item13AIsOrdrTiSegmntd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'taPart3Item13aSegProcdurDtls'], header_row.get('taPart3Item13ASegProcdurDtls'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'rbPart3Item13bIsSegmntatnSameForAll'], header_row.get('rbPart3Item13BIsSegmntatnSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13bSegmntDtls'], 'rbPart3Item13bIsSegmntatnSameForAll', header_row.get('part3Item13BSegmntDtlsRbPart3Item13BIsSegmntatnSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13bSegmntDtls', 'taPart3Item13bSegDiffDtls'], header_row.get('taPart3Item13BSegDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item13cIsCustmrOrdr'], header_row.get('rbPart3Item13cIsCustmrOrdr'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls'], 'rbPart3Item13dIsSegCatgDisclosd', header_row.get('rbPart3Item13DIsSegCatgDisclosd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'taPart3Item13dDsclosrContntDtls'], header_row.get('taPart3Item13DDsclosrContntDtls'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'rbPart3Item13eIsDsclosrSameForAll'], header_row.get('rbPart3Item13EIsDsclosrSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'part3Item13eArngmntDtls'], 'rbPart3Item13eIsDsclosrSameForAll', header_row.get('part3Item13EArngmntDtlsRbPart3Item13EIsDsclosrSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'part3Item13eArngmntDtls', 'taPart3Item13eDsclosrDiffDtls'], header_row.get('taPart3Item13EDsclosrDiffDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls'], 'rbPart3Item14aIsDsgToIntrctOrNot', header_row.get('rbPart3Item14aIsDsgToIntrctOrNot'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item14aIsDsgToIntrctOrNot'], header_row.get('rbPart3Item14AIsDsgToIntrctOrNot'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'taPart3Item14aCntrPrtyDtls'], header_row.get('taPart3Item14aCntrPrtyDtls'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'rbPart3Item14bIsSelectnSameForAll'], header_row.get('rbPart3Item14BIsSelectnSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'part3Item14bSelectDtls'], 'rbPart3Item14bIsSelectnSameForAll', header_row.get('part3Item14BSelectDtlsRbPart3Item14BIsSelectnSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'part3Item14bSelectDtls', 'taPart3Item14bSelectnDiffDtls'], header_row.get('taPart3Item14BSelectnDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item15aIsElectrncCommu'], header_row.get('rbPart3Item15aIsElectrncCommu'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls'], 'rbPart3Item15bIsSubScrbOrdBnd', header_row.get('rbPart3Item15bIsSubScrbOrdBnd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item15bIsSubScrbOrdBnd'], header_row.get('rbPart3Item15BIsSubScrbOrdBnd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'taPart3Item15bSubscrBndDtls'], header_row.get('taPart3Item15bSubscrBndDtls'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'rbPart3Item15cIsDsplyProcSameForAll'], header_row.get('rbPart3Item15CIsDsplyProcSameForAll'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'part3Item15cDsplyProcDtls'], 'rbPart3Item15cIsDsplyProcSameForAll', header_row.get('part3Item15CDsplyProcDtlsRbPart3Item15CIsDsplyProcSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'part3Item15cDsplyProcDtls', 'taPart3Item5cDsplyProcDiffDtls'], header_row.get('taPart3Item5CDsplyProcDiffDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls'], 'rbPart3Item16aIsInstRoutd', header_row.get('rbPart3Item16AIsInstRoutd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item16aIsInstRoutd'], header_row.get('rbPart3Item16aIsInstRoutd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls', 'taPart3Item16bAffirmInstrDiffDtlsNo'], header_row.get('taPart3Item16BAffirmInstrDiffDtlsNo'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls', 'part3Item16bAffirmInstrDtls'], 'rbPart3Item16bIsRoutdBefrInstr', header_row.get('part3Item16BAffirmInstrDtlsRbPart3Item16BIsRoutdBefrInstr'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item18aTrdingHrDtls', 'rbPart3Item18cIsTrtedDiffOutsdHrs'], header_row.get('rbPart3Item16BIsRoutdBefrInstr'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls', 'part3Item16bAffirmInstrDtls', 'taPart3Item16bAffirmInstrDiffDtls'], header_row.get('taPart3Item16BAffirmInstrDiffDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item17aAffirInstrDtls'], 'rbPart3Item17aIsDiffBtwnOrdTITrtmnt', header_row.get('part3Item17AAffirInstrDtlsRbPart3Item17AIsDiffBtwnOrdTiTrtmnt'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item17aIsDiffBtwnOrdTITrtmnt'], header_row.get('rbPart3Item17AIsDiffBtwnOrdTiTrtmnt'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item17aAffirInstrDtls', 'taPart3Item17aTrtmntDiffDtls'], header_row.get('taPart3Item17ATrtmntDiffDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item17bTrtmntDtls'], 'rbPart3Item17bIsTrtmntSameForAll', header_row.get('rbPart3Item17BIsTrtmntSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item17bIsTrtmntSameForAll'], header_row.get('rbPart3Item17bIsTrtmntSameForAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item17bTrtmntDtls', 'taPart3Item17bDiffDtls'], header_row.get('taPart3Item17BDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item18aIsOutsdeTrdingHrs'], header_row.get('rbPart3Item18aIsOutsdeTrdingHrs'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item19aSrvcUsgFees'], header_row.get('taPart3Item19aSrvcUsgFees'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item19bBundldSrvcUsgFees'], header_row.get('taPart3Item19bBundldSrvcUsgFees'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item19cRbtDiscOfFees'], header_row.get('taPart3Item19cRbtDiscOfFees'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item20aSuspndProcdur'], header_row.get('taPart3Item20aSuspndProcdur'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item20bSuspndProcdurDiffDtls'], 'rbPart3Item20bIsSuspndProcdurSameFrAll', header_row.get('rbPart3Item20BIsSuspndProcdurSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item20bIsSuspndProcdurSameFrAll'], header_row.get('rbPart3Item20bIsSuspndProcdurSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item20bSuspndProcdurDiffDtls', 'taPart3Item20bDiffDtls'], header_row.get('taPart3Item20BDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item21aMtrlArngmntDtls'], header_row.get('taPart3Item21aMtrlArngmntDtls'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item21bIsMtrlArngmtSameFrAll'], header_row.get('rbPart3Item21bIsMtrlArngmtSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item22aMtrlArngmntDtls'], header_row.get('taPart3Item22aMtrlArngmntDtls'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item22bMtrlArngmntDiffDtls'], 'rbPart3Item22bIsMtrlArngmtSameFrAll', header_row.get('part3Item22BMtrlArngmntDiffDtlsRbPart3Item22BIsMtrlArngmtSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item22bIsMtrlArngmtSameFrAll'], header_row.get('rbPart3Item22BIsMtrlArngmtSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item22bMtrlArngmntDiffDtls', 'taPart3Item22bDiffDtls'], header_row.get('taPart3Item22BDiffDtls'))
    _add_path_text(root, ['formData', 'partThree', 'taPart3Item23aMrktDatSrc'], header_row.get('taPart3Item23aMrktDatSrc'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item23bIsSrcSameFrAll'], header_row.get('rbPart3Item23bIsSrcSameFrAll'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item24aIsSubScrbrOrdr'], header_row.get('rbPart3Item24aIsSubScrbrOrdr'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls'], 'rbPart3Item25aIsAvgDlyTradinVolExcd', header_row.get('rbPart3Item25AIsAvgDlyTradinVolExcd'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls', 'part3Item25bAccessDtls'], 'rbPart3Item25bIsCmplyRule301', header_row.get('rbPart3Item25BIsCmplyRule301'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls', 'part3Item25bAccessDtls', 'taPart3Item25biTickrSymbol'], header_row.get('taPart3Item25BiTickrSymbol'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls', 'part3Item25bAccessDtls', 'taPart3Item25biiDWrtnStndrds'], header_row.get('taPart3Item25BiiDWrtnStndrds'))
    _add_path_attr(root, ['formData', 'partThree', 'part3Item26PlatFrmData'], 'rbPart3Item26IsOrdrFloExecStatsPublshd', header_row.get('part3Item26PlatFrmDataRbPart3Item26IsOrdrFloExecStatsPublshd'))
    _add_path_text(root, ['formData', 'partThree', 'rbPart3Item26IsOrdrFloExecStatsPublshd'], header_row.get('rbPart3Item26IsOrdrFloExecStatsPublshd'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item26PlatFrmData', 'cbPart3Item26iInfoRqstdUndrExbt4AvlblAtWebst'], header_row.get('cbPart3Item26IInfoRqstdUndrExbt4AvlblAtWebst'))
    _add_path_text(root, ['formData', 'partThree', 'part3Item26PlatFrmData', 'cbPart3Item26iiInfoRqstdUndrExbt5AvlblAtWebst'], header_row.get('cbPart3Item26IiInfoRqstdUndrExbt5AvlblAtWebst'))

    _add_created_with_comment(root)
    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')
    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')