import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text

def construct_atsn_ua(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/atsn')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    root.set('xmlns:ats', 'http://www.sec.gov/edgar/atsncommon')
    for row in normalized_rows:
        _add_path_text(root, ['headerData', 'accessionNumber'], row.get('accessionNumber'))
        _add_path_text(root, ['headerData', 'dateCeaseToOperate'], row.get('dateCeaseToOperate'))
        _add_path_text(root, ['headerData', 'rbOperatesPursuantToFormATS'], row.get('rbOperatesPursuantToFormATS'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'cover', 'rbOperatesPursuantToFormATS'], row.get('rbOperatesPursuantToFormATS'))
        _add_path_text(root, ['formData', 'cover', 'taStatementAboutAmendment'], row.get('taStatementAboutAmendment'))
        _add_path_text(root, ['formData', 'cover', 'txNMSStockATSName'], row.get('txNMSStockATSName'))
        _add_path_text(root, ['formData', 'partOne', 'cbPart1Item8Exhibit1atWebsite'], row.get('cbPart1Item8Exhibit1atWebsite'))
        _add_path_text(root, ['formData', 'partOne', 'cbPart1Item9Exhibit2atWebsite'], row.get('cbPart1Item9Exhibit2atWebsite'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item5bEffectiveMembershipDate'], row.get('part1Item5bEffectiveMembershipDate'))
        _add_path_text(root, ['formData', 'partOne', 'rbPart1Item1IsBd'], row.get('rbPart1Item1IsBd'))
        _add_path_text(root, ['formData', 'partOne', 'txPart1Item2ATSName'], row.get('txPart1Item2ATSName'))
        _add_path_text(root, ['formData', 'partOne', 'txPart1Item4aBdCrdNumber'], row.get('txPart1Item4aBdCrdNumber'))
        _add_path_text(root, ['formData', 'partOne', 'txPart1Item4aBdFileNumber'], row.get('txPart1Item4aBdFileNumber'))
        _add_path_text(root, ['formData', 'partOne', 'txPart1Item5aNsaFullName'], row.get('txPart1Item5aNsaFullName'))
        _add_path_text(root, ['formData', 'partOne', 'txtPart1Item5cNmsStockMPID'], row.get('txtPart1Item5cNmsStockMPID'))
        _add_path_text(root, ['formData', 'partOne', 'txtPart1Item6uwebsite'], row.get('txtPart1Item6uwebsite'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10bIsOpnReopnSameForAll'], row.get('rbPart3Item10bIsOpnReopnSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10dIsAnyDifBtwnExeProcTrdHrs'], row.get('rbPart3Item10dIsAnyDifBtwnExeProcTrdHrs'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item10eIsAnyDifBtwnPreOpExecFlwngStpg'], row.get('rbPart3Item10eIsAnyDifBtwnPreOpExecFlwngStpg'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item11bIsMeansFeciltsSameForAll'], row.get('rbPart3Item11bIsMeansFeciltsSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item11dIsProcsRulsSameForAll'], row.get('rbPart3Item11dIsProcsRulsSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item12aIsAnyFrmlInfrmlArngmnts'], row.get('rbPart3Item12aIsAnyFrmlInfrmlArngmnts'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item13aIsOrdrTiSegmntd'], row.get('rbPart3Item13aIsOrdrTiSegmntd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item13cIsCustmrOrdr'], row.get('rbPart3Item13cIsCustmrOrdr'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item14aIsDsgToIntrctOrNot'], row.get('rbPart3Item14aIsDsgToIntrctOrNot'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item15aIsElectrncCommu'], row.get('rbPart3Item15aIsElectrncCommu'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item15bIsSubScrbOrdBnd'], row.get('rbPart3Item15bIsSubScrbOrdBnd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item16aIsInstRoutd'], row.get('rbPart3Item16aIsInstRoutd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item17aIsDiffBtwnOrdTITrtmnt'], row.get('rbPart3Item17aIsDiffBtwnOrdTITrtmnt'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item17bIsTrtmntSameForAll'], row.get('rbPart3Item17bIsTrtmntSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item18aIsOutsdeTrdingHrs'], row.get('rbPart3Item18aIsOutsdeTrdingHrs'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item20bIsSuspndProcdurSameFrAll'], row.get('rbPart3Item20bIsSuspndProcdurSameFrAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item21bIsMtrlArngmtSameFrAll'], row.get('rbPart3Item21bIsMtrlArngmtSameFrAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item22bIsMtrlArngmtSameFrAll'], row.get('rbPart3Item22bIsMtrlArngmtSameFrAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item23bIsSrcSameFrAll'], row.get('rbPart3Item23bIsSrcSameFrAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item24aIsSubScrbrOrdr'], row.get('rbPart3Item24aIsSubScrbrOrdr'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item25aIsAvgDlyTradinVolExcd'], row.get('rbPart3Item25aIsAvgDlyTradinVolExcd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item26IsOrdrFloExecStatsPublshd'], row.get('rbPart3Item26IsOrdrFloExecStatsPublshd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item2aRegisteredBD'], row.get('rbPart3Item2aRegisteredBD'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item2dIsThereWrittenAgreement'], row.get('rbPart3Item2dIsThereWrittenAgreement'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item4bIsHrsOfOperationsame'], row.get('rbPart3Item4bIsHrsOfOperationsame'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item5aIsPermitOrdrTradng'], row.get('rbPart3Item5aIsPermitOrdrTradng'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item5cIsAnyOtherMeans'], row.get('rbPart3Item5cIsAnyOtherMeans'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item6aIsCoLocRltdSrvcsOfrd'], row.get('rbPart3Item6aIsCoLocRltdSrvcsOfrd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item6cIsAnyOtherMeans'], row.get('rbPart3Item6cIsAnyOtherMeans'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item6eIsAnyRducdSpOfCom'], row.get('rbPart3Item6eIsAnyRducdSpOfCom'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item7bIsTnCSameForAll'], row.get('rbPart3Item7bIsTnCSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item8cIsOddLotsAcptdExecutd'], row.get('rbPart3Item8cIsOddLotsAcptdExecutd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item8eIsMixLotOrdrsAcptdExecutd'], row.get('rbPart3Item8eIsMixLotOrdrsAcptdExecutd'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item9aIsAnyMsgToIndicTI'], row.get('rbPart3Item9aIsAnyMsgToIndicTI'))
        _add_path_text(root, ['formData', 'partThree', 'rbPart3Item9bIsIndIntrstSameForAll'], row.get('rbPart3Item9bIsIndIntrstSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item10aOpenReOpenDtls'], row.get('taPart3Item10aOpenReOpenDtls'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item10cUnexeOrdrTIDtls'], row.get('taPart3Item10cUnexeOrdrTIDtls'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item11aStrucOfNmsStk'], row.get('taPart3Item11aStrucOfNmsStk'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item11cRulsProcsOfNmsStk'], row.get('taPart3Item11cRulsProcsOfNmsStk'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item19aSrvcUsgFees'], row.get('taPart3Item19aSrvcUsgFees'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item19bBundldSrvcUsgFees'], row.get('taPart3Item19bBundldSrvcUsgFees'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item19cRbtDiscOfFees'], row.get('taPart3Item19cRbtDiscOfFees'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item1OtherSubscrbrDtls'], row.get('taPart3Item1OtherSubscrbrDtls'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item1SubscriberType'], row.get('taPart3Item1SubscriberType'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item20aSuspndProcdur'], row.get('taPart3Item20aSuspndProcdur'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item21aMtrlArngmntDtls'], row.get('taPart3Item21aMtrlArngmntDtls'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item22aMtrlArngmntDtls'], row.get('taPart3Item22aMtrlArngmntDtls'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item23aMrktDatSrc'], row.get('taPart3Item23aMrktDatSrc'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item4aHrsOfOperation'], row.get('taPart3Item4aHrsOfOperation'))
        _add_path_text(root, ['formData', 'partThree', 'taPart3Item7AOrdrTypExplain'], row.get('taPart3Item7AOrdrTypExplain'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item1aArePermittedToEnterInterest'], row.get('rbPart2Item1aArePermittedToEnterInterest'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item1dCanOATInterestBeRouted'], row.get('rbPart2Item1dCanOATInterestBeRouted'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item2aAreAfflPermittedToEnterInterest'], row.get('rbPart2Item2aAreAfflPermittedToEnterInterest'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item2dCanOATIBeRoutedByAffl'], row.get('rbPart2Item2dCanOATIBeRoutedByAffl'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3aCanSubscrOptOutWithOATIOfAffl'], row.get('rbPart2Item3aCanSubscrOptOutWithOATIOfAffl'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3aCanSubscrOptOutWithOATIOfBD'], row.get('rbPart2Item3aCanSubscrOptOutWithOATIOfBD'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item3cAreOptOutSametoAllSubscribers'], row.get('rbPart2Item3cAreOptOutSametoAllSubscribers'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item4aAreThereArrangementsBtwBDAndTC'], row.get('rbPart2Item4aAreThereArrangementsBtwBDAndTC'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item5cDoesAfflOfferProductsAndServices'], row.get('rbPart2Item5cDoesAfflOfferProductsAndServices'))
        _add_path_text(root, ['formData', 'partTwo', 'rbPart2Item7bCanSubscriberConsentToDisclosure'], row.get('rbPart2Item7bCanSubscriberConsentToDisclosure'))
        _add_path_text(root, ['formData', 'partTwo', 'taPart2Item7aDescrOfSafeGaurdsAndProcedures'], row.get('taPart2Item7aDescrOfSafeGaurdsAndProcedures'))
        _add_path_text(root, ['formData', 'partTwo', 'taPart2Item7dSummaryOfRolesRespOfPersons'], row.get('taPart2Item7dSummaryOfRolesRespOfPersons'))
        _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], row.get('liveTestFlag'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'state'], row.get('state'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'street1'], row.get('street1'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'street2'], row.get('street2'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7PrimarySite', 'zip'], row.get('zip'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item10eDiffDtls', 'taPart3Item10eDiffDtls'], row.get('taPart3Item10eDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item11bMeansFeciltsDtls', 'taPart3Item11bMeansFeciltsDtls'], row.get('taPart3Item11bMeansFeciltsDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item11dDiffDtls', 'taPart3Item11dDiffDtls'], row.get('taPart3Item11dDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item17aAffirInstrDtls', 'taPart3Item17aTrtmntDiffDtls'], row.get('taPart3Item17aTrtmntDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'rbPart3Item13bIsSegmntatnSameForAll'], row.get('rbPart3Item13bIsSegmntatnSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'taPart3Item13aSegProcdurDtls'], row.get('taPart3Item13aSegProcdurDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'rbPart3Item14bIsSelectnSameForAll'], row.get('rbPart3Item14bIsSelectnSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'taPart3Item14aCntrPrtyDtls'], row.get('taPart3Item14aCntrPrtyDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'rbPart3Item15cIsDsplyProcSameForAll'], row.get('rbPart3Item15cIsDsplyProcSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'taPart3Item15bSubscrBndDtls'], row.get('taPart3Item15bSubscrBndDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item18aTrdingHrDtls', 'rbPart3Item18cIsTrtedDiffOutsdHrs'], row.get('rbPart3Item18cIsTrtedDiffOutsdHrs'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls', 'taPart3Item16bAffirmInstrDiffDtlsNo'], row.get('taPart3Item16bAffirmInstrDiffDtlsNo'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item17bTrtmntDtls', 'taPart3Item17bDiffDtls'], row.get('taPart3Item17bDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item20bSuspndProcdurDiffDtls', 'taPart3Item20bDiffDtls'], row.get('taPart3Item20bDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item22bMtrlArngmntDiffDtls', 'taPart3Item22bDiffDtls'], row.get('taPart3Item22bDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item26PlatFrmData', 'cbPart3Item26iInfoRqstdUndrExbt4AvlblAtWebst'], row.get('cbPart3Item26iInfoRqstdUndrExbt4AvlblAtWebst'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item26PlatFrmData', 'cbPart3Item26iiInfoRqstdUndrExbt5AvlblAtWebst'], row.get('cbPart3Item26iiInfoRqstdUndrExbt5AvlblAtWebst'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'rbPart3Item2cIsConditionsSameForAll'], row.get('rbPart3Item2cIsConditionsSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'taPart3Item2bSummaryOfCndtns'], row.get('taPart3Item2bSummaryOfCndtns'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'rbPart3Item3bIsCondtnsSameForAll'], row.get('rbPart3Item3bIsCondtnsSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'taPart3Item3aExcludngSumryDtls'], row.get('taPart3Item3aExcludngSumryDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'rbPart3Item5bIsProtclsameForAll'], row.get('rbPart3Item5bIsProtclsameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'taPart3Item5aProtocolused'], row.get('taPart3Item5aProtocolused'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'rbPart3Item5dIsTnCSameForAll'], row.get('rbPart3Item5dIsTnCSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'taPart3Item5cOthrMeansDtls'], row.get('taPart3Item5cOthrMeansDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'rbPart3Item6bIsTNCsameForAll'], row.get('rbPart3Item6bIsTNCsameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'taPart3Item6aCoLocRltdSrvcsDtls'], row.get('taPart3Item6aCoLocRltdSrvcsDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item7bTnCDetails', 'taPart3Item7bTnCSumryDtls'], row.get('taPart3Item7bTnCSumryDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'rbPart3Item8bIsReqProcSameForAll'], row.get('rbPart3Item8bIsReqProcSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'taPart3Item8aOtiSizeReqrmns'], row.get('taPart3Item8aOtiSizeReqrmns'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs', 'rbPart3Item8dIsReqsProcdurSameForAll'], row.get('rbPart3Item8dIsReqsProcdurSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8cOddltOrdrReqs', 'taPart3Item8cOddLtOrdrReqsnProcdurs'], row.get('taPart3Item8cOddLtOrdrReqsnProcdurs'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8eMixltOrdrDetails', 'rbPart3Item8fIsRecProcSameForAll'], row.get('rbPart3Item8fIsRecProcSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8eMixltOrdrDetails', 'taPart3Item8eMixltOrdrReqsProcDtls'], row.get('taPart3Item8eMixltOrdrReqsProcDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item9aMsgDtls', 'taPart3Item9aMsgUsgDtls'], row.get('taPart3Item9aMsgUsgDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item9bMsgDtls', 'taPart3Item9bMsgUsgDtls'], row.get('taPart3Item9bMsgUsgDtls'))
        _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'rbPart2Item2bAreSevicestoAfflSametoSubscribers'], row.get('rbPart2Item2bAreSevicestoAfflSametoSubscribers'))
        _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'rbPart2Item2cAreThereArrangementsWithAffl'], row.get('rbPart2Item2cAreThereArrangementsWithAffl'))
        _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'taPart2Item2aAfflThatEnterInterest'], row.get('taPart2Item2aAfflThatEnterInterest'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'rbPart2Item1bAreSevicesSametoAllSubscribers'], row.get('rbPart2Item1bAreSevicesSametoAllSubscribers'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'rbPart2Item1cAreThereArrangements'], row.get('rbPart2Item1cAreThereArrangements'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'taPart2Item1aUnitNamesEnterInterest'], row.get('taPart2Item1aUnitNamesEnterInterest'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfAffl', 'taPart2Item3bExplianOptOut'], row.get('taPart2Item3bExplianOptOut'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item3aCanSubscrOptOutWithOATIOfBD', 'taPart2Item3aExplianOptOut'], row.get('taPart2Item3aExplianOptOut'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item3cAreOptOutSametoAllSubscribers', 'taPart2Item3cExplainDiff'], row.get('taPart2Item3cExplainDiff'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item4aAreThereArrangementsBtwBDAndTC', 'rbPart2Item4bAreThereArrangementsBtwAfflAndTC'], row.get('rbPart2Item4bAreThereArrangementsBtwAfflAndTC'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item4aAreThereArrangementsBtwBDAndTC', 'taPart2Item4aTDAndATSServices'], row.get('taPart2Item4aTDAndATSServices'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'rbPart2Item5bAreSevicesSametoAllSubscribersAndBD'], row.get('rbPart2Item5bAreSevicesSametoAllSubscribersAndBD'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'taPart2Item5aProductsAndServices'], row.get('taPart2Item5aProductsAndServices'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item6aDoesEmployeeAccessConfidentialInfo', 'taPart2Item6aUnitAfflEmployeeServices'], row.get('taPart2Item6aUnitAfflEmployeeServices'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'rbPart2Item6cDoesServiceProviderUseATSServices'], row.get('rbPart2Item6cDoesServiceProviderUseATSServices'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'taPart2Item6bServiceProvider'], row.get('taPart2Item6bServiceProvider'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure', 'taPart2Item7bExplainHowAndConditions'], row.get('taPart2Item7bExplainHowAndConditions'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactEmailAddress'], row.get('contactEmailAddress'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactName'], row.get('contactName'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'contactPhoneNumber'], row.get('contactPhoneNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'MPID'], row.get('MPID'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'NMSStockATSName'], row.get('NMSStockATSName'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'confirmingCopyFlag'], row.get('confirmingCopyFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], row.get('overrideInternetFlag'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords', 'secondarySiteI7', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords', 'secondarySiteI7', 'state'], row.get('state'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords', 'secondarySiteI7', 'street1'], row.get('street1'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords', 'secondarySiteI7', 'street2'], row.get('street2'))
        _add_path_text(root, ['formData', 'partOne', 'part1Item7SecondarySiteRecords', 'secondarySiteI7', 'zip'], row.get('zip'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13bSegmntDtls', 'taPart3Item13bSegDiffDtls'], row.get('taPart3Item13bSegDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'rbPart3Item13eIsDsclosrSameForAll'], row.get('rbPart3Item13eIsDsclosrSameForAll'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'taPart3Item13dDsclosrContntDtls'], row.get('taPart3Item13dDsclosrContntDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item14aCntrPrtySelectnDtls', 'part3Item14bSelectDtls', 'taPart3Item14bSelectnDiffDtls'], row.get('taPart3Item14bSelectnDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item15bSubSctbDtls', 'part3Item15cDsplyProcDtls', 'taPart3Item5cDsplyProcDiffDtls'], row.get('taPart3Item5cDsplyProcDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item16aAffirInstrDtls', 'part3Item16bAffirmInstrDtls', 'taPart3Item16bAffirmInstrDiffDtls'], row.get('taPart3Item16bAffirmInstrDiffDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls', 'part3Item25bAccessDtls', 'taPart3Item25biTickrSymbol'], row.get('taPart3Item25biTickrSymbol'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item25aSubScrbrOrdrDtls', 'part3Item25bAccessDtls', 'taPart3Item25biiDWrtnStndrds'], row.get('taPart3Item25biiDWrtnStndrds'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item2bSummaryOfConditions', 'part3Item2cSummaryOfConditions', 'taPart3Item2cSummaryOfDifferences'], row.get('taPart3Item2cSummaryOfDifferences'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item3aSumryOfExcludngCondtns', 'part3Item3bSummaryOfConditions', 'taPart3Item3bSummaryOfDifferences'], row.get('taPart3Item3bSummaryOfDifferences'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5aProtocolDetails', 'part3Item5bProtocolDetails', 'taPart3Item5aProtocolSumryDtls'], row.get('taPart3Item5aProtocolSumryDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item5cOthrDtls', 'part3Item5dTnCDetails', 'taPart3Item5dTnCSumryDtls'], row.get('taPart3Item5dTnCSumryDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item6aProtocolDetails', 'part3Item6bTNCDetails', 'taPart3Item6bTNCSumryDtls'], row.get('taPart3Item6bTNCSumryDtls'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item8aSizeReqrmnts', 'part3Item8bReqProcDetails', 'taPart3Item8bDiffrncsInOtiReqrmnts'], row.get('taPart3Item8bDiffrncsInOtiReqrmnts'))
        _add_path_text(root, ['formData', 'partTwo', 'affiliatesPermittedToEnterInterest', 'part2Item2bAreSevicestoAfflSametoSubscribers', 'taPart2Item2bExplainDiff'], row.get('taPart2Item2bExplainDiff'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item1aArePermittedToEnterInterest', 'part2Item1bAreSevicesSametoAllSubscribers', 'taPart2Item2bExplainDiff'], row.get('taPart2Item2bExplainDiff'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item5aDoesOfferProductsAndServices', 'part2Item5bAreSevicesSametoAllSubscribersAndBD', 'taPart2Item5bExplainDiff'], row.get('taPart2Item5bExplainDiff'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'part2Item6cDoesServiceProviderUseATSServices', 'rbPart2Item6dAreATSSevicesSametoAll'], row.get('rbPart2Item6dAreATSSevicesSametoAll'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item6bDoesAnyEntitySupportServices', 'part2Item6cDoesServiceProviderUseATSServices', 'taPart2Item6cProviderAfflAndServicesUsed'], row.get('taPart2Item6cProviderAfflAndServicesUsed'))
        _add_path_text(root, ['formData', 'partTwo', 'part2Item7bCanSubscriberConsentToDisclosure', 'part2Item7cCanSubscriberWithdrawConsent', 'taPart2Item7cExplainHowAndConditions'], row.get('taPart2Item7cExplainHowAndConditions'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('cik'))
        _add_path_text(root, ['formData', 'partThree', 'part3Item13aSegmntDtls', 'part3Item13dDsclrContntDtls', 'part3Item13eArngmntDtls', 'taPart3Item13eDsclosrDiffDtls'], row.get('taPart3Item13eDsclosrDiffDtls'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')






