import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_cfportal(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/crowdfunding')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    for row in normalized_rows:
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'compensationDesc'], row.get('escrowCompensationDesc'))
        _add_path_text(root, ['formData', 'execution', 'executionDate'], row.get('executionDate'))
        _add_path_text(root, ['formData', 'execution', 'fullLegalNameFundingPortal'], row.get('executionFullLegalName'))
        _add_path_text(root, ['formData', 'execution', 'personSignature'], row.get('executionSignature'))
        _add_path_text(root, ['formData', 'execution', 'personTitle'], row.get('executionTitle'))
        _add_path_text(root, ['formData', 'formOfOrganization', 'dateIncorporation'], row.get('dateIncorporation'))
        _add_path_text(root, ['formData', 'formOfOrganization', 'jurisdictionOrganization'], row.get('jurisdictionOrganization'))
        _add_path_text(root, ['formData', 'formOfOrganization', 'legalStatusForm'], row.get('legalStatusForm'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'amendmentExplanation'], row.get('amendmentExplanation'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'anyForeignRegistrations'], row.get('anyForeignRegistrations'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'anyPreviousRegistrations'], row.get('anyPreviousRegistrations'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeTitle'], row.get('contactTitle'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'fiscalYearEnd'], row.get('fiscalYearEnd'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'irsEmployerIdNumber'], row.get('irsEmployerIdNumber'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'legalNameChange'], row.get('legalNameChange'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'mailingAddressDifferent'], row.get('mailingAddressDifferent'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'nameOfPortal'], row.get('nameOfPortal'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'secFileNumbers'], row.get('secFileNumbers'))
        _add_path_text(root, ['formData', 'nonSecuritiesRelatedBusiness', 'isEngagedInNonSecurities'], row.get('isEngagedInNonSecurities'))
        _add_path_text(root, ['formData', 'nonSecuritiesRelatedBusiness', 'nonSecuritiesBusinessDesc'], row.get('nonSecuritiesBusinessDesc'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentName'], row.get('agentName'))
        _add_path_text(root, ['formData', 'scheduleC', 'personSignature'], row.get('scheduleCSignature'))
        _add_path_text(root, ['formData', 'scheduleC', 'personTitle'], row.get('scheduleCTitle'))
        _add_path_text(root, ['formData', 'scheduleC', 'printedName'], row.get('scheduleCPrintedName'))
        _add_path_text(root, ['formData', 'scheduleC', 'signatureDate'], row.get('scheduleCSignatureDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'dateBusinessCeasedWithdrawn'], row.get('dateBusinessCeasedWithdrawn'))
        _add_path_text(root, ['formData', 'scheduleD', 'investorInitiatedComplaint'], row.get('investorInitiatedComplaint'))
        _add_path_text(root, ['formData', 'scheduleD', 'isInvestigated'], row.get('isInvestigated'))
        _add_path_text(root, ['formData', 'scheduleD', 'privateCivilLitigation'], row.get('privateCivilLitigation'))
        _add_path_text(root, ['formData', 'successions', 'isSucceedingBusiness'], row.get('isSucceedingBusiness'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'drpFiledFor'], row.get('drpFiledFor'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'initialOrAmended'], row.get('initialOrAmended'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'drpFiledFor'], row.get('civilJudicialDrpDrpFiledFor'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'initialOrAmended'], row.get('civilJudicialDrpInitialOrAmended'))
        _add_path_text(root, ['formData', 'controlRelationships', 'fullLegalNames', 'fullLegalName'], row.get('controlRelationshipFullLegalName'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilJudicialActionDisclosure', 'isDismissed'], row.get('isDismissed'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilJudicialActionDisclosure', 'isEnjoined'], row.get('isEnjoined'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilJudicialActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('civilIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilJudicialActionDisclosure', 'isNamedInCivilProceeding'], row.get('isNamedInCivilProceeding'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isChargedMisdemeanor'], row.get('isChargedMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isChargedWithFelony'], row.get('isChargedWithFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isConvictedMisdemeanor'], row.get('isConvictedMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isConvictedOfFelony'], row.get('isConvictedOfFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'financialDisclosure', 'doesAppHaveLiens'], row.get('doesAppHaveLiens'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'financialDisclosure', 'hasBondDenied'], row.get('hasBondDenied'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'financialDisclosure', 'hasSubjectOfBankruptcy'], row.get('hasSubjectOfBankruptcy'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'financialDisclosure', 'hasTrusteeAppointed'], row.get('hasTrusteeAppointed'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isAuthorizedToActAttorney'], row.get('isAuthorizedToActAttorney'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isCauseOfDenial'], row.get('isCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isDeniedLicense'], row.get('isDeniedLicense'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isDisciplined'], row.get('isDisciplined'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isFoundInCauseOfDenial'], row.get('isFoundInCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isFoundInCauseOfSuspension'], row.get('isFoundInCauseOfSuspension'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('isFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isFoundInViolationOfRules'], row.get('isFoundInViolationOfRules'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isFoundMadeFalseStatement'], row.get('isFoundMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isImposedPenalty'], row.get('isImposedPenalty'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isMadeFalseStatement'], row.get('isMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isOrderAgainst'], row.get('isOrderAgainst'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isOrderAgainstActivity'], row.get('isOrderAgainstActivity'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isRegulatoryComplaint'], row.get('isRegulatoryComplaint'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isUnEthical'], row.get('isUnEthical'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryActionDisclosure', 'isViolatedRegulation'], row.get('isViolatedRegulation'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsContactName'], row.get('investorFundsContactName'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsContactPhone'], row.get('investorFundsContactPhone'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeName', 'firstName'], row.get('contactFirstName'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeName', 'lastName'], row.get('contactLastName'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeName', 'middleName'], row.get('contactMiddleName'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeName', 'prefix'], row.get('contactPrefix'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'contactEmployeeName', 'suffix'], row.get('suffix'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherNamesAndWebsiteUrls', 'otherNamesUsedPortal'], row.get('otherNamesUsed'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherNamesAndWebsiteUrls', 'webSiteOfPortal'], row.get('webSiteOfPortal'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherOfficeLocationAddress', 'city'], row.get('otherOfficeLocationAddressPortalCity'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherOfficeLocationAddress', 'stateOrCountry'], row.get('otherOfficeLocationAddressPortalStateOrCountry'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherOfficeLocationAddress', 'street1'], row.get('otherOfficeLocationAddressPortalStreet1'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherOfficeLocationAddress', 'street2'], row.get('otherOfficeLocationAddressPortalStreet2'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'otherOfficeLocationAddress', 'zipCode'], row.get('otherOfficeLocationAddressPortalZipCode'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalAddress', 'city'], row.get('portalAddressPortalCity'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalAddress', 'stateOrCountry'], row.get('portalAddressPortalStateOrCountry'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalAddress', 'street1'], row.get('portalAddressPortalStreet1'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalAddress', 'street2'], row.get('portalAddressPortalStreet2'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalAddress', 'zipCode'], row.get('portalAddressPortalZipCode'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalContact', 'portalContactEmail'], row.get('portalContactEmail'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalContact', 'portalContactFax'], row.get('portalContactFax'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalContact', 'portalContactPhone'], row.get('portalContactPhone'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalMailingAddress', 'city'], row.get('mailingCity'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalMailingAddress', 'stateOrCountry'], row.get('mailingStateOrCountry'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalMailingAddress', 'street1'], row.get('mailingStreet1'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalMailingAddress', 'street2'], row.get('mailingStreet2'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'portalMailingAddress', 'zipCode'], row.get('mailingZipCode'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'prevNamesAndWebsiteUrls', 'prevNamesOfPortal'], row.get('prevNamesOfPortal'))
        _add_path_text(root, ['formData', 'identifyingInformation', 'prevNamesAndWebsiteUrls', 'prevWebSiteUrls'], row.get('prevWebSiteUrls'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'controlPerson'], row.get('scheduleAControlPerson'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'crdNumber'], row.get('scheduleACrdNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'dateOfTitleStatusAcquired'], row.get('scheduleADateOfTitleStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'entityType'], row.get('scheduleAEntityType'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'fullLegalName'], row.get('scheduleAFullLegalName'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'ownershipCode'], row.get('scheduleAOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleA', 'entityOrNaturalPerson', 'titleStatus'], row.get('scheduleATitleStatus'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'controlPerson'], row.get('scheduleBControlPerson'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'crdNumber'], row.get('scheduleBCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'dateOfTitleStatusAcquired'], row.get('scheduleBDateOfTitleStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'entityType'], row.get('scheduleBEntityType'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'fullLegalName'], row.get('scheduleBFullLegalName'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'ownershipCode'], row.get('scheduleBOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'titleStatus'], row.get('scheduleBTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleB', 'amendEntityOrNaturalPerson', 'typeOfAmendment'], row.get('scheduleBTypeOfAmendment'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentAddress', 'city'], row.get('portalCity'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentAddress', 'stateOrCountry'], row.get('portalStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentAddress', 'street1'], row.get('portalStreet1'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentAddress', 'street2'], row.get('portalStreet2'))
        _add_path_text(root, ['formData', 'scheduleC', 'agentAddress', 'zipCode'], row.get('portalZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityFax'], row.get('bookKeepingEntityFax'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityName'], row.get('bookKeepingEntityName'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityPhone'], row.get('bookKeepingEntityPhone'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityType'], row.get('bookKeepingEntityType'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingLocationDesc'], row.get('bookKeepingLocationDesc'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'isAddressPrivateResidence'], row.get('isAddressPrivateResidence'))
        _add_path_text(root, ['formData', 'successions', 'acquiredHistoryDetails', 'acquiredDesc'], row.get('acquiredDesc'))
        _add_path_text(root, ['formData', 'successions', 'acquiredHistoryDetails', 'acquiredFundingPortal'], row.get('acquiredFundingPortal'))
        _add_path_text(root, ['formData', 'successions', 'acquiredHistoryDetails', 'acquiredPortalFileNumber'], row.get('acquiredPortalFileNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], row.get('filerCcc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'confirmingCopyFlag'], row.get('confirmingCopyFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], row.get('overrideInternetFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], row.get('returnCopyFlag'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'respondingTo', 'responseQuestion'], row.get('responseQuestion'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'respondingTo', 'responseQuestion'], row.get('respondingToResponseQuestion'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'summaryOfDetails'], row.get('summaryOfCircumstances'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'summaryOfCircumstances'], row.get('civilJudicialDrpDetailsSummaryOfCircumstances'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsAddress', 'city'], row.get('investorFundsCity'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsAddress', 'stateOrCountry'], row.get('investorFundsStateOrCountry'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsAddress', 'street1'], row.get('investorFundsStreet1'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsAddress', 'street2'], row.get('investorFundsStreet2'))
        _add_path_text(root, ['formData', 'escrowArrangements', 'investorFundsContacts', 'investorFundsAddress', 'zipCode'], row.get('investorFundsZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityAddress', 'city'], row.get('bookKeepingEntityAddressPortalCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityAddress', 'stateOrCountry'], row.get('bookKeepingEntityAddressPortalStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityAddress', 'street1'], row.get('bookKeepingEntityAddressPortalStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityAddress', 'street2'], row.get('bookKeepingEntityAddressPortalStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'bookKeepingDetails', 'bookKeepingEntityAddress', 'zipCode'], row.get('bookKeepingEntityAddressPortalZipCode'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'filerCik'], row.get('filerCik'))
        _add_path_text(root, ['formData', 'bankruptcySipcDrpInfo', 'bankruptcyDrp', 'affiliatePerson', 'affBankruptcySipcDrpDetails', 'apCrdNumber'], row.get('apCrdNumber'))
        _add_path_text(root, ['formData', 'bankruptcySipcDrpInfo', 'bankruptcyDrp', 'affiliatePerson', 'affBankruptcySipcDrpDetails', 'controlAffiliateType'], row.get('controlAffiliateType'))
        _add_path_text(root, ['formData', 'bankruptcySipcDrpInfo', 'bankruptcyDrp', 'affiliatePerson', 'affBankruptcySipcDrpDetails', 'isConAffRegisteredCrd'], row.get('isConAffRegisteredCrd'))
        _add_path_text(root, ['formData', 'bankruptcySipcDrpInfo', 'bankruptcyDrp', 'affiliatePerson', 'affBankruptcySipcDrpDetails', 'isRegistered'], row.get('isRegistered'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'cityOrCounty'], row.get('cityOrCounty'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'civilActionCourtName'], row.get('civilActionCourtName'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'civilActionCourtType'], row.get('civilActionCourtType'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'regulatoryActionInitiatedBy'], row.get('courtActionInitiatorName'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'descAllegations'], row.get('describeCivilActionAllegations'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'docketOrCaseNumber'], row.get('docketOrCaseNumber'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'currentStatus'], row.get('eventCurrentStatus'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'regulatorName'], row.get('grantOrFineAmount'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'matterResolvedType'], row.get('matterResolveType'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'otherProductDesc'], row.get('otherPrincipalProductType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'principalReliefSought'], row.get('principalReliefSought'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'principalProductTypeOtherDesc'], row.get('principalProductType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'sanctionDetail'], row.get('sanctionDetail'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'stateOrCountry'], row.get('civilJudicialDrpDetailsPortalStateOrCountry'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'associatedPersonDetails', 'crdNumber'], row.get('associatedPersonDetailsScheduleACrdNumber'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'associatedPersonDetails', 'fullName'], row.get('fullName'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'associatedPersonDetails', 'personRegistered'], row.get('personRegistered'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'associatedPersonDetails', 'personType'], row.get('personType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'cityOrCounty'], row.get('civilJudicialDrpDetailsCityOrCounty'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'civilActionCourtName'], row.get('civilJudicialDrpDetailsCivilActionCourtName'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'civilActionCourtType'], row.get('civilJudicialDrpDetailsCivilActionCourtType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'courtActionInitiatorName'], row.get('civilJudicialDrpDetailsCourtActionInitiatorName'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'describeCivilActionAllegations'], row.get('civilJudicialDrpDetailsDescribeCivilActionAllegations'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'docketOrCaseNumber'], row.get('civilJudicialDrpDetailsDocketOrCaseNumber'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'eventCurrentStatus'], row.get('civilJudicialDrpDetailsEventCurrentStatus'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'grantOrFineAmount'], row.get('civilJudicialDrpDetailsGrantOrFineAmount'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'matterResolveType'], row.get('civilJudicialDrpDetailsMatterResolveType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'otherPrincipalProductType'], row.get('civilJudicialDrpDetailsOtherPrincipalProductType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'principalReliefSought'], row.get('civilJudicialDrpDetailsPrincipalReliefSought'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'principalProductType'], row.get('civilJudicialDrpDetailsPrincipalProductType'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'sanctionDetail'], row.get('civilJudicialDrpDetailsSanctionDetail'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'stateOrCountry'], row.get('associatedPersonCivilJudicialDrpDetailsPortalStateOrCountry'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'filingDateOfCourtActionExactOrExplain', 'date'], row.get('filingDateOfCourtActionExactOrExplainDate'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'applicant', 'civilJudicialDrpDetails', 'filingDateOfCourtActionExactOrExplain', 'exactOrExplanation'], row.get('filingDateOfCourtActionExactOrExplainExactOrExplanation'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'resolutionDateExactExplain', 'date'], row.get('date'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'resolutionDateExactExplain', 'exactOrExplanation'], row.get('exactOrExplanation'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'applicant', 'regulatoryDrpDetails', 'sanctionsOrderedDetails', 'sanctionsOrdered', 'sanctionOrdered'], row.get('sanctionOrdered'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'filingDateOfCourtActionExactOrExplain', 'date'], row.get('civilJudicialDrpDetailsFilingDateOfCourtActionExactOrExplainDate'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'filingDateOfCourtActionExactOrExplain', 'exactOrExplanation'], row.get('civilJudicialDrpDetailsFilingDateOfCourtActionExactOrExplainExactOrExplanation'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'resolutionDateExactOrExplain', 'date'], row.get('resolutionDateExactOrExplainDate'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'resolutionDateExactOrExplain', 'exactOrExplanation'], row.get('resolutionDateExactOrExplainExactOrExplanation'))
        _add_path_text(root, ['formData', 'civilJudicialDrpInfo', 'civilJudicialDrp', 'associatedPerson', 'civilJudicialDrpDetails', 'sanctionReliefType', 'sanctionOrdered'], row.get('sanctionReliefTypeSanctionOrdered'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




