import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_ma(rows: list) -> bytes:

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/mafiler')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common_ma')
    root.set('xmlns:com1', 'http://www.sec.gov/edgar/common')
    for row in rows:
        _add_path_text(root, ['formData', 'calYearEnd'], row.get('calYearEnd'))
        _add_path_text(root, ['formData', 'clientsServedAsMA'], row.get('clientsServedAsMA'))
        _add_path_text(root, ['formData', 'dateOfOrganization'], row.get('dateOfOrganization'))
        _add_path_text(root, ['formData', 'dbaName'], row.get('dbaName'))
        _add_path_text(root, ['formData', 'employeesEngagedInMAA'], row.get('employeesEngagedInMAA'))
        _add_path_text(root, ['formData', 'firmCrdNumber'], row.get('firmCrdNumber'))
        _add_path_text(root, ['formData', 'firmName'], row.get('firmName'))
        _add_path_text(root, ['formData', 'fiscalYearEnd'], row.get('fiscalYearEnd'))
        _add_path_text(root, ['formData', 'hasAnnualReceiptsLessThan7Million'], row.get('hasAnnualReceiptsLessThan7Million'))
        _add_path_text(root, ['formData', 'hasChanges'], row.get('hasChanges'))
        _add_path_text(root, ['formData', 'irsNum'], row.get('irsNum'))
        _add_path_text(root, ['formData', 'isAffiliatedWithReceiptsMoreThan7Million'], row.get('isAffiliatedWithReceiptsMoreThan7Million'))
        _add_path_text(root, ['formData', 'isEngagedInOtherNonMAABusiness'], row.get('isEngagedInOtherNonMAABusiness'))
        _add_path_text(root, ['formData', 'isPrcApplicant'], row.get('isPrcApplicant'))
        _add_path_text(root, ['formData', 'maaEmployeesRegBD'], row.get('maaEmployeesRegBD'))
        _add_path_text(root, ['formData', 'maaRegIA'], row.get('maaRegIA'))
        _add_path_text(root, ['formData', 'mailingAddressDifferent'], row.get('mailingAddressDifferent'))
        _add_path_text(root, ['formData', 'miscellaneous'], row.get('miscellaneous'))
        _add_path_text(root, ['formData', 'monthOfFiscalYearEnd'], row.get('monthOfFiscalYearEnd'))
        _add_path_text(root, ['formData', 'numberOfAdditionalWebSites'], row.get('numberOfAdditionalWebSites'))
        _add_path_text(root, ['formData', 'numberOfEmployees'], row.get('numberOfEmployees'))
        _add_path_text(root, ['formData', 'numberOfSolicitedME'], row.get('numberOfSolicitedME'))
        _add_path_text(root, ['formData', 'numberOfSolicitedOP'], row.get('numberOfSolicitedOP'))
        _add_path_text(root, ['formData', 'numberOfSolicitingFirms'], row.get('numberOfSolicitingFirms'))
        _add_path_text(root, ['formData', 'otherNonMAABusinessPrimaryDescription'], row.get('otherNonMAABusinessPrimaryDescription'))
        _add_path_text(root, ['formData', 'previousDbaName'], row.get('previousDbaName'))
        _add_path_text(root, ['formData', 'previousLegalName'], row.get('previousLegalName'))
        _add_path_text(root, ['formData', 'primaryWebAddress'], row.get('primaryWebAddress'))
        _add_path_text(root, ['formData', 'receiveCompensationForMAAFromOtherClientsExplanation'], row.get('receiveCompensationForMAAFromOtherClientsExplanation'))
        _add_path_text(root, ['formData', 'totalFIAAssociatedPersons'], row.get('totalFIAAssociatedPersons'))
        _add_path_text(root, ['formData', 'totalNumberOfSolicitedMEAndOP'], row.get('totalNumberOfSolicitedMEAndOP'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'cco', 'email'], row.get('email'))
        _add_path_text(root, ['formData', 'cco', 'faxNumber'], row.get('faxNumber'))
        _add_path_text(root, ['formData', 'cco', 'phoneNumber'], row.get('phoneNumber'))
        _add_path_text(root, ['formData', 'contactPerson', 'email'], row.get('contactPersonEmail'))
        _add_path_text(root, ['formData', 'contactPerson', 'faxNumber'], row.get('contactPersonFaxNumber'))
        _add_path_text(root, ['formData', 'contactPerson', 'phoneNumber'], row.get('contactPersonPhoneNumber'))
        _add_path_text(root, ['formData', 'controls', 'additionalOffices'], row.get('additionalOffices'))
        _add_path_text(root, ['formData', 'controls', 'additionalRegs'], row.get('additionalRegs'))
        _add_path_text(root, ['formData', 'controls', 'hasAdditionalDBANames'], row.get('hasAdditionalDBANames'))
        _add_path_text(root, ['formData', 'controls', 'hasAdditionalWebsites'], row.get('hasAdditionalWebsites'))
        _add_path_text(root, ['formData', 'controls', 'hasBooksRecords'], row.get('hasBooksRecords'))
        _add_path_text(root, ['formData', 'controls', 'hasDBAName'], row.get('hasDBAName'))
        _add_path_text(root, ['formData', 'controls', 'hasMATReg'], row.get('hasMATReg'))
        _add_path_text(root, ['formData', 'controls', 'hasMailingAddress'], row.get('hasMailingAddress'))
        _add_path_text(root, ['formData', 'controls', 'hasNameChange'], row.get('hasNameChange'))
        _add_path_text(root, ['formData', 'controls', 'hasPreviousDBAName'], row.get('hasPreviousDBAName'))
        _add_path_text(root, ['formData', 'controls', 'hasScheduleB'], row.get('hasScheduleB'))
        _add_path_text(root, ['formData', 'controls', 'independentBusinessEmployee'], row.get('independentBusinessEmployee'))
        _add_path_text(root, ['formData', 'controls', 'isAffiliatedOtherBus'], row.get('isAffiliatedOtherBus'))
        _add_path_text(root, ['formData', 'controls', 'isCPForApplicantPolicy'], row.get('isCPForApplicantPolicy'))
        _add_path_text(root, ['formData', 'controls', 'isOtherNonMAABuisinesssPrimary'], row.get('isOtherNonMAABuisinesssPrimary'))
        _add_path_text(root, ['formData', 'controls', 'isPRCompanyUnder1215'], row.get('isPRCompanyUnder1215'))
        _add_path_text(root, ['formData', 'controls', 'isRegisteredFFRA'], row.get('isRegisteredFFRA'))
        _add_path_text(root, ['formData', 'controls', 'isSection12Or15ReportingCompany'], row.get('isSection12Or15ReportingCompany'))
        _add_path_text(root, ['formData', 'controls', 'isSolePropietor'], row.get('isSolePropietor'))
        _add_path_text(root, ['formData', 'controls', 'isSucceedingApplicant'], row.get('isSucceedingApplicant'))
        _add_path_text(root, ['formData', 'controls', 'receiveCompensationForMAAFromOtherClients'], row.get('receiveCompensationForMAAFromOtherClients'))
        _add_path_text(root, ['formData', 'engagedActivities', 'eaTypeOtherDescription'], row.get('eaTypeOtherDescription'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersonsTypes', 'fiaAPTypes'], row.get('fiaAPTypes'))
        _add_path_text(root, ['formData', 'formOfOrganization', 'formOrgOtherDescription'], row.get('formOrgOtherDescription'))
        _add_path_text(root, ['formData', 'maExecutionPage', 'crdNumber'], row.get('crdNumber'))
        _add_path_text(root, ['formData', 'meOrOPCompensationTypes', 'COMP_TYPE_OTHER_DESCRIPTION'], row.get('cOMPTYPEOTHERDESCRIPTION'))
        _add_path_text(root, ['formData', 'organizedJurisdiction', 'stateOrCountry'], row.get('stateOrCountry'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactBuySellFromClients'], row.get('mactBuySellFromClients'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactBuySellRecommendToClients'], row.get('mactBuySellRecommendToClients'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactCompensateForReferrals'], row.get('mactCompensateForReferrals'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactDiscAuthBuySell'], row.get('mactDiscAuthBuySell'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactDiscAuthBuySellAsMAA'], row.get('mactDiscAuthBuySellAsMAA'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactDiscAuthDetermineBrokerDealer'], row.get('mactDiscAuthDetermineBrokerDealer'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactDiscAuthDetermineBrokerDealerAreAP'], row.get('mactDiscAuthDetermineBrokerDealerAreAP'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactDiscAuthDetermineCommissionToBrokerDealer'], row.get('mactDiscAuthDetermineCommissionToBrokerDealer'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactEnterDerivativesWithClients'], row.get('mactEnterDerivativesWithClients'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactReceiveCompensationForReferrals'], row.get('mactReceiveCompensationForReferrals'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactRecommendBrokerDealerToClient'], row.get('mactRecommendBrokerDealerToClient'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactRecommendBrokerDealerToClientAreAP'], row.get('mactRecommendBrokerDealerToClientAreAP'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactRecommendOwnedInterestToClients'], row.get('mactRecommendOwnedInterestToClients'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactRecommendToClientsHavingOtherSalesInterest'], row.get('mactRecommendToClientsHavingOtherSalesInterest'))
        _add_path_text(root, ['formData', 'participationInterestMACT', 'mactRecommendToClientsServing'], row.get('mactRecommendToClientsServing'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'faxNumber'], row.get('principalOfficeAddressFaxNumber'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'phoneNumber'], row.get('principalOfficeAddressPhoneNumber'))
        _add_path_text(root, ['formData', 'solicitationCompensationTypes', 'COMP_TYPE_OTHER_DESCRIPTION'], row.get('solicitationCompensationTypesCOMPTYPEOTHERDESCRIPTION'))
        _add_path_text(root, ['formData', 'typesOfClients', 'typesOfClientsOther'], row.get('typesOfClientsOther'))
        _add_path_text(root, ['formData', 'typesOfSolicitedPersons', 'spOtherDescription'], row.get('spOtherDescription'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contactEmail'], row.get('contactEmail'))
        _add_path_text(root, ['formData', 'additionalWebAddresses', 'additionalWebAddress', 'webAddress'], row.get('webAddress'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'description'], row.get('description'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'locationName'], row.get('locationName'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'affiliateName'], row.get('affiliateName'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'hasApplicableRegistration'], row.get('hasApplicableRegistration'))
        _add_path_text(root, ['formData', 'businessConductedOtherNames', 'businessConductedOtherName', 'jurisdictions'], row.get('jurisdictions'))
        _add_path_text(root, ['formData', 'businessConductedOtherNames', 'businessConductedOtherName', 'name'], row.get('name'))
        _add_path_text(root, ['formData', 'cco', 'name', 'firstName'], row.get('firstName'))
        _add_path_text(root, ['formData', 'cco', 'name', 'lastName'], row.get('lastName'))
        _add_path_text(root, ['formData', 'cco', 'name', 'middleName'], row.get('middleName'))
        _add_path_text(root, ['formData', 'cco', 'titles', 'title'], row.get('title'))
        _add_path_text(root, ['formData', 'contactPerson', 'name', 'firstName'], row.get('nameFirstName'))
        _add_path_text(root, ['formData', 'contactPerson', 'name', 'lastName'], row.get('nameLastName'))
        _add_path_text(root, ['formData', 'contactPerson', 'name', 'middleName'], row.get('nameMiddleName'))
        _add_path_text(root, ['formData', 'contactPerson', 'titles', 'title'], row.get('titlesTitle'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilDisclosure', 'isDismissed'], row.get('isDismissed'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilDisclosure', 'isEnjoined'], row.get('isEnjoined'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilDisclosure', 'isFoundInViolationOfRegulation'], row.get('isFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'civilDisclosure', 'isNamedInCivilProceeding'], row.get('isNamedInCivilProceeding'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isChargedWithFelony'], row.get('isChargedWithFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isConvictedOfFelony'], row.get('isConvictedOfFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isOrgChargedWithFelony'], row.get('isOrgChargedWithFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'criminalDisclosure', 'isOrgConvictedOfFelony'], row.get('isOrgConvictedOfFelony'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isAuthorizedToActAttorney'], row.get('isAuthorizedToActAttorney'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isCauseOfDenial'], row.get('isCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isDeniedLicense'], row.get('isDeniedLicense'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isDiscipliend'], row.get('isDiscipliend'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isFoundInCauseOfDenial'], row.get('isFoundInCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isFoundInCauseOfSuspension'], row.get('isFoundInCauseOfSuspension'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isFoundInViolationOfRegulation'], row.get('regulatoryDisclosureIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isFoundInViolationOfRules'], row.get('isFoundInViolationOfRules'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isFoundMadeFalseStatement'], row.get('isFoundMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isImposedPenalty'], row.get('isImposedPenalty'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isMadeFalseStatement'], row.get('isMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isOrderAgainst'], row.get('isOrderAgainst'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isOrderAgainstActivity'], row.get('isOrderAgainstActivity'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isRegulatoryComplaint'], row.get('isRegulatoryComplaint'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isUnEthical'], row.get('isUnEthical'))
        _add_path_text(root, ['formData', 'disclosureAnswers', 'regulatoryDisclosure', 'isViolatedRegulation'], row.get('isViolatedRegulation'))
        _add_path_text(root, ['formData', 'engagedActivities', 'engagedActivityTypes', 'engagedActivityType'], row.get('engagedActivityType'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'legalName'], row.get('legalName'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'primaryBusinessName'], row.get('primaryBusinessName'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'ffraRegistrations', 'ffraRegistration', 'country'], row.get('country'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'ffraRegistrations', 'ffraRegistration', 'registrationNum'], row.get('registrationNum'))
        _add_path_text(root, ['formData', 'registrations', 'maTregistration', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['formData', 'section1215DPublicReportingCompanies', 'section1215DPublicReportingCompany', 'cik'], row.get('cik'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'nonScheduleABCControlPersonNatural', 'crd'], row.get('crd'))
        _add_path_text(root, ['formData', 'maExecutionPage', 'signature', 'date'], row.get('date'))
        _add_path_text(root, ['formData', 'maExecutionPage', 'signature', 'signature'], row.get('signature'))
        _add_path_text(root, ['formData', 'maExecutionPage', 'signature', 'signerName'], row.get('signerName'))
        _add_path_text(root, ['formData', 'maExecutionPage', 'signature', 'title'], row.get('signatureTitle'))
        _add_path_text(root, ['formData', 'mailingAddress', 'address', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'mailingAddress', 'address', 'stateOrCountry'], row.get('addressStateOrCountry'))
        _add_path_text(root, ['formData', 'mailingAddress', 'address', 'street1'], row.get('street1'))
        _add_path_text(root, ['formData', 'mailingAddress', 'address', 'street2'], row.get('street2'))
        _add_path_text(root, ['formData', 'mailingAddress', 'address', 'zipCode'], row.get('zipCode'))
        _add_path_text(root, ['formData', 'meOrOPCompensationTypes', 'compensationTypes', 'compensationTypes'], row.get('compensationTypes'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'description'], row.get('nonScheduleABCControllingPersonDescription'))
        _add_path_text(root, ['formData', 'otherActivities', 'accounting', 'licensedJurisdictions'], row.get('licensedJurisdictions'))
        _add_path_text(root, ['formData', 'otherActivities', 'bankingThrift', 'isActivelyEngaged'], row.get('isActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'bankingThrift', 'isPrimaryBusiness'], row.get('isPrimaryBusiness'))
        _add_path_text(root, ['formData', 'otherActivities', 'brokerDealers', 'isActivelyEngaged'], row.get('brokerDealersIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'brokerDealers', 'isPrimaryBusiness'], row.get('brokerDealersIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'otherActivities', 'commidityTA', 'isActivelyEngaged'], row.get('commidityTAIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'engineering', 'isActivelyEngaged'], row.get('engineeringIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'investmentAdvisor', 'isPrimaryBusiness'], row.get('investmentAdvisorIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'otherActivities', 'insurance', 'isActivelyEngaged'], row.get('insuranceIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'insurance', 'isPrimaryBusiness'], row.get('insuranceIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'otherActivities', 'investmentAdvisor', 'isActivelyEngaged'], row.get('investmentAdvisorIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'lawyers', 'licensedJurisdictions'], row.get('lawyersLicensedJurisdictions'))
        _add_path_text(root, ['formData', 'otherActivities', 'otherFinancialProductAdvisor', 'licensedJurisdictions'], row.get('otherFinancialProductAdvisorLicensedJurisdictions'))
        _add_path_text(root, ['formData', 'otherActivities', 'trustCompany', 'isActivelyEngaged'], row.get('realEstateIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'registeredBrokerDealerReps', 'isActivelyEngaged'], row.get('registeredBrokerDealerRepsIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'registeredBrokerDealerReps', 'isPrimaryBusiness'], row.get('registeredBrokerDealerRepsIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'section1215DPublicReportingCompanies', 'section1215DPublicReportingCompany', 'name'], row.get('section1215DPublicReportingCompanyName'))
        _add_path_text(root, ['formData', 'soleProprietor', 'name', 'firstName'], row.get('soleProprietorNameFirstName'))
        _add_path_text(root, ['formData', 'soleProprietor', 'name', 'lastName'], row.get('soleProprietorNameLastName'))
        _add_path_text(root, ['formData', 'soleProprietor', 'name', 'middleName'], row.get('soleProprietorNameMiddleName'))
        _add_path_text(root, ['formData', 'solicitationCompensationTypes', 'compensationTypes', 'compensationTypes'], row.get('compensationTypesCompensationTypes'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'name'], row.get('contactName'))
        _add_path_text(root, ['formData', 'typesOfClients', 'typesOfClients', 'clientTypes'], row.get('clientTypes'))
        _add_path_text(root, ['formData', 'typesOfSolicitedPersons', 'solicitationPersonTypes', 'solicitationPersonTypes'], row.get('solicitationPersonTypes'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'phoneNumber'], row.get('contactPhoneNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCcc'], row.get('filerCcc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerId'], row.get('filerId'))
        _add_path_text(root, ['headerData', 'filerInfo', 'notifications', 'internetNotificationAddress'], row.get('internetNotificationAddress'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'addDeleteAmend', 'add'], row.get('add'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'addDeleteAmend', 'amend'], row.get('amend'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'addDeleteAmend', 'delete'], row.get('delete'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'addDeleteAmend', 'newAdd'], row.get('newAdd'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'faxNumber'], row.get('officeInfoFaxNumber'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'phoneNumber'], row.get('officeInfoPhoneNumber'))
        _add_path_text(root, ['formData', 'additionalRegistrations', 'additionalRegistration', 'nameAndRegistration', 'name'], row.get('nameAndRegistrationName'))
        _add_path_text(root, ['formData', 'additionalRegistrations', 'additionalRegistration', 'nameAndRegistration', 'registrationId'], row.get('registrationId'))
        _add_path_text(root, ['formData', 'additionalWebAddresses', 'additionalWebAddress', 'addDeleteAmend', 'add'], row.get('addDeleteAmendAdd'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'faxNumber'], row.get('contactFaxNumber'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'phoneNumber'], row.get('booksAndRecordsLocationContactPhoneNumber'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'type', 'add'], row.get('typeAdd'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'type', 'amend'], row.get('typeAmend'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'type', 'delete'], row.get('typeDelete'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'type', 'newAdd'], row.get('typeNewAdd'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'applicableRegistration', 'issuingAgencyName'], row.get('issuingAgencyName'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'applicableRegistration', 'registrationNumber'], row.get('registrationNumber'))
        _add_path_text(root, ['formData', 'businessConductedOtherNames', 'businessConductedOtherName', 'addDeleteAmend', 'add'], row.get('businessConductedOtherNameAddDeleteAmendAdd'))
        _add_path_text(root, ['formData', 'cco', 'address', 'address', 'city'], row.get('addressCity'))
        _add_path_text(root, ['formData', 'cco', 'address', 'address', 'stateOrCountry'], row.get('addressAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'cco', 'address', 'address', 'street1'], row.get('addressStreet1'))
        _add_path_text(root, ['formData', 'cco', 'address', 'address', 'street2'], row.get('addressStreet2'))
        _add_path_text(root, ['formData', 'cco', 'address', 'address', 'zipCode'], row.get('addressZipCode'))
        _add_path_text(root, ['formData', 'contactPerson', 'address', 'address', 'city'], row.get('addressAddressCity'))
        _add_path_text(root, ['formData', 'contactPerson', 'address', 'address', 'stateOrCountry'], row.get('contactPersonAddressAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'contactPerson', 'address', 'address', 'street1'], row.get('addressAddressStreet1'))
        _add_path_text(root, ['formData', 'contactPerson', 'address', 'address', 'street2'], row.get('addressAddressStreet2'))
        _add_path_text(root, ['formData', 'contactPerson', 'address', 'address', 'zipCode'], row.get('addressAddressZipCode'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'apTypes', 'fiaAPTypes'], row.get('apTypesFiaAPTypes'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'isControlOrControlled'], row.get('isControlOrControlled'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'isRegisteredWithFFRA'], row.get('isRegisteredWithFFRA'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'isUnderCommonControl'], row.get('isUnderCommonControl'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'type', 'add'], row.get('fiaAssociatedPersonTypeAdd'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'type', 'amend'], row.get('fiaAssociatedPersonTypeAmend'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'type', 'newAdd'], row.get('fiaAssociatedPersonTypeNewAdd'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'faxNumber'], row.get('nonScheduleABCControllingPersonContactFaxNumber'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'phoneNumber'], row.get('nonScheduleABCControllingPersonContactPhoneNumber'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'type', 'add'], row.get('nonScheduleABCControllingPersonTypeAdd'))
        _add_path_text(root, ['formData', 'otherActivities', 'accounting', 'activelyEngagedPrimaryBusiness', 'isActivelyEngaged'], row.get('activelyEngagedPrimaryBusinessIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'accounting', 'activelyEngagedPrimaryBusiness', 'isPrimaryBusiness'], row.get('activelyEngagedPrimaryBusinessIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'otherActivities', 'otherFinancialProductAdvisor', 'activelyEngagedPrimaryBusiness', 'isActivelyEngaged'], row.get('otherFinancialProductAdvisorActivelyEngagedPrimaryBusinessIsActivelyEngaged'))
        _add_path_text(root, ['formData', 'otherActivities', 'otherFinancialProductAdvisor', 'activelyEngagedPrimaryBusiness', 'isPrimaryBusiness'], row.get('otherFinancialProductAdvisorActivelyEngagedPrimaryBusinessIsPrimaryBusiness'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'addressInfo', 'address', 'city'], row.get('addressInfoAddressCity'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'addressInfo', 'address', 'stateOrCountry'], row.get('addressInfoAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'addressInfo', 'address', 'street1'], row.get('addressInfoAddressStreet1'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'addressInfo', 'address', 'street2'], row.get('addressInfoAddressStreet2'))
        _add_path_text(root, ['formData', 'principalOfficeAddress', 'addressInfo', 'address', 'zipCode'], row.get('addressInfoAddressZipCode'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'maRegistration', 'fileNumber'], row.get('maRegistrationFileNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'controPersonPR'], row.get('controPersonPR'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'empIDNumber'], row.get('empIDNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'irsNum'], row.get('businessIrsNum'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'name'], row.get('businessName'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'owningEntity'], row.get('owningEntity'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'owningEntity'], row.get('personOwningEntity'))
        _add_path_text(root, ['formData', 'section1215DPublicReportingCompanies', 'section1215DPublicReportingCompany', 'reportingSchedules', 'reportingSchedule'], row.get('reportingSchedule'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'applicableRegistration', 'jurisdiction', 'ForeignCountry'], row.get('foreignCountry'))
        _add_path_text(root, ['formData', 'businessAffiliates', 'businessAffiliate', 'applicableRegistration', 'jurisdiction', 'US_State'], row.get('uSState'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'nonScheduleABCControlPersonNatural', 'dateInfo', 'effectiveDate'], row.get('effectiveDate'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'nonScheduleABCControlPersonNatural', 'name', 'firstName'], row.get('nonScheduleABCControlPersonNaturalNameFirstName'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'nonScheduleABCControlPersonNatural', 'name', 'lastName'], row.get('nonScheduleABCControlPersonNaturalNameLastName'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'nonScheduleABCControlPersonNatural', 'name', 'middleName'], row.get('nonScheduleABCControlPersonNaturalNameMiddleName'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'anotherRegistration', 'description'], row.get('anotherRegistrationDescription'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'anotherRegistration', 'registrationId'], row.get('anotherRegistrationRegistrationId'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'bdRegistration', 'crdNumber'], row.get('bdRegistrationCrdNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'bdRegistration', 'fileNumber'], row.get('bdRegistrationFileNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'otherRegistration', 'cik'], row.get('otherRegistrationCik'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'otherRegistration', 'description'], row.get('otherRegistrationDescription'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'otherRegistration', 'fileNumber'], row.get('otherRegistrationFileNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'baseInformation', 'crdNumber'], row.get('baseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'baseInformation', 'statusAcquired'], row.get('statusAcquired'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'baseInformation', 'isControPerson'], row.get('isControPerson'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'baseInformation', 'ownershipCode'], row.get('ownershipCode'))
        _add_path_text(root, ['formData', 'scheduleA', 'businesses', 'business', 'baseInformation', 'titleStatus'], row.get('titleStatus'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'baseInformation', 'crdNumber'], row.get('personBaseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'baseInformation', 'isControPerson'], row.get('baseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'baseInformation', 'ownershipCode'], row.get('baseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'baseInformation', 'statusAcquired'], row.get('baseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'baseInformation', 'titleStatus'], row.get('baseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'name', 'firstName'], row.get('personNameFirstName'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'name', 'lastName'], row.get('personNameLastName'))
        _add_path_text(root, ['formData', 'scheduleA', 'persons', 'person', 'name', 'middleName'], row.get('personNameMiddleName'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'controPersonPR'], row.get('baseInfoControPersonPR'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'empIDNumber'], row.get('baseInfoEmpIDNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'irsNum'], row.get('baseInfoIrsNum'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'name'], row.get('baseInfoName'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'controPersonPR'], row.get('baseInformationControPersonPR'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'empIDNumber'], row.get('baseInformationEmpIDNumber'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'irsNum'], row.get('baseInformationIrsNum'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'name'], row.get('baseInformationName'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'type', 'add'], row.get('businessTypeAdd'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'type', 'amend'], row.get('businessTypeAmend'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'type', 'delete'], row.get('personTypeDelete'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'type', 'newAdd'], row.get('personTypeNewAdd'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'type', 'add'], row.get('personTypeAdd'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'type', 'amend'], row.get('personTypeAmend'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'owningEntity'], row.get('baseInformationOwningEntity'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'type', 'add'], row.get('indirectBusinessesBusinessTypeAdd'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'type', 'amend'], row.get('indirectBusinessesBusinessTypeAmend'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'owningEntity'], row.get('personBaseInformationOwningEntity'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'type', 'add'], row.get('indirectPersonsPersonTypeAdd'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'type', 'amend'], row.get('indirectPersonsPersonTypeAmend'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'addressInfo', 'address', 'city'], row.get('officeInfoAddressInfoAddressCity'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'addressInfo', 'address', 'stateOrCountry'], row.get('officeInfoAddressInfoAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'addressInfo', 'address', 'street1'], row.get('officeInfoAddressInfoAddressStreet1'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'addressInfo', 'address', 'street2'], row.get('officeInfoAddressInfoAddressStreet2'))
        _add_path_text(root, ['formData', 'additionalOffices', 'additionalOffice', 'officeInfo', 'addressInfo', 'address', 'zipCode'], row.get('officeInfoAddressInfoAddressZipCode'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'addressInfo', 'address', 'city'], row.get('contactAddressInfoAddressCity'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'addressInfo', 'address', 'stateOrCountry'], row.get('contactAddressInfoAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'addressInfo', 'address', 'street1'], row.get('contactAddressInfoAddressStreet1'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'addressInfo', 'address', 'street2'], row.get('contactAddressInfoAddressStreet2'))
        _add_path_text(root, ['formData', 'booksAndRecordsLocations', 'booksAndRecordsLocation', 'contact', 'addressInfo', 'address', 'zipCode'], row.get('contactAddressInfoAddressZipCode'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'headerData', 'baseHeader', 'apDrpFiledCount'], row.get('apDrpFiledCount'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'headerData', 'respondingTo', 'responseQuestion'], row.get('responseQuestion'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'headerData', 'baseHeader', 'apDrpFiledCount'], row.get('baseHeaderApDrpFiledCount'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'headerData', 'respondingTo', 'responseQuestion'], row.get('respondingToResponseQuestion'))
        _add_path_text(root, ['formData', 'fiaAssociatedPersons', 'fiaAssociatedPerson', 'otherMunicipalAdviser', 'ffraRegistrations', 'ffraRegistration', 'name'], row.get('ffraRegistrationName'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'addressInfo', 'address', 'city'], row.get('nonScheduleABCControllingPersonContactAddressInfoAddressCity'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'addressInfo', 'address', 'stateOrCountry'], row.get('nonScheduleABCControllingPersonContactAddressInfoAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'addressInfo', 'address', 'street1'], row.get('nonScheduleABCControllingPersonContactAddressInfoAddressStreet1'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'addressInfo', 'address', 'street2'], row.get('nonScheduleABCControllingPersonContactAddressInfoAddressStreet2'))
        _add_path_text(root, ['formData', 'nonScheduleABCControllingPersons', 'nonScheduleABCControllingPerson', 'contact', 'addressInfo', 'address', 'zipCode'], row.get('nonScheduleABCControllingPersonContactAddressInfoAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'baseInformation', 'crdNumber'], row.get('baseInfoBaseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'baseInformation', 'statusAcquired'], row.get('baseInfoBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'baseInformation', 'isControPerson'], row.get('baseInfoBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'baseInformation', 'ownershipCode'], row.get('baseInfoBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'businesses', 'business', 'baseInfo', 'baseInformation', 'titleStatus'], row.get('baseInfoBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'baseInformation', 'isControPerson'], row.get('personBaseInfoBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'baseInformation', 'ownershipCode'], row.get('personBaseInfoBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'baseInformation', 'statusAcquired'], row.get('personBaseInfoBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'baseInformation', 'titleStatus'], row.get('personBaseInfoBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'name', 'firstName'], row.get('baseInfoNameFirstName'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'name', 'lastName'], row.get('baseInfoNameLastName'))
        _add_path_text(root, ['formData', 'scheduleB', 'persons', 'person', 'baseInfo', 'name', 'middleName'], row.get('baseInfoNameMiddleName'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'baseInformation', 'crdNumber'], row.get('baseInformationBaseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'baseInformation', 'statusAcquired'], row.get('baseInformationBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'baseInformation', 'isControPerson'], row.get('baseInformationBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'baseInformation', 'ownershipCode'], row.get('baseInformationBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleC', 'directBusinesses', 'business', 'baseInformation', 'baseInformation', 'titleStatus'], row.get('baseInformationBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'baseInformation', 'crdNumber'], row.get('personBaseInformationBaseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'baseInformation', 'isControPerson'], row.get('personBaseInformationBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'baseInformation', 'ownershipCode'], row.get('personBaseInformationBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'baseInformation', 'statusAcquired'], row.get('personBaseInformationBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'baseInformation', 'titleStatus'], row.get('personBaseInformationBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'name', 'firstName'], row.get('baseInformationNameFirstName'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'name', 'lastName'], row.get('baseInformationNameLastName'))
        _add_path_text(root, ['formData', 'scheduleC', 'directPersons', 'person', 'baseInformation', 'name', 'middleName'], row.get('baseInformationNameMiddleName'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'controPersonPR'], row.get('baseInformationBaseInfoControPersonPR'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'empIDNumber'], row.get('baseInformationBaseInfoEmpIDNumber'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'irsNum'], row.get('baseInformationBaseInfoIrsNum'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'name'], row.get('baseInformationBaseInfoName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'apType', 'firmInfo'], row.get('firmInfo'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'registrationInfo', 'crdNumber'], row.get('registrationInfoCrdNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'apInfo', 'associatedPerson', 'registrationInfo', 'isSECRegistered'], row.get('isSECRegistered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'registrationInfo', 'secRegistrationNumber'], row.get('secRegistrationNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'allegationsDescription'], row.get('allegationsDescription'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'principalProductTypes', 'product'], row.get('product'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'registrationInfo', 'isSECRegistered'], row.get('registrationInfoIsSECRegistered'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'baseInformation', 'crdNumber'], row.get('baseInformationBaseInfoBaseInformationCrdNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'iaRegistration', 'nonExempt', 'secRegistration', 'fileNumber'], row.get('secRegistrationFileNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'iaRegistration', 'nonExempt', 'secRegistration', 'crdNumber'], row.get('secRegistrationCrdNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'iaRegistration', 'nonExempt', 'stateRegistration', 'crdNumber'], row.get('stateRegistrationCrdNumber'))
        _add_path_text(root, ['formData', 'registrations', 'baseRegistrations', 'baseRegistrations', 'iaRegistration', 'nonExempt', 'stateRegistration', 'state'], row.get('state'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'baseInformation', 'statusAcquired'], row.get('baseInformationBaseInfoBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'baseInformation', 'isControPerson'], row.get('baseInformationBaseInfoBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'baseInformation', 'ownershipCode'], row.get('baseInformationBaseInfoBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectBusinesses', 'business', 'baseInformation', 'baseInfo', 'baseInformation', 'titleStatus'], row.get('baseInformationBaseInfoBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'baseInformation', 'isControPerson'], row.get('personBaseInformationBaseInfoBaseInformationIsControPerson'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'baseInformation', 'ownershipCode'], row.get('personBaseInformationBaseInfoBaseInformationOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'baseInformation', 'statusAcquired'], row.get('personBaseInformationBaseInfoBaseInformationStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'baseInformation', 'titleStatus'], row.get('personBaseInformationBaseInfoBaseInformationTitleStatus'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'name', 'firstName'], row.get('baseInformationBaseInfoNameFirstName'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'name', 'lastName'], row.get('baseInformationBaseInfoNameLastName'))
        _add_path_text(root, ['formData', 'scheduleC', 'indirectPersons', 'person', 'baseInformation', 'baseInfo', 'name', 'middleName'], row.get('baseInformationBaseInfoNameMiddleName'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'firstName'], row.get('naturalPersonInfoFirstName'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'lastName'], row.get('naturalPersonInfoLastName'))
        _add_path_text(root, ['formData', 'drpInfo', 'civilJudicialDisclosure', 'civilJudicialDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'middleName'], row.get('naturalPersonInfoMiddleName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'suffix'], row.get('suffix'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'allegationsDescription'], row.get('initiatedDRPAllegationsDescription'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'principalProductTypes', 'product'], row.get('principalProductTypesProduct'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'name'], row.get('advBDU4FilingName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'summary'], row.get('summary'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'dateInitiated', 'date'], row.get('dateInitiatedDate'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'sanctionsSought', 'sanction'], row.get('sanction'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'crdNumber'], row.get('advBDU4FilingCrdNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'disclosureNumber'], row.get('disclosureNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'firstName'], row.get('apTypeNaturalPersonInfoFirstName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'lastName'], row.get('apTypeNaturalPersonInfoLastName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'apType', 'naturalPersonInfo', 'middleName'], row.get('apTypeNaturalPersonInfoMiddleName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'name'], row.get('filedDisclosureAdvBDU4FilingName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'summary'], row.get('baseInformationSummary'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'dateInitiated', 'date'], row.get('initiatedDRPDateInitiatedDate'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'sanctionsSought', 'sanction'], row.get('sanctionsSoughtSanction'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'crdNumber'], row.get('filedDisclosureAdvBDU4FilingCrdNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'filedDisclosure', 'advBDU4Filing', 'disclosureNumber'], row.get('advBDU4FilingDisclosureNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'docketOrCaseNo'], row.get('docketOrCaseNo'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'name'], row.get('chargesBroughtInName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'date', 'date'], row.get('dateDate'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'explanation'], row.get('explanation'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionsOrdered'], row.get('sanctionsOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'totalAmountOrdered'], row.get('totalAmountOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'judgement'], row.get('judgement'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'isFinalOrder'], row.get('isFinalOrder'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'initiatedBy', 'name'], row.get('initiatedByName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'docketOrCaseNo'], row.get('chargesBroughtInDocketOrCaseNo'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'name'], row.get('baseInformationChargesBroughtInName'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'date', 'date'], row.get('resolutionInformationDateDate'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'explanation'], row.get('typesExplanation'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionsOrdered'], row.get('detailsSanctionsOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'totalAmountOrdered'], row.get('detailsTotalAmountOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'judgement'], row.get('typesJudgement'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'types', 'isFinalOrder'], row.get('typesIsFinalOrder'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'city'], row.get('chargesBroughtInAddressCity'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'stateOrCountry'], row.get('chargesBroughtInAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'street1'], row.get('chargesBroughtInAddressStreet1'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'zipCode'], row.get('chargesBroughtInAddressZipCode'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctions', 'sanction'], row.get('sanctionsSanction'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'city'], row.get('baseInformationChargesBroughtInAddressCity'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'stateOrCountry'], row.get('baseInformationChargesBroughtInAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'street1'], row.get('baseInformationChargesBroughtInAddressStreet1'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'baseInformation', 'chargesBroughtIn', 'address', 'zipCode'], row.get('baseInformationChargesBroughtInAddressZipCode'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctions', 'sanction'], row.get('detailsSanctionsSanction'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionDetails', 'monetarySanctions', 'amountOrdered'], row.get('amountOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionDetails', 'monetarySanctions', 'finalAmount'], row.get('finalAmount'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionDetails', 'monetarySanctions', 'amountOrdered'], row.get('monetarySanctionsAmountOrdered'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'apInfo', 'associatedPerson', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionDetails', 'monetarySanctions', 'finalAmount'], row.get('monetarySanctionsFinalAmount'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'applicantInfo', 'drpInfo', 'detailedDisclosure', 'initiatedDRP', 'resolutionInformation', 'details', 'sanctionDetails', 'monetarySanctions', 'paymentState', 'satisfied'], row.get('satisfied'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')





