import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_mai(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/maifiler')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common_ma')
    root.set('xmlns:com1', 'http://www.sec.gov/edgar/common')
    for row in normalized_rows:
        _add_path_text(root, ['formData', 'applicantCrdNum'], row.get('applicantCrdNum'))
        _add_path_text(root, ['formData', 'hasMoreThanOneAdvisoryFirms'], row.get('hasMoreThanOneAdvisoryFirms'))
        _add_path_text(root, ['formData', 'isAmendment'], row.get('isAmendment'))
        _add_path_text(root, ['formData', 'isEngagedInOtherBusiness'], row.get('isEngagedInOtherBusiness'))
        _add_path_text(root, ['formData', 'isIndividual'], row.get('isIndividual'))
        _add_path_text(root, ['formData', 'noOfAdvisoryFirms'], row.get('noOfAdvisoryFirms'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'applicantName', 'firstName'], row.get('firstName'))
        _add_path_text(root, ['formData', 'applicantName', 'lastName'], row.get('lastName'))
        _add_path_text(root, ['formData', 'applicantName', 'middleName'], row.get('middleName'))
        _add_path_text(root, ['formData', 'applicantName', 'suffix'], row.get('suffix'))
        _add_path_text(root, ['formData', 'selfCertification', 'crdNumber'], row.get('crdNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contactEmail'], row.get('contactEmail'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'civilDisclosure', 'isDismissed'], row.get('isDismissed'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'civilDisclosure', 'isEnjoined'], row.get('isEnjoined'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'civilDisclosure', 'isFoundInViolationOfRegulation'], row.get('isFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'civilDisclosure', 'isNamedInCivilProceeding'], row.get('isNamedInCivilProceeding'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'complaintDisclosure', 'isComplaintPending'], row.get('isComplaintPending'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'complaintDisclosure', 'isComplaintSettled'], row.get('isComplaintSettled'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'complaintDisclosure', 'isFraudCasePending'], row.get('isFraudCasePending'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'complaintDisclosure', 'isFraudCaseResultedAward'], row.get('isFraudCaseResultedAward'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'complaintDisclosure', 'isFraudCaseSettled'], row.get('isFraudCaseSettled'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'isChargedWithMisdemeanor'], row.get('isChargedWithMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'isConvictedOfMisdemeanor'], row.get('isConvictedOfMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'isOrgChargedWithMisdemeanor'], row.get('isOrgChargedWithMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'isOrgConvictedOfMisdemeanor'], row.get('isOrgConvictedOfMisdemeanor'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'financialDisclosure', 'isBankruptcyPetition'], row.get('isBankruptcyPetition'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'financialDisclosure', 'isBondRevoked'], row.get('isBondRevoked'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'financialDisclosure', 'isCompromised'], row.get('isCompromised'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'financialDisclosure', 'isTrusteeApointed'], row.get('isTrusteeApointed'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'investigationDisclosure', 'isInvestigated'], row.get('isInvestigated'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'judgmentLienDisclosure', 'isLienAgainst'], row.get('isLienAgainst'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isAssociationBared'], row.get('isAssociationBared'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isFailedResonably'], row.get('isFailedResonably'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isFailedToSupervise'], row.get('isFailedToSupervise'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isFinalOrder'], row.get('isFinalOrder'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isFoundWillFullyAided'], row.get('isFoundWillFullyAided'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isViolatedSecurityAct'], row.get('isViolatedSecurityAct'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isWillFullyAided'], row.get('isWillFullyAided'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'isWillFullyViolatedSecurityAct'], row.get('isWillFullyViolatedSecurityAct'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'terminationDisclosure', 'isFailedToSupervise'], row.get('terminationDisclosureIsFailedToSupervise'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'terminationDisclosure', 'isInvolvedInFraud'], row.get('isInvolvedInFraud'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'terminationDisclosure', 'isViloatedIndustryStandard'], row.get('isViloatedIndustryStandard'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'isRelatedToInvestment'], row.get('isRelatedToInvestment'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'isRelatedToMunicipalAdvisor'], row.get('isRelatedToMunicipalAdvisor'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'name'], row.get('name'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'positionDescription'], row.get('positionDescription'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'startDate'], row.get('startDate'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'approximateHoursOrMonths'], row.get('approximateHoursOrMonths'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'dutiesDescription'], row.get('dutiesDescription'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'isRelatedToInvestment'], row.get('otherBusinessIsRelatedToInvestment'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'isRelatedToMunicipalAdvisor'], row.get('otherBusinessIsRelatedToMunicipalAdvisor'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'name'], row.get('otherBusinessName'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'natureOfBusiness'], row.get('natureOfBusiness'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'positionDescription'], row.get('otherBusinessPositionDescription'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'startDate'], row.get('otherBusinessStartDate'))
        _add_path_text(root, ['formData', 'otherNames', 'otherName', 'firstName'], row.get('otherNameFirstName'))
        _add_path_text(root, ['formData', 'otherNames', 'otherName', 'lastName'], row.get('otherNameLastName'))
        _add_path_text(root, ['formData', 'otherNames', 'otherName', 'middleName'], row.get('otherNameMiddleName'))
        _add_path_text(root, ['formData', 'otherNames', 'otherName', 'suffix'], row.get('otherNameSuffix'))
        _add_path_text(root, ['formData', 'selfCertification', 'signature', 'dateSigned'], row.get('dateSigned'))
        _add_path_text(root, ['formData', 'selfCertification', 'signature', 'signature'], row.get('signature'))
        _add_path_text(root, ['formData', 'signatureInfo', 'signature', 'dateSigned'], row.get('signatureDateSigned'))
        _add_path_text(root, ['formData', 'signatureInfo', 'signature', 'signature'], row.get('signatureSignature'))
        _add_path_text(root, ['formData', 'signatureInfo', 'signature', 'title'], row.get('title'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'name'], row.get('contactName'))
        _add_path_text(root, ['headerData', 'filerInfo', 'contact', 'phoneNumber'], row.get('phoneNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCcc'], row.get('filerCcc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerId'], row.get('filerId'))
        _add_path_text(root, ['headerData', 'filerInfo', 'notifications', 'internetNotificationAddress'], row.get('internetNotificationAddress'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'criminalDisclosureCommonQuestion', 'isChargedWithFelony'], row.get('isChargedWithFelony'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'criminalDisclosureCommonQuestion', 'isConvictedOfFelony'], row.get('isConvictedOfFelony'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'criminalDisclosureCommonQuestion', 'isOrgChargedWithFelony'], row.get('isOrgChargedWithFelony'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'criminalDisclosure', 'criminalDisclosureCommonQuestion', 'isOrgConvictedOfFelony'], row.get('isOrgConvictedOfFelony'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isAuthorizedToActAttorney'], row.get('isAuthorizedToActAttorney'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isCauseOfDenial'], row.get('isCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isDeniedLicense'], row.get('isDeniedLicense'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isDiscipliend'], row.get('isDiscipliend'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isFoundInCauseOfDenial'], row.get('isFoundInCauseOfDenial'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isFoundInCauseOfSuspension'], row.get('isFoundInCauseOfSuspension'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isFoundInViolationOfRegulation'], row.get('regulatoryDisclosureCommonQuestionIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isFoundInViolationOfRules'], row.get('isFoundInViolationOfRules'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isFoundMadeFalseStatement'], row.get('isFoundMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isImposedPenalty'], row.get('isImposedPenalty'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isMadeFalseStatement'], row.get('isMadeFalseStatement'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isOrderAgainst'], row.get('isOrderAgainst'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isOrderAgainstActivity'], row.get('isOrderAgainstActivity'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isRegulatoryComplaint'], row.get('isRegulatoryComplaint'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isUnEthical'], row.get('isUnEthical'))
        _add_path_text(root, ['formData', 'disclosureQuestions', 'regulatoryDisclosure', 'regulatoryDisclosureCommonQuestion', 'isViolatedRegulation'], row.get('isViolatedRegulation'))
        _add_path_text(root, ['formData', 'drpInfo', 'criminalDisclosure', 'criminalDrp', 'criminalQuestions'], row.get('criminalQuestions'))
        _add_path_text(root, ['formData', 'drpInfo', 'customerComplaintDisclosure', 'customerComplaintDrp', 'customerComplaintQuestions'], row.get('customerComplaintQuestions'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'regulatoryQuestions'], row.get('regulatoryQuestions'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'addressInfo', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'addressInfo', 'zipCode'], row.get('zipCode'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'endDate'], row.get('endDate'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'isRelatedToInvestment'], row.get('priorEmployerIsRelatedToInvestment'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'isRelatedToMunicipalAdvisor'], row.get('priorEmployerIsRelatedToMunicipalAdvisor'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'name'], row.get('priorEmployerName'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'positionDescription'], row.get('priorEmployerPositionDescription'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'startDate'], row.get('priorEmployerStartDate'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'municipalFirm', 'isIndependentRelatioship'], row.get('isIndependentRelatioship'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'municipalFirm', 'municipalDbaName'], row.get('municipalDbaName'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'municipalFirm', 'municipalFirmName'], row.get('municipalFirmName'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'municipalFirm', 'recentEmploymentCommencedDate'], row.get('recentEmploymentCommencedDate'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'addressInfo', 'city'], row.get('addressInfoCity'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'addressInfo', 'stateOrCountry'], row.get('stateOrCountry'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'addressInfo', 'street1'], row.get('street1'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'addressInfo', 'street2'], row.get('street2'))
        _add_path_text(root, ['formData', 'otherBusinesses', 'otherBusiness', 'addressInfo', 'zipCode'], row.get('addressInfoZipCode'))
        _add_path_text(root, ['formData', 'selfCertification', 'signature', 'nameOfApplicant', 'firstName'], row.get('nameOfApplicantFirstName'))
        _add_path_text(root, ['formData', 'selfCertification', 'signature', 'nameOfApplicant', 'lastName'], row.get('nameOfApplicantLastName'))
        _add_path_text(root, ['formData', 'selfCertification', 'signature', 'nameOfApplicant', 'middleName'], row.get('nameOfApplicantMiddleName'))
        _add_path_text(root, ['formData', 'employmentHistory', 'currentEmployer', 'addressInfo', 'stateOrCountry', 'stateOrCountry'], row.get('stateOrCountryStateOrCountry'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'addressInfo', 'city'], row.get('priorEmployerAddressInfoCity'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'addressInfo', 'zipCode'], row.get('priorEmployerAddressInfoZipCode'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'locationInfo'], row.get('locationInfo'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'startDate'], row.get('advisorOfficeStartDate'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'maRegistration', 'notSecRegistered', 'explanation'], row.get('explanation'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'maRegistration', 'secRegistration', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'municipalFirm', 'municipalFiler', 'filerId'], row.get('municipalFilerFilerId'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'maRegistration', 'notSecRegistered', 'hasFiled', 'filingDate'], row.get('filingDate'))
        _add_path_text(root, ['formData', 'employmentHistory', 'priorEmployers', 'priorEmployer', 'addressInfo', 'stateOrCountry', 'stateOrCountry'], row.get('addressInfoStateOrCountryStateOrCountry'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'maRegistration', 'notSecRegistered', 'hasFiled', 'cik'], row.get('cik'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'baseHeader', 'filingInfo', 'formADVBDFiling', 'crdNumber'], row.get('formADVBDFilingCrdNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'baseHeader', 'filingInfo', 'formADVBDFiling', 'disclosureNumber'], row.get('disclosureNumber'))
        _add_path_text(root, ['formData', 'drpInfo', 'regulatoryDisclosure', 'regulatoryDrp', 'baseHeader', 'filingInfo', 'formADVBDFiling', 'filingName'], row.get('filingName'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'addressInfo', 'address', 'city'], row.get('addressCity'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'addressInfo', 'address', 'stateOrCountry'], row.get('addressStateOrCountry'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'addressInfo', 'address', 'street1'], row.get('addressStreet1'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'addressInfo', 'address', 'street2'], row.get('addressStreet2'))
        _add_path_text(root, ['formData', 'municipalAdvisorOffices', 'municipalAdvisorOffice', 'advisorOffices', 'advisorOffice', 'addressInfo', 'address', 'zipCode'], row.get('addressZipCode'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




