import io
import xml.etree.ElementTree as ET
from ..utils import _add_created_with_comment, _add_path_text, _ensure_path



def _is_present(value) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, tuple, set)):
        return any(_is_present(item) for item in value)
    return True


def _to_text(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _normalize_values(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (list, tuple, set)):
        out = []
        for item in value:
            out.extend(_normalize_values(item))
        return out

    text = _to_text(value)
    if text == "":
        return [""]

    stripped = text.strip()
    if not stripped:
        return []

    if any(token in text for token in ("|", ";", "\n", "\r")):
        normalized = (
            text.replace("\r\n", "\n")
            .replace("\r", "\n")
            .replace(";", "|")
            .replace("\n", "|")
        )
        return [part.strip() for part in normalized.split("|") if part.strip()]

    return [text]


def _first_across_rows(rows: list[dict], keys: list[str]):
    for row in rows:
        for key in keys:
            value = row.get(key)
            if _is_present(value):
                return value
    return None





def _add_path_attr(root: ET.Element, tags: list[str], attr_name: str, value) -> None:
    if not _is_present(value):
        return
    target = _ensure_path(root, tags)
    if attr_name not in target.attrib:
        target.set(attr_name, _to_text(value))

def _collect_records(rows: list[dict], key_names: list[str]) -> list[dict]:
    records = []
    for row in rows:
        value_lists = {k: _normalize_values(row.get(k)) for k in key_names}
        max_items = max((len(v) for v in value_lists.values()), default=0)
        if max_items == 0:
            continue
        for i in range(max_items):
            record = {}
            for key, values in value_lists.items():
                if not values:
                    record[key] = None
                elif len(values) == 1:
                    record[key] = values[0]
                elif i < len(values):
                    record[key] = values[i]
                else:
                    record[key] = None
            if any(_is_present(v) for v in record.values()):
                records.append(record)
    return records

def construct_ncen(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/ncen')
    _add_path_text(root, ['schemaVersion'], _first_across_rows(normalized_rows, ['schemaVersion']))
    _add_path_text(root, ['headerData', 'submissionType'], _first_across_rows(normalized_rows, ['submissionType']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isChangeAccPrinciples'], _first_across_rows(normalized_rows, ['isChangeAccPrinciples']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isCodeOfEthics'], _first_across_rows(normalized_rows, ['isCodeOfEthics']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isIPAReportInternalControl'], _first_across_rows(normalized_rows, ['isIPAReportInternalControl']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isInfoItem405'], _first_across_rows(normalized_rows, ['isInfoItem405']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isInfoRequiredEO'], _first_across_rows(normalized_rows, ['isInfoRequiredEO']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isInstDefiningRights'], _first_across_rows(normalized_rows, ['isInstDefiningRights']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isLegalProceedings'], _first_across_rows(normalized_rows, ['isLegalProceedings']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isMaterialAmendments'], _first_across_rows(normalized_rows, ['isMaterialAmendments']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isNewOrAmendedInvAdvContracts'], _first_across_rows(normalized_rows, ['isNewOrAmendedInvAdvContracts']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isOtherInfoRequired'], _first_across_rows(normalized_rows, ['isOtherInfoRequired']))
    _add_path_text(root, ['formData', 'attachmentsTab', 'isProvisionFinancialSupport'], _first_across_rows(normalized_rows, ['isProvisionFinancialSupport']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isDefaultLongTermDebt'], _first_across_rows(normalized_rows, ['isDefaultLongTermDebt']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isDividendsInArrears'], _first_across_rows(normalized_rows, ['isDividendsInArrears']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isRepurchaseSecurity'], _first_across_rows(normalized_rows, ['isRepurchaseSecurity']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isRightsOffering'], _first_across_rows(normalized_rows, ['isRightsOffering']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isSecondaryOffering'], _first_across_rows(normalized_rows, ['isSecondaryOffering']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isSecuritiesModified'], _first_across_rows(normalized_rows, ['isSecuritiesModified']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'managementFee'], _first_across_rows(normalized_rows, ['managementFee']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'marketPricePerShare'], _first_across_rows(normalized_rows, ['marketPricePerShare']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'netAssetValuePerShare'], _first_across_rows(normalized_rows, ['netAssetValuePerShare']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'netOperatingExpenses'], _first_across_rows(normalized_rows, ['netOperatingExpenses']))
    _add_path_attr(root, ['formData', 'generalInfo'], 'isReportPeriodLt12', _first_across_rows(normalized_rows, ['isReportPeriodLt12']))
    _add_path_attr(root, ['formData', 'generalInfo'], 'reportEndingPeriod', _first_across_rows(normalized_rows, ['reportEndingPeriod']))
    _add_path_text(root, ['formData', 'registrantInfo', 'investmentCompFileNo'], _first_across_rows(normalized_rows, ['investmentCompFileNo']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isAccountingPrincipleChange'], _first_across_rows(normalized_rows, ['isAccountingPrincipleChange']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isClaimFiled'], _first_across_rows(normalized_rows, ['isClaimFiled']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isCoveredByInsurancePolicy'], _first_across_rows(normalized_rows, ['isCoveredByInsurancePolicy']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isExemptionFromAct'], _first_across_rows(normalized_rows, ['isExemptionFromAct']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isFinancialSupportDuringPeriod'], _first_across_rows(normalized_rows, ['isFinancialSupportDuringPeriod']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isMaterialChange'], _first_across_rows(normalized_rows, ['isMaterialChange']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isMaterialWeakness'], _first_across_rows(normalized_rows, ['isMaterialWeakness']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isOpinionOffered'], _first_across_rows(normalized_rows, ['isOpinionOffered']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isPaymentDividend'], _first_across_rows(normalized_rows, ['isPaymentDividend']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isPaymentErrorInNetAssetValue'], _first_across_rows(normalized_rows, ['isPaymentErrorInNetAssetValue']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isPreviousLegalProceeding'], _first_across_rows(normalized_rows, ['isPreviousLegalProceeding']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isPreviousProceedingTerminated'], _first_across_rows(normalized_rows, ['isPreviousProceedingTerminated']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isPublicAccountantChanged'], _first_across_rows(normalized_rows, ['isPublicAccountantChanged']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantFamilyInvComp'], _first_across_rows(normalized_rows, ['isRegistrantFamilyInvComp']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantFirstFiling'], _first_across_rows(normalized_rows, ['isRegistrantFirstFiling']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantLastFiling'], _first_across_rows(normalized_rows, ['isRegistrantLastFiling']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantSubmittedMatter'], _first_across_rows(normalized_rows, ['isRegistrantSubmittedMatter']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isSecuritiesActRegistration'], _first_across_rows(normalized_rows, ['isSecuritiesActRegistration']))
    _add_path_text(root, ['formData', 'registrantInfo', 'isUnderwriterHiredOrTerminated'], _first_across_rows(normalized_rows, ['isUnderwriterHiredOrTerminated']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantCik'], _first_across_rows(normalized_rows, ['registrantCik']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantClassificationType'], _first_across_rows(normalized_rows, ['registrantClassificationType']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantFullName'], _first_across_rows(normalized_rows, ['registrantFullName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantLei'], _first_across_rows(normalized_rows, ['registrantLei']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantcity'], _first_across_rows(normalized_rows, ['registrantcity']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantcountry'], _first_across_rows(normalized_rows, ['registrantcountry']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantphoneNumber'], _first_across_rows(normalized_rows, ['registrantphoneNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantstate'], _first_across_rows(normalized_rows, ['registrantstate']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantstreet1'], _first_across_rows(normalized_rows, ['registrantstreet1']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantstreet2'], _first_across_rows(normalized_rows, ['registrantstreet2']))
    _add_path_text(root, ['formData', 'registrantInfo', 'registrantzipCode'], _first_across_rows(normalized_rows, ['registrantzipCode']))
    _add_path_text(root, ['formData', 'registrantInfo', 'totalSeries'], _first_across_rows(normalized_rows, ['totalSeries']))
    _add_path_attr(root, ['formData', 'signature'], 'registrantSignedName', _first_across_rows(normalized_rows, ['registrantSignedName']))
    _add_path_attr(root, ['formData', 'signature'], 'signature', _first_across_rows(normalized_rows, ['signature']))
    _add_path_attr(root, ['formData', 'signature'], 'signedDate', _first_across_rows(normalized_rows, ['signedDate']))
    _add_path_attr(root, ['formData', 'signature'], 'title', _first_across_rows(normalized_rows, ['title']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule11A2Reliance'], _first_across_rows(normalized_rows, ['isRule11A2Reliance']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule12D1Dash4Reliance'], _first_across_rows(normalized_rows, ['isRule12D1Dash4Reliance']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule12D1GReliance'], _first_across_rows(normalized_rows, ['isRule12D1GReliance']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule6C7Reliance'], _first_across_rows(normalized_rows, ['isRule6C7Reliance']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isUitAdminHiredTerminated'], _first_across_rows(normalized_rows, ['isUitAdminHiredTerminated']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'numOfContracts'], _first_across_rows(normalized_rows, ['numOfContracts']))
    _add_path_text(root, ['headerData', 'filerInfo', 'investmentCompanyType'], _first_across_rows(normalized_rows, ['investmentCompanyType']))
    _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], _first_across_rows(normalized_rows, ['liveTestFlag']))
    _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities'], 'isRepurchaseSecurity', _first_across_rows(normalized_rows, ['repurchaseSecuritiesIsRepurchaseSecurity']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities', 'otherRepurchaseSecurityDesc'], _first_across_rows(normalized_rows, ['otherRepurchaseSecurityDesc']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities', 'repurchaseSecurityType'], _first_across_rows(normalized_rows, ['repurchaseSecurityType']))
    _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds'], 'isRightsOffering', _first_across_rows(normalized_rows, ['rightsOfferingFundsIsRightsOffering']))
    _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'secondaryOfferings'], 'isSecondaryOffering', _first_across_rows(normalized_rows, ['secondaryOfferingsIsSecondaryOffering']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'secondaryOfferings', 'secondaryOfferingType'], _first_across_rows(normalized_rows, ['secondaryOfferingType']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitSDRedeemedInKind'], _first_across_rows(normalized_rows, ['creationUnitSDRedeemedInKind']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashPerUnit'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeeCashPerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'averagePercentagePurchased'], _first_across_rows(normalized_rows, ['averagePercentagePurchased']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'averagePercentageRedeemed'], _first_across_rows(normalized_rows, ['averagePercentageRedeemed']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitNumOfShares'], _first_across_rows(normalized_rows, ['creationUnitNumOfShares']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPercentageRedeemedInKind'], _first_across_rows(normalized_rows, ['creationUnitPercentageRedeemedInKind']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPurchasedInKind'], _first_across_rows(normalized_rows, ['creationUnitPurchasedInKind']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPurchasedSDInKind'], _first_across_rows(normalized_rows, ['creationUnitPurchasedSDInKind']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashManyUnits'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeeCashManyUnits']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashPercentagePerUnit'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeeCashPercentagePerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeManyUnits'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeeManyUnits']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeePerUnit'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeePerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeePercentagePerUnit'], _first_across_rows(normalized_rows, ['creationUnitTransactionFeePercentagePerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'etfSeriesId'], _first_across_rows(normalized_rows, ['etfSeriesId']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'fundName'], _first_across_rows(normalized_rows, ['fundName']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isByAffiliatedPerson'], _first_across_rows(normalized_rows, ['isByAffiliatedPerson']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isCollateralRequired'], _first_across_rows(normalized_rows, ['isCollateralRequired']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isExclusiveFund'], _first_across_rows(normalized_rows, ['isExclusiveFund']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isInKindETF'], _first_across_rows(normalized_rows, ['isInKindETF']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'percentSDRedeemed'], _first_across_rows(normalized_rows, ['percentSDRedeemed']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPerMoreUnits'], _first_across_rows(normalized_rows, ['purchaseCreationUnitCashPerMoreUnits']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPerUnit'], _first_across_rows(normalized_rows, ['purchaseCreationUnitCashPerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPercentagePerUnit'], _first_across_rows(normalized_rows, ['purchaseCreationUnitCashPercentagePerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPerMoreUnits'], _first_across_rows(normalized_rows, ['purchaseCreationUnitDollarPerMoreUnits']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPerUnit'], _first_across_rows(normalized_rows, ['purchaseCreationUnitDollarPerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPercentagePerUnit'], _first_across_rows(normalized_rows, ['purchaseCreationUnitDollarPercentagePerUnit']))
    _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'standardDeviationPurchased'], _first_across_rows(normalized_rows, ['standardDeviationPurchased']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'aggregateCommission'], _first_across_rows(normalized_rows, ['aggregateCommission']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'avgPortfolioSecuritiesValue'], _first_across_rows(normalized_rows, ['avgPortfolioSecuritiesValue']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'dailyAvgNetAssets'], _first_across_rows(normalized_rows, ['dailyAvgNetAssets']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'didFundLendSecurities'], _first_across_rows(normalized_rows, ['didFundLendSecurities']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundType'], _first_across_rows(normalized_rows, ['fundType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'hasLineOfCredit'], _first_across_rows(normalized_rows, ['hasLineOfCredit']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isAdminHiredOrTerminated'], _first_across_rows(normalized_rows, ['isAdminHiredOrTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isBrokerageResearchPayment'], _first_across_rows(normalized_rows, ['isBrokerageResearchPayment']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isCustodianHiredOrTerminated'], _first_across_rows(normalized_rows, ['isCustodianHiredOrTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseLimitationInPlace'], _first_across_rows(normalized_rows, ['isExpenseLimitationInPlace']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseReducedOrWaived'], _first_across_rows(normalized_rows, ['isExpenseReducedOrWaived']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseWaivedRecoupable'], _first_across_rows(normalized_rows, ['isExpenseWaivedRecoupable']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFeesWaivedRecoupable'], _first_across_rows(normalized_rows, ['isFeesWaivedRecoupable']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFirstFilingByFund'], _first_across_rows(normalized_rows, ['isFirstFilingByFund']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isForeignSubsidiary'], _first_across_rows(normalized_rows, ['isForeignSubsidiary']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFundSecuritiesLending'], _first_across_rows(normalized_rows, ['isFundSecuritiesLending']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isInterfundBorrowing'], _first_across_rows(normalized_rows, ['isInterfundBorrowing']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isInterfundLending'], _first_across_rows(normalized_rows, ['isInterfundLending']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isLiquidityHiredTerminated'], _first_across_rows(normalized_rows, ['isLiquidityHiredTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isNonDiversifiedCompany'], _first_across_rows(normalized_rows, ['isNonDiversifiedCompany']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isPricingServiceHiredOrTerminated'], _first_across_rows(normalized_rows, ['isPricingServiceHiredOrTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isShareholderServiceHiredTerminated'], _first_across_rows(normalized_rows, ['isShareholderServiceHiredTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isSwingPricing'], _first_across_rows(normalized_rows, ['isSwingPricing']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isTransferAgentHiredOrTerminated'], _first_across_rows(normalized_rows, ['isTransferAgentHiredOrTerminated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvFundName'], _first_across_rows(normalized_rows, ['mgmtInvFundName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvLei'], _first_across_rows(normalized_rows, ['mgmtInvLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvSeriesId'], _first_across_rows(normalized_rows, ['mgmtInvSeriesId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mnthlyAvgNetAssets'], _first_across_rows(normalized_rows, ['mnthlyAvgNetAssets']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'netIncomeSecuritiesLending'], _first_across_rows(normalized_rows, ['netIncomeSecuritiesLending']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numAddedClass'], _first_across_rows(normalized_rows, ['numAddedClass']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numAuthorizedClass'], _first_across_rows(normalized_rows, ['numAuthorizedClass']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numTerminatedClass'], _first_across_rows(normalized_rows, ['numTerminatedClass']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagerType'], _first_across_rows(normalized_rows, ['paymentToAgentManagerType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalAggregatePurchase'], _first_across_rows(normalized_rows, ['principalAggregatePurchase']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'relyOnRuleType'], _first_across_rows(normalized_rows, ['relyOnRuleType']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'coveredByInsurancePolicy'], 'isClaimFiledDuringPeriod', _first_across_rows(normalized_rows, ['isClaimFiledDuringPeriod']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'coveredByInsurancePolicy'], 'isCoveredByInsurancePolicy', _first_across_rows(normalized_rows, ['coveredByInsurancePolicyIsCoveredByInsurancePolicy']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'financialSupportSeriesInfo'], 'isFinancialSupportDuringPeriod', _first_across_rows(normalized_rows, ['financialSupportSeriesInfoIsFinancialSupportDuringPeriod']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo'], 'isPreviousLegalProceeding', _first_across_rows(normalized_rows, ['legalProceedingSeriesInfoIsPreviousLegalProceeding']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries'], 'isPaymentDividend', _first_across_rows(normalized_rows, ['paymentDividendSeriesIsPaymentDividend']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries'], 'isPaymentErrorInNetAssetValue', _first_across_rows(normalized_rows, ['paymentErrorSeriesIsPaymentErrorInNetAssetValue']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'previousProceedingTerminated'], 'isPreviousProceedingTerminated', _first_across_rows(normalized_rows, ['previousProceedingTerminatedIsPreviousProceedingTerminated']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'registrantFamilyInvComp'], 'familyInvCompFullName', _first_across_rows(normalized_rows, ['familyInvCompFullName']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'registrantFamilyInvComp'], 'isRegistrantFamilyInvComp', _first_across_rows(normalized_rows, ['registrantFamilyInvCompIsRegistrantFamilyInvComp']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'releaseNumbers'], 'isExemptionFromAct', _first_across_rows(normalized_rows, ['releaseNumbersIsExemptionFromAct']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo'], 'isRegistrantSubmittedMatter', _first_across_rows(normalized_rows, ['securityMatterSeriesInfoIsRegistrantSubmittedMatter']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges'], 'isMaterialChange', _first_across_rows(normalized_rows, ['valuationMethodsChangesIsMaterialChange']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount'], 'isRegistrantSeparateInsuranceAccount', _first_across_rows(normalized_rows, ['isRegistrantSeparateInsuranceAccount']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'additionalUnitsTotalValue'], _first_across_rows(normalized_rows, ['additionalUnitsTotalValue']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'newSeriesAggregateValue'], _first_across_rows(normalized_rows, ['newSeriesAggregateValue']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfExistingSeries'], _first_across_rows(normalized_rows, ['numOfExistingSeries']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfExistingSeriesAdditionalUnits'], _first_across_rows(normalized_rows, ['numOfExistingSeriesAdditionalUnits']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfNewSeriesRegistration'], _first_across_rows(normalized_rows, ['numOfNewSeriesRegistration']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfSeriesCurrentProspectus'], _first_across_rows(normalized_rows, ['numOfSeriesCurrentProspectus']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'totalAssetsSeries'], _first_across_rows(normalized_rows, ['totalAssetsSeries']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'unitInPortfolioValue'], _first_across_rows(normalized_rows, ['unitInPortfolioValue']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'registrantSeparateInsuranceAccount'], 'isRegistrantSeparateInsuranceAccount', _first_across_rows(normalized_rows, ['registrantSeparateInsuranceAccountIsRegistrantSeparateInsuranceAccount']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'registrantSeparateInsuranceAccount'], 'separateAccountSeriesId', _first_across_rows(normalized_rows, ['separateAccountSeriesId']))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], _first_across_rows(normalized_rows, ['fileNumber']))
    _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'confirmingCopyFlag'], _first_across_rows(normalized_rows, ['confirmingCopyFlag']))
    _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], _first_across_rows(normalized_rows, ['overrideInternetFlag']))
    _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], _first_across_rows(normalized_rows, ['returnCopyFlag']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportClass', 'rptIncludeAllClassesFlag'], _first_across_rows(normalized_rows, ['rptIncludeAllClassesFlag']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptIncludeAllSeriesFlag'], _first_across_rows(normalized_rows, ['rptIncludeAllSeriesFlag']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds', 'rightsOfferingFund', 'rightsOfferingParticipationPercent'], _first_across_rows(normalized_rows, ['rightsOfferingParticipationPercent']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'description'], _first_across_rows(normalized_rows, ['description']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'otherSecurityDescription'], _first_across_rows(normalized_rows, ['otherSecurityDescription']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'securityClassTitle'], _first_across_rows(normalized_rows, ['securityClassTitle']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments'], 'isForeignSubsidiary', _first_across_rows(normalized_rows, ['foreignInvestmentsIsForeignSubsidiary']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities'], 'didFundLendSecurities', _first_across_rows(normalized_rows, ['fundLendSecuritiesDidFundLendSecurities']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities', 'isFundAdverselyImpacted'], _first_across_rows(normalized_rows, ['isFundAdverselyImpacted']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities', 'isFundLiquidated'], _first_across_rows(normalized_rows, ['isFundLiquidated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'fundType'], _first_across_rows(normalized_rows, ['fundTypesFundType']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails'], 'isInterfundBorrowing', _first_across_rows(normalized_rows, ['interfundBorrowingDetailsIsInterfundBorrowing']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails'], 'isInterfundLending', _first_across_rows(normalized_rows, ['interfundLendingDetailsIsInterfundLending']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit'], 'hasLineOfCredit', _first_across_rows(normalized_rows, ['lineOfCreditHasLineOfCredit']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagers', 'otherFeeDesc'], _first_across_rows(normalized_rows, ['otherFeeDesc']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagers', 'paymentToAgentManagerType'], _first_across_rows(normalized_rows, ['paymentToAgentManagersPaymentToAgentManagerType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'relyOnRuleTypes', 'relyOnRuleType'], _first_across_rows(normalized_rows, ['relyOnRuleTypesRelyOnRuleType']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries', 'seriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['seriesInfoSeriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries', 'seriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['seriesInfoSeriesName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoCity'], _first_across_rows(normalized_rows, ['ccoCity']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoName'], _first_across_rows(normalized_rows, ['ccoName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoPhone'], _first_across_rows(normalized_rows, ['ccoPhone']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStreet1'], _first_across_rows(normalized_rows, ['ccoStreet1']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStreet2'], _first_across_rows(normalized_rows, ['ccoStreet2']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoZipCode'], _first_across_rows(normalized_rows, ['ccoZipCode']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'crdNumber'], _first_across_rows(normalized_rows, ['crdNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'isCcoChangedSinceLastFiling'], _first_across_rows(normalized_rows, ['isCcoChangedSinceLastFiling']))
    _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'crdNumber'], _first_across_rows(normalized_rows, ['directorCrdNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'directorName'], _first_across_rows(normalized_rows, ['directorName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'isDirectorInterestedPerson'], _first_across_rows(normalized_rows, ['isDirectorInterestedPerson']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo', 'seriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['seriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo', 'seriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['seriesName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'booksRecordsDesc'], _first_across_rows(normalized_rows, ['booksRecordsDesc']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeAddress1'], _first_across_rows(normalized_rows, ['officeAddress1']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeAddress2'], _first_across_rows(normalized_rows, ['officeAddress2']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeCity'], _first_across_rows(normalized_rows, ['officeCity']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeCountry'], _first_across_rows(normalized_rows, ['officeCountry']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeName'], _first_across_rows(normalized_rows, ['officeName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officePhone'], _first_across_rows(normalized_rows, ['officePhone']))
    _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeRecordsZipCode'], _first_across_rows(normalized_rows, ['officeRecordsZipCode']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries', 'seriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['paymentErrorSeriesSeriesInfoSeriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries', 'seriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['paymentErrorSeriesSeriesInfoSeriesName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'isPrincipalUnderwriterAffiliatedWithRegistrant'], _first_across_rows(normalized_rows, ['isPrincipalUnderwriterAffiliatedWithRegistrant']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterName'], _first_across_rows(normalized_rows, ['principalUnderwriterName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterCrdNumber'], _first_across_rows(normalized_rows, ['principalUnderwriterCrdNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterFileNumber'], _first_across_rows(normalized_rows, ['principalUnderwriterFileNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterLei'], _first_across_rows(normalized_rows, ['principalUnderwriterLei']))
    _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterRssdId'], _first_across_rows(normalized_rows, ['principalUnderwriterRssdId']))
    _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'pcaobNumber'], _first_across_rows(normalized_rows, ['pcaobNumber']))
    _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantName'], _first_across_rows(normalized_rows, ['publicAccountantName']))
    _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantLei'], _first_across_rows(normalized_rows, ['publicAccountantLei']))
    _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantRssdId'], _first_across_rows(normalized_rows, ['publicAccountantRssdId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'releaseNumbers', 'releaseNumberInfo'], 'releaseNumber', _first_across_rows(normalized_rows, ['releaseNumber']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo', 'seriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['securityMatterSeriesInfoSeriesInfoSeriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo', 'seriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['securityMatterSeriesInfoSeriesInfoSeriesName']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['terminatedSeriesInfoSeriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['terminatedSeriesInfoSeriesName']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'terminationDate', _first_across_rows(normalized_rows, ['terminationDate']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'assetType'], _first_across_rows(normalized_rows, ['assetType']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'assetTypeOtherDesc'], _first_across_rows(normalized_rows, ['assetTypeOtherDesc']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'changeExplanation'], _first_across_rows(normalized_rows, ['changeExplanation']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'dateOfChange'], _first_across_rows(normalized_rows, ['dateOfChange']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'investmentType'], _first_across_rows(normalized_rows, ['investmentType']))
    _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'statutoryRegulatoryBasis'], _first_across_rows(normalized_rows, ['statutoryRegulatoryBasis']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'websites', 'website'], 'webpage', _first_across_rows(normalized_rows, ['webpage']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'contractValueRedeemed', _first_across_rows(normalized_rows, ['contractValueRedeemed']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'contractValueRedeemedSection1035', _first_across_rows(normalized_rows, ['contractValueRedeemedSection1035']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'grossPremiumReceived', _first_across_rows(normalized_rows, ['grossPremiumReceived']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'grossPremiumReceivedSection1035', _first_across_rows(normalized_rows, ['grossPremiumReceivedSection1035']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsAffected', _first_across_rows(normalized_rows, ['numContractsAffected']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsAffectedRedeemed', _first_across_rows(normalized_rows, ['numContractsAffectedRedeemed']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsSold', _first_across_rows(normalized_rows, ['numContractsSold']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountContractId', _first_across_rows(normalized_rows, ['separateAccountContractId']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountSecurityName', _first_across_rows(normalized_rows, ['separateAccountSecurityName']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountTotalAsset', _first_across_rows(normalized_rows, ['separateAccountTotalAsset']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorCrdNo'], _first_across_rows(normalized_rows, ['depositorCrdNo']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorLei'], _first_across_rows(normalized_rows, ['depositorLei']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorName'], _first_across_rows(normalized_rows, ['depositorName']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorUltimateParentname'], _first_across_rows(normalized_rows, ['depositorUltimateParentname']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserStateCountry'], 'investmentAdviserState', _first_across_rows(normalized_rows, ['investmentAdviserState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserStateCountry'], 'investmentAdviserCountry', _first_across_rows(normalized_rows, ['investmentAdviserStateCountryInvestmentAdviserCountry']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'isUitAdminAffiliated'], _first_across_rows(normalized_rows, ['isUitAdminAffiliated']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'isUitAdminSubAdmin'], _first_across_rows(normalized_rows, ['isUitAdminSubAdmin']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminName'], _first_across_rows(normalized_rows, ['uitAdminName']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminDescOtherNumber'], _first_across_rows(normalized_rows, ['uitAdminDescOtherNumber']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminLei'], _first_across_rows(normalized_rows, ['uitAdminLei']))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'issuerCredentials', 'ccc'], _first_across_rows(normalized_rows, ['ccc']))
    _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'issuerCredentials', 'cik'], _first_across_rows(normalized_rows, ['cik']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportClass', 'classInfo', 'classId'], _first_across_rows(normalized_rows, ['classId']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'includeAllClassesFlag'], _first_across_rows(normalized_rows, ['includeAllClassesFlag']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'seriesId'], _first_across_rows(normalized_rows, ['rptSeriesClassInfoSeriesId']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerStateCountry'], 'brokerDealerState', _first_across_rows(normalized_rows, ['brokerDealerState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundName', _first_across_rows(normalized_rows, ['masterFundName']))
    _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds', 'rightsOfferingFund', 'rightsOfferingTypes', 'rightsOfferingType'], _first_across_rows(normalized_rows, ['rightsOfferingType']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantCrdNo', _first_across_rows(normalized_rows, ['authorizedParticipantCrdNo']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantFileNo', _first_across_rows(normalized_rows, ['authorizedParticipantFileNo']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantLei', _first_across_rows(normalized_rows, ['authorizedParticipantLei']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantName', _first_across_rows(normalized_rows, ['authorizedParticipantName']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantPurchaseValue', _first_across_rows(normalized_rows, ['authorizedParticipantPurchaseValue']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantRedeemValue', _first_across_rows(normalized_rows, ['authorizedParticipantRedeemValue']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'securityExchanges', 'securityExchange'], 'fundExchange', _first_across_rows(normalized_rows, ['fundExchange']))
    _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'securityExchanges', 'securityExchange'], 'fundsTickerSymbol', _first_across_rows(normalized_rows, ['fundsTickerSymbol']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminCountry'], _first_across_rows(normalized_rows, ['adminCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminLei'], _first_across_rows(normalized_rows, ['adminLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminName'], _first_across_rows(normalized_rows, ['adminName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminOther'], _first_across_rows(normalized_rows, ['adminOther']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminRssdId'], _first_across_rows(normalized_rows, ['adminRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'idNumberDesc'], _first_across_rows(normalized_rows, ['idNumberDesc']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'isAdminAffiliated'], _first_across_rows(normalized_rows, ['isAdminAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'isAdminSubAdmin'], _first_across_rows(normalized_rows, ['isAdminSubAdmin']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCommission'], _first_across_rows(normalized_rows, ['brokerDealerCommission']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCountry'], _first_across_rows(normalized_rows, ['brokerDealerCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCrdNo'], _first_across_rows(normalized_rows, ['brokerDealerCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerFileNo'], _first_across_rows(normalized_rows, ['brokerDealerFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerLei'], _first_across_rows(normalized_rows, ['brokerDealerLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerName'], _first_across_rows(normalized_rows, ['brokerDealerName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerRssdId'], _first_across_rows(normalized_rows, ['brokerDealerRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerCountry'], _first_across_rows(normalized_rows, ['brokerCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerCrdNo'], _first_across_rows(normalized_rows, ['brokerCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerFileNo'], _first_across_rows(normalized_rows, ['brokerFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerLei'], _first_across_rows(normalized_rows, ['brokerLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerName'], _first_across_rows(normalized_rows, ['brokerName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerRssdId'], _first_across_rows(normalized_rows, ['brokerRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'grossCommission'], _first_across_rows(normalized_rows, ['grossCommission']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'collateralManagerLei', _first_across_rows(normalized_rows, ['collateralManagerLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'collateralManagerName', _first_across_rows(normalized_rows, ['collateralManagerName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'isCollateralManagerAffliliated', _first_across_rows(normalized_rows, ['isCollateralManagerAffliliated']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'isCollateralManagerAffliliatedWithFund', _first_across_rows(normalized_rows, ['isCollateralManagerAffliliatedWithFund']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianCountry'], _first_across_rows(normalized_rows, ['custodianCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianLei'], _first_across_rows(normalized_rows, ['custodianLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianName'], _first_across_rows(normalized_rows, ['custodianName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianRssdId'], _first_across_rows(normalized_rows, ['custodianRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodyType'], _first_across_rows(normalized_rows, ['custodyType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'isCustodianAffiliated'], _first_across_rows(normalized_rows, ['isCustodianAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'isSubCustodian'], _first_across_rows(normalized_rows, ['isSubCustodian']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'otherCustodianDesc'], _first_across_rows(normalized_rows, ['otherCustodianDesc']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments', 'foreignInvestment'], 'foreignSubsidiaryLei', _first_across_rows(normalized_rows, ['foreignSubsidiaryLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments', 'foreignInvestment'], 'foreignSubsidiaryName', _first_across_rows(normalized_rows, ['foreignSubsidiaryName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo'], 'fundType', _first_across_rows(normalized_rows, ['indexFundInfoFundType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDailyStdevAfterExpense'], _first_across_rows(normalized_rows, ['indexFundReturnDailyStdevAfterExpense']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDailyStdevBeforeExpense'], _first_across_rows(normalized_rows, ['indexFundReturnDailyStdevBeforeExpense']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDiffAfterExpense'], _first_across_rows(normalized_rows, ['indexFundReturnDiffAfterExpense']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDiffBeforeExpense'], _first_across_rows(normalized_rows, ['indexFundReturnDiffBeforeExpense']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'isIndexFundAffiliated'], _first_across_rows(normalized_rows, ['isIndexFundAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'isIndexFundExclusive'], _first_across_rows(normalized_rows, ['isIndexFundExclusive']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo'], 'fundType', _first_across_rows(normalized_rows, ['masterFeederFundInfoFundType']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails', 'interfundBorrowing'], 'interfundBorrowingDaysOutstanding', _first_across_rows(normalized_rows, ['interfundBorrowingDaysOutstanding']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails', 'interfundBorrowing'], 'interfundBorrowingLoanAverage', _first_across_rows(normalized_rows, ['interfundBorrowingLoanAverage']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails', 'interfundLending'], 'interfundLendingDaysOutstanding', _first_across_rows(normalized_rows, ['interfundLendingDaysOutstanding']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails', 'interfundLending'], 'interfundLendingLoanAverage', _first_across_rows(normalized_rows, ['interfundLendingLoanAverage']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserCountry'], _first_across_rows(normalized_rows, ['investmentAdviserCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserCrdNo'], _first_across_rows(normalized_rows, ['investmentAdviserCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserFileNo'], _first_across_rows(normalized_rows, ['investmentAdviserFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserLei'], _first_across_rows(normalized_rows, ['investmentAdviserLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserName'], _first_across_rows(normalized_rows, ['investmentAdviserName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserRssdId'], _first_across_rows(normalized_rows, ['investmentAdviserRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'isInvestmentAdviserHired'], _first_across_rows(normalized_rows, ['isInvestmentAdviserHired']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedCrdNo'], _first_across_rows(normalized_rows, ['investAdviserTerminatedCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedFileNo'], _first_across_rows(normalized_rows, ['investAdviserTerminatedFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedLei'], _first_across_rows(normalized_rows, ['investAdviserTerminatedLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminationDate'], _first_across_rows(normalized_rows, ['investAdviserTerminationDate']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedName'], _first_across_rows(normalized_rows, ['investmentAdviserTerminatedName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'assetClassType'], _first_across_rows(normalized_rows, ['assetClassType']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'isAffiliatedPerson'], _first_across_rows(normalized_rows, ['isAffiliatedPerson']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityName'], _first_across_rows(normalized_rows, ['liquidityName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityLei'], _first_across_rows(normalized_rows, ['liquidityLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityRssdId'], _first_across_rows(normalized_rows, ['liquidityRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'isPricingServiceAffiliated'], _first_across_rows(normalized_rows, ['isPricingServiceAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceCountry'], _first_across_rows(normalized_rows, ['pricingServiceCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceIdNumberDesc'], _first_across_rows(normalized_rows, ['pricingServiceIdNumberDesc']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceLei'], _first_across_rows(normalized_rows, ['pricingServiceLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceName'], _first_across_rows(normalized_rows, ['pricingServiceName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceOther'], _first_across_rows(normalized_rows, ['pricingServiceOther']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceRssdId'], _first_across_rows(normalized_rows, ['pricingServiceRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalCountry'], _first_across_rows(normalized_rows, ['principalCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalCrdNo'], _first_across_rows(normalized_rows, ['principalCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalFileNo'], _first_across_rows(normalized_rows, ['principalFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalLei'], _first_across_rows(normalized_rows, ['principalLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalName'], _first_across_rows(normalized_rows, ['principalName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalRssdId'], _first_across_rows(normalized_rows, ['principalRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalTotalPurchaseSale'], _first_across_rows(normalized_rows, ['principalTotalPurchaseSale']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'isSecuritiesAgentAffiliated'], _first_across_rows(normalized_rows, ['isSecuritiesAgentAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'isSecurityAgentIdemnity'], _first_across_rows(normalized_rows, ['isSecurityAgentIdemnity']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securitiesAgentLei'], _first_across_rows(normalized_rows, ['securitiesAgentLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securitiesAgentName'], _first_across_rows(normalized_rows, ['securitiesAgentName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'isShareholderServiceAgentAffiliated'], _first_across_rows(normalized_rows, ['isShareholderServiceAgentAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'isShareholderServiceAgentSubshare'], _first_across_rows(normalized_rows, ['isShareholderServiceAgentSubshare']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentCountry'], _first_across_rows(normalized_rows, ['shareholderServiceAgentCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentLei'], _first_across_rows(normalized_rows, ['shareholderServiceAgentLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentName'], _first_across_rows(normalized_rows, ['shareholderServiceAgentName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentOther'], _first_across_rows(normalized_rows, ['shareholderServiceAgentOther']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentRssdId'], _first_across_rows(normalized_rows, ['shareholderServiceAgentRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceIdNumberDesc'], _first_across_rows(normalized_rows, ['shareholderServiceIdNumberDesc']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingClassId', _first_across_rows(normalized_rows, ['sharesOutstandingClassId']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingClassName', _first_across_rows(normalized_rows, ['sharesOutstandingClassName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingTickerSymbol', _first_across_rows(normalized_rows, ['sharesOutstandingTickerSymbol']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'isSubAdviserAffiliated'], _first_across_rows(normalized_rows, ['isSubAdviserAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'isSubAdviserHired'], _first_across_rows(normalized_rows, ['isSubAdviserHired']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserCountry'], _first_across_rows(normalized_rows, ['subAdviserCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserCrdNo'], _first_across_rows(normalized_rows, ['subAdviserCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserFileNo'], _first_across_rows(normalized_rows, ['subAdviserFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserLei'], _first_across_rows(normalized_rows, ['subAdviserLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserName'], _first_across_rows(normalized_rows, ['subAdviserName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserRssdId'], _first_across_rows(normalized_rows, ['subAdviserRssdId']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedCountry'], _first_across_rows(normalized_rows, ['subAdviserTerminatedCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedCrdNo'], _first_across_rows(normalized_rows, ['subAdviserTerminatedCrdNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedFileNo'], _first_across_rows(normalized_rows, ['subAdviserTerminatedFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedLei'], _first_across_rows(normalized_rows, ['subAdviserTerminatedLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedName'], _first_across_rows(normalized_rows, ['subAdviserTerminatedName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminationDate'], _first_across_rows(normalized_rows, ['subAdviserTerminationDate']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'isTransferAgentAffiliated'], _first_across_rows(normalized_rows, ['isTransferAgentAffiliated']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'isTransferAgentSubAgent'], _first_across_rows(normalized_rows, ['isTransferAgentSubAgent']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentCountry'], _first_across_rows(normalized_rows, ['transferAgentCountry']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentFileNo'], _first_across_rows(normalized_rows, ['transferAgentFileNo']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentLei'], _first_across_rows(normalized_rows, ['transferAgentLei']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentName'], _first_across_rows(normalized_rows, ['transferAgentName']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentRssdId'], _first_across_rows(normalized_rows, ['transferAgentRssdId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStateCountry'], 'ccoCountry', _first_across_rows(normalized_rows, ['ccoCountry']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStateCountry'], 'ccoState', _first_across_rows(normalized_rows, ['ccoState']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeStateCountry'], 'officeCountry', _first_across_rows(normalized_rows, ['officeStateCountryOfficeCountry']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeStateCountry'], 'officeState', _first_across_rows(normalized_rows, ['officeState']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderWriterStateCountry'], 'principalUnderWriterCountry', _first_across_rows(normalized_rows, ['principalUnderWriterCountry']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderWriterStateCountry'], 'principalUnderWriterState', _first_across_rows(normalized_rows, ['principalUnderWriterState']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantStateCountry'], 'publicAccountantCountry', _first_across_rows(normalized_rows, ['publicAccountantCountry']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantStateCountry'], 'publicAccountantState', _first_across_rows(normalized_rows, ['publicAccountantState']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorStateCountry'], 'depositorCountry', _first_across_rows(normalized_rows, ['depositorCountry']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorStateCountry'], 'depositorState', _first_across_rows(normalized_rows, ['depositorState']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'seriesCIKs', 'seriesCIK'], 'cik', _first_across_rows(normalized_rows, ['seriesCIKCik']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorCrdNo'], _first_across_rows(normalized_rows, ['sponsorCrdNo']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorLei'], _first_across_rows(normalized_rows, ['sponsorLei']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorName'], _first_across_rows(normalized_rows, ['sponsorName']))
    _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeName'], _first_across_rows(normalized_rows, ['trusteeName']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminStateCountry'], 'uitAdminCountry', _first_across_rows(normalized_rows, ['uitAdminCountry']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminStateCountry'], 'uitAdminState', _first_across_rows(normalized_rows, ['uitAdminState']))
    _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'classInfo', 'classId'], _first_across_rows(normalized_rows, ['classInfoClassId']))
    _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'commonStocks', 'commonStock'], 'commonStockExchange', _first_across_rows(normalized_rows, ['commonStockExchange']))
    _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'commonStocks', 'commonStock'], 'commonStockTickerSymbol', _first_across_rows(normalized_rows, ['commonStockTickerSymbol']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminStateCountry'], 'adminCountry', _first_across_rows(normalized_rows, ['adminStateCountryAdminCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminStateCountry'], 'adminState', _first_across_rows(normalized_rows, ['adminState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerStateCountry'], 'brokerDealerCountry', _first_across_rows(normalized_rows, ['brokerDealerStateCountryBrokerDealerCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerStateCountry'], 'brokerCountry', _first_across_rows(normalized_rows, ['brokerStateCountryBrokerCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerStateCountry'], 'brokerState', _first_across_rows(normalized_rows, ['brokerState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianStateCountry'], 'custodianCountry', _first_across_rows(normalized_rows, ['custodianStateCountryCustodianCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianStateCountry'], 'custodianState', _first_across_rows(normalized_rows, ['custodianState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'feederFundName', _first_across_rows(normalized_rows, ['feederFundName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundFileNo', _first_across_rows(normalized_rows, ['regFeederFundFileNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundLei', _first_across_rows(normalized_rows, ['regFeederFundLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundSeriesIdNo', _first_across_rows(normalized_rows, ['regFeederFundSeriesIdNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'unregFeederFileNo', _first_across_rows(normalized_rows, ['unregFeederFileNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'unregFeederFundLei', _first_across_rows(normalized_rows, ['unregFeederFundLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundFileNo', _first_across_rows(normalized_rows, ['masterFundFileNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundLei', _first_across_rows(normalized_rows, ['masterFundLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundSECFileNo', _first_across_rows(normalized_rows, ['masterFundSECFileNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserHired'], 'isInvestmentAdviserHired', _first_across_rows(normalized_rows, ['investmentAdviserHiredIsInvestmentAdviserHired']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserHired', 'investmentAdviserStartDate'], _first_across_rows(normalized_rows, ['investmentAdviserStartDate']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedStateCountry'], 'investmentAdviserTerminatedCountry', _first_across_rows(normalized_rows, ['investmentAdviserTerminatedCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedStateCountry'], 'investmentAdviserTerminatedState', _first_across_rows(normalized_rows, ['investmentAdviserTerminatedState']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'isCreditLineCommitted'], _first_across_rows(normalized_rows, ['isCreditLineCommitted']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'isCreditLineUsed'], _first_across_rows(normalized_rows, ['isCreditLineUsed']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'lineOfCreditSize'], _first_across_rows(normalized_rows, ['lineOfCreditSize']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityStateCountry'], 'liquidityCountry', _first_across_rows(normalized_rows, ['liquidityCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityStateCountry'], 'liquidityState', _first_across_rows(normalized_rows, ['liquidityState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceStateCountry'], 'pricingServiceCountry', _first_across_rows(normalized_rows, ['pricingServiceStateCountryPricingServiceCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceStateCountry'], 'pricingServiceState', _first_across_rows(normalized_rows, ['pricingServiceState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalStateCountry'], 'principalCountry', _first_across_rows(normalized_rows, ['principalStateCountryPrincipalCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalStateCountry'], 'principalState', _first_across_rows(normalized_rows, ['principalState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity'], 'isSecurityAgentIdemnity', _first_across_rows(normalized_rows, ['securityAgentIdemnityIsSecurityAgentIdemnity']))
    _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'didIndemnificationRights'], _first_across_rows(normalized_rows, ['didIndemnificationRights']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentStateCountry'], 'shareholderServiceAgentCountry', _first_across_rows(normalized_rows, ['shareholderServiceAgentStateCountryShareholderServiceAgentCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentStateCountry'], 'shareholderServiceAgentState', _first_across_rows(normalized_rows, ['shareholderServiceAgentState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserHired'], 'isSubAdviserHired', _first_across_rows(normalized_rows, ['subAdviserHiredIsSubAdviserHired']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserHired'], 'subAdviserStartDate', _first_across_rows(normalized_rows, ['subAdviserStartDate']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserStateCountry'], 'subAdviserCountry', _first_across_rows(normalized_rows, ['subAdviserStateCountrySubAdviserCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserStateCountry'], 'subAdviserState', _first_across_rows(normalized_rows, ['subAdviserState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedStateCountry'], 'subAdviserTerminatedCountry', _first_across_rows(normalized_rows, ['subAdviserTerminatedStateCountrySubAdviserTerminatedCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedStateCountry'], 'subAdviserTerminatedState', _first_across_rows(normalized_rows, ['subAdviserTerminatedState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentStateCountry'], 'transferAgentCountry', _first_across_rows(normalized_rows, ['transferAgentStateCountryTransferAgentCountry']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentStateCountry'], 'transferAgentState', _first_across_rows(normalized_rows, ['transferAgentState']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoEmployers', 'ccoEmployer'], 'ccoEmployerId', _first_across_rows(normalized_rows, ['ccoEmployerId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoEmployers', 'ccoEmployer'], 'ccoEmployerName', _first_across_rows(normalized_rows, ['ccoEmployerName']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'directors', 'director', 'fileNumbers', 'fileNumberInfo'], 'fileNumber', _first_across_rows(normalized_rows, ['fileNumberInfoFileNumber']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'valuationMethodsChangeSeries', 'seriesInfo'], 'seriesId', _first_across_rows(normalized_rows, ['valuationMethodsChangeSeriesSeriesInfoSeriesId']))
    _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'valuationMethodsChangeSeries', 'seriesInfo'], 'seriesName', _first_across_rows(normalized_rows, ['valuationMethodsChangeSeriesSeriesInfoSeriesName']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorStateCountry'], 'sponsorCountry', _first_across_rows(normalized_rows, ['sponsorCountry']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorStateCountry'], 'sponsorState', _first_across_rows(normalized_rows, ['sponsorState']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeStateCountry'], 'trusteeCountry', _first_across_rows(normalized_rows, ['trusteeCountry']))
    _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeStateCountry'], 'trusteeState', _first_across_rows(normalized_rows, ['trusteeState']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'averageCreditLineUsed', _first_across_rows(normalized_rows, ['averageCreditLineUsed']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'daysCreditUsed', _first_across_rows(normalized_rows, ['daysCreditUsed']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'isCreditLineUsed', _first_across_rows(normalized_rows, ['creditLineUsedIsCreditLineUsed']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType'], 'creditType', _first_across_rows(normalized_rows, ['creditType']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'soleCreditType'], 'creditType', _first_across_rows(normalized_rows, ['soleCreditTypeCreditType']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'lineOfCreditInstitutions', 'lineOfCreditInstitution'], 'creditInstitutionName', _first_across_rows(normalized_rows, ['creditInstitutionName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType', 'creditUser'], 'fundName', _first_across_rows(normalized_rows, ['creditUserFundName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType', 'creditUser'], 'secFileNo', _first_across_rows(normalized_rows, ['secFileNo']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderLei', _first_across_rows(normalized_rows, ['idemnityProviderLei']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderName', _first_across_rows(normalized_rows, ['idemnityProviderName']))
    _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderRssdId', _first_across_rows(normalized_rows, ['idemnityProviderRssdId']))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')



