import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text, _ensure_path


def _add_path_attr(root: ET.Element, tags: list[str], attr_name: str, value) -> None:
    if value is None:
        return
    target = _ensure_path(root, tags)
    if attr_name not in target.attrib:
        target.set(attr_name, str(value))

def construct_ncen(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/ncen')
    for row in normalized_rows:
        _add_path_text(root, ['schemaVersion'], row.get('schemaVersion'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isChangeAccPrinciples'], row.get('isChangeAccPrinciples'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isCodeOfEthics'], row.get('isCodeOfEthics'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isIPAReportInternalControl'], row.get('isIPAReportInternalControl'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isInfoItem405'], row.get('isInfoItem405'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isInfoRequiredEO'], row.get('isInfoRequiredEO'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isInstDefiningRights'], row.get('isInstDefiningRights'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isLegalProceedings'], row.get('isLegalProceedings'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isMaterialAmendments'], row.get('isMaterialAmendments'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isNewOrAmendedInvAdvContracts'], row.get('isNewOrAmendedInvAdvContracts'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isOtherInfoRequired'], row.get('isOtherInfoRequired'))
        _add_path_text(root, ['formData', 'attachmentsTab', 'isProvisionFinancialSupport'], row.get('isProvisionFinancialSupport'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isDefaultLongTermDebt'], row.get('isDefaultLongTermDebt'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isDividendsInArrears'], row.get('isDividendsInArrears'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isRepurchaseSecurity'], row.get('isRepurchaseSecurity'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isRightsOffering'], row.get('isRightsOffering'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isSecondaryOffering'], row.get('isSecondaryOffering'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'isSecuritiesModified'], row.get('isSecuritiesModified'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'managementFee'], row.get('managementFee'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'marketPricePerShare'], row.get('marketPricePerShare'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'netAssetValuePerShare'], row.get('netAssetValuePerShare'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'netOperatingExpenses'], row.get('netOperatingExpenses'))
        _add_path_attr(root, ['formData', 'generalInfo'], 'isReportPeriodLt12', row.get('isReportPeriodLt12'))
        _add_path_attr(root, ['formData', 'generalInfo'], 'reportEndingPeriod', row.get('reportEndingPeriod'))
        _add_path_text(root, ['formData', 'registrantInfo', 'investmentCompFileNo'], row.get('investmentCompFileNo'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isAccountingPrincipleChange'], row.get('isAccountingPrincipleChange'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isClaimFiled'], row.get('isClaimFiled'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isCoveredByInsurancePolicy'], row.get('isCoveredByInsurancePolicy'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isExemptionFromAct'], row.get('isExemptionFromAct'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isFinancialSupportDuringPeriod'], row.get('isFinancialSupportDuringPeriod'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isMaterialChange'], row.get('isMaterialChange'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isMaterialWeakness'], row.get('isMaterialWeakness'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isOpinionOffered'], row.get('isOpinionOffered'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isPaymentDividend'], row.get('isPaymentDividend'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isPaymentErrorInNetAssetValue'], row.get('isPaymentErrorInNetAssetValue'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isPreviousLegalProceeding'], row.get('isPreviousLegalProceeding'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isPreviousProceedingTerminated'], row.get('isPreviousProceedingTerminated'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isPublicAccountantChanged'], row.get('isPublicAccountantChanged'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantFamilyInvComp'], row.get('isRegistrantFamilyInvComp'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantFirstFiling'], row.get('isRegistrantFirstFiling'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantLastFiling'], row.get('isRegistrantLastFiling'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isRegistrantSubmittedMatter'], row.get('isRegistrantSubmittedMatter'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isSecuritiesActRegistration'], row.get('isSecuritiesActRegistration'))
        _add_path_text(root, ['formData', 'registrantInfo', 'isUnderwriterHiredOrTerminated'], row.get('isUnderwriterHiredOrTerminated'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantCik'], row.get('registrantCik'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantClassificationType'], row.get('registrantClassificationType'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantFullName'], row.get('registrantFullName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantLei'], row.get('registrantLei'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantcity'], row.get('registrantcity'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantcountry'], row.get('registrantcountry'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantphoneNumber'], row.get('registrantphoneNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantstate'], row.get('registrantstate'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantstreet1'], row.get('registrantstreet1'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantstreet2'], row.get('registrantstreet2'))
        _add_path_text(root, ['formData', 'registrantInfo', 'registrantzipCode'], row.get('registrantzipCode'))
        _add_path_text(root, ['formData', 'registrantInfo', 'totalSeries'], row.get('totalSeries'))
        _add_path_attr(root, ['formData', 'signature'], 'registrantSignedName', row.get('registrantSignedName'))
        _add_path_attr(root, ['formData', 'signature'], 'signature', row.get('signature'))
        _add_path_attr(root, ['formData', 'signature'], 'signedDate', row.get('signedDate'))
        _add_path_attr(root, ['formData', 'signature'], 'title', row.get('title'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule11A2Reliance'], row.get('isRule11A2Reliance'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule12D1Dash4Reliance'], row.get('isRule12D1Dash4Reliance'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule12D1GReliance'], row.get('isRule12D1GReliance'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isRule6C7Reliance'], row.get('isRule6C7Reliance'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'isUitAdminHiredTerminated'], row.get('isUitAdminHiredTerminated'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'numOfContracts'], row.get('numOfContracts'))
        _add_path_text(root, ['headerData', 'filerInfo', 'investmentCompanyType'], row.get('investmentCompanyType'))
        _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], row.get('liveTestFlag'))
        _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities'], 'isRepurchaseSecurity', row.get('repurchaseSecuritiesIsRepurchaseSecurity'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities', 'otherRepurchaseSecurityDesc'], row.get('otherRepurchaseSecurityDesc'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'repurchaseSecurities', 'repurchaseSecurityType'], row.get('repurchaseSecurityType'))
        _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds'], 'isRightsOffering', row.get('rightsOfferingFundsIsRightsOffering'))
        _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'secondaryOfferings'], 'isSecondaryOffering', row.get('secondaryOfferingsIsSecondaryOffering'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'secondaryOfferings', 'secondaryOfferingType'], row.get('secondaryOfferingType'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitSDRedeemedInKind'], row.get('creationUnitSDRedeemedInKind'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashPerUnit'], row.get('creationUnitTransactionFeeCashPerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'averagePercentagePurchased'], row.get('averagePercentagePurchased'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'averagePercentageRedeemed'], row.get('averagePercentageRedeemed'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitNumOfShares'], row.get('creationUnitNumOfShares'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPercentageRedeemedInKind'], row.get('creationUnitPercentageRedeemedInKind'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPurchasedInKind'], row.get('creationUnitPurchasedInKind'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitPurchasedSDInKind'], row.get('creationUnitPurchasedSDInKind'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashManyUnits'], row.get('creationUnitTransactionFeeCashManyUnits'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeCashPercentagePerUnit'], row.get('creationUnitTransactionFeeCashPercentagePerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeeManyUnits'], row.get('creationUnitTransactionFeeManyUnits'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeePerUnit'], row.get('creationUnitTransactionFeePerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'creationUnitTransactionFeePercentagePerUnit'], row.get('creationUnitTransactionFeePercentagePerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'etfSeriesId'], row.get('etfSeriesId'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'fundName'], row.get('fundName'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isByAffiliatedPerson'], row.get('isByAffiliatedPerson'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isCollateralRequired'], row.get('isCollateralRequired'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isExclusiveFund'], row.get('isExclusiveFund'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'isInKindETF'], row.get('isInKindETF'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'percentSDRedeemed'], row.get('percentSDRedeemed'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPerMoreUnits'], row.get('purchaseCreationUnitCashPerMoreUnits'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPerUnit'], row.get('purchaseCreationUnitCashPerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitCashPercentagePerUnit'], row.get('purchaseCreationUnitCashPercentagePerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPerMoreUnits'], row.get('purchaseCreationUnitDollarPerMoreUnits'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPerUnit'], row.get('purchaseCreationUnitDollarPerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'purchaseCreationUnitDollarPercentagePerUnit'], row.get('purchaseCreationUnitDollarPercentagePerUnit'))
        _add_path_text(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'standardDeviationPurchased'], row.get('standardDeviationPurchased'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'aggregateCommission'], row.get('aggregateCommission'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'avgPortfolioSecuritiesValue'], row.get('avgPortfolioSecuritiesValue'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'dailyAvgNetAssets'], row.get('dailyAvgNetAssets'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'didFundLendSecurities'], row.get('didFundLendSecurities'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundType'], row.get('fundType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'hasLineOfCredit'], row.get('hasLineOfCredit'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isAdminHiredOrTerminated'], row.get('isAdminHiredOrTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isBrokerageResearchPayment'], row.get('isBrokerageResearchPayment'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isCustodianHiredOrTerminated'], row.get('isCustodianHiredOrTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseLimitationInPlace'], row.get('isExpenseLimitationInPlace'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseReducedOrWaived'], row.get('isExpenseReducedOrWaived'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isExpenseWaivedRecoupable'], row.get('isExpenseWaivedRecoupable'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFeesWaivedRecoupable'], row.get('isFeesWaivedRecoupable'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFirstFilingByFund'], row.get('isFirstFilingByFund'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isForeignSubsidiary'], row.get('isForeignSubsidiary'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isFundSecuritiesLending'], row.get('isFundSecuritiesLending'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isInterfundBorrowing'], row.get('isInterfundBorrowing'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isInterfundLending'], row.get('isInterfundLending'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isLiquidityHiredTerminated'], row.get('isLiquidityHiredTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isNonDiversifiedCompany'], row.get('isNonDiversifiedCompany'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isPricingServiceHiredOrTerminated'], row.get('isPricingServiceHiredOrTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isShareholderServiceHiredTerminated'], row.get('isShareholderServiceHiredTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isSwingPricing'], row.get('isSwingPricing'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'isTransferAgentHiredOrTerminated'], row.get('isTransferAgentHiredOrTerminated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvFundName'], row.get('mgmtInvFundName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvLei'], row.get('mgmtInvLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mgmtInvSeriesId'], row.get('mgmtInvSeriesId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'mnthlyAvgNetAssets'], row.get('mnthlyAvgNetAssets'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'netIncomeSecuritiesLending'], row.get('netIncomeSecuritiesLending'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numAddedClass'], row.get('numAddedClass'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numAuthorizedClass'], row.get('numAuthorizedClass'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'numTerminatedClass'], row.get('numTerminatedClass'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagerType'], row.get('paymentToAgentManagerType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalAggregatePurchase'], row.get('principalAggregatePurchase'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'relyOnRuleType'], row.get('relyOnRuleType'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'coveredByInsurancePolicy'], 'isClaimFiledDuringPeriod', row.get('isClaimFiledDuringPeriod'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'coveredByInsurancePolicy'], 'isCoveredByInsurancePolicy', row.get('coveredByInsurancePolicyIsCoveredByInsurancePolicy'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'financialSupportSeriesInfo'], 'isFinancialSupportDuringPeriod', row.get('financialSupportSeriesInfoIsFinancialSupportDuringPeriod'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo'], 'isPreviousLegalProceeding', row.get('legalProceedingSeriesInfoIsPreviousLegalProceeding'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries'], 'isPaymentDividend', row.get('paymentDividendSeriesIsPaymentDividend'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries'], 'isPaymentErrorInNetAssetValue', row.get('paymentErrorSeriesIsPaymentErrorInNetAssetValue'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'previousProceedingTerminated'], 'isPreviousProceedingTerminated', row.get('previousProceedingTerminatedIsPreviousProceedingTerminated'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'registrantFamilyInvComp'], 'familyInvCompFullName', row.get('familyInvCompFullName'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'registrantFamilyInvComp'], 'isRegistrantFamilyInvComp', row.get('registrantFamilyInvCompIsRegistrantFamilyInvComp'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'releaseNumbers'], 'isExemptionFromAct', row.get('releaseNumbersIsExemptionFromAct'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo'], 'isRegistrantSubmittedMatter', row.get('securityMatterSeriesInfoIsRegistrantSubmittedMatter'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges'], 'isMaterialChange', row.get('valuationMethodsChangesIsMaterialChange'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount'], 'isRegistrantSeparateInsuranceAccount', row.get('isRegistrantSeparateInsuranceAccount'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'additionalUnitsTotalValue'], row.get('additionalUnitsTotalValue'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'newSeriesAggregateValue'], row.get('newSeriesAggregateValue'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfExistingSeries'], row.get('numOfExistingSeries'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfExistingSeriesAdditionalUnits'], row.get('numOfExistingSeriesAdditionalUnits'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfNewSeriesRegistration'], row.get('numOfNewSeriesRegistration'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'numOfSeriesCurrentProspectus'], row.get('numOfSeriesCurrentProspectus'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'totalAssetsSeries'], row.get('totalAssetsSeries'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'unitInPortfolioValue'], row.get('unitInPortfolioValue'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'registrantSeparateInsuranceAccount'], 'isRegistrantSeparateInsuranceAccount', row.get('registrantSeparateInsuranceAccountIsRegistrantSeparateInsuranceAccount'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'registrantSeparateInsuranceAccount'], 'separateAccountSeriesId', row.get('separateAccountSeriesId'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'confirmingCopyFlag'], row.get('confirmingCopyFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], row.get('overrideInternetFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], row.get('returnCopyFlag'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportClass', 'rptIncludeAllClassesFlag'], row.get('rptIncludeAllClassesFlag'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptIncludeAllSeriesFlag'], row.get('rptIncludeAllSeriesFlag'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds', 'rightsOfferingFund', 'rightsOfferingParticipationPercent'], row.get('rightsOfferingParticipationPercent'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'description'], row.get('description'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'otherSecurityDescription'], row.get('otherSecurityDescription'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'securityClassTitle'], row.get('securityClassTitle'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments'], 'isForeignSubsidiary', row.get('foreignInvestmentsIsForeignSubsidiary'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities'], 'didFundLendSecurities', row.get('fundLendSecuritiesDidFundLendSecurities'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities', 'isFundAdverselyImpacted'], row.get('isFundAdverselyImpacted'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundLendSecurities', 'isFundLiquidated'], row.get('isFundLiquidated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'fundType'], row.get('fundTypesFundType'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails'], 'isInterfundBorrowing', row.get('interfundBorrowingDetailsIsInterfundBorrowing'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails'], 'isInterfundLending', row.get('interfundLendingDetailsIsInterfundLending'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit'], 'hasLineOfCredit', row.get('lineOfCreditHasLineOfCredit'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagers', 'otherFeeDesc'], row.get('otherFeeDesc'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'paymentToAgentManagers', 'paymentToAgentManagerType'], row.get('paymentToAgentManagersPaymentToAgentManagerType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'relyOnRuleTypes', 'relyOnRuleType'], row.get('relyOnRuleTypesRelyOnRuleType'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries', 'seriesInfo'], 'seriesId', row.get('seriesInfoSeriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentDividendSeries', 'seriesInfo'], 'seriesName', row.get('seriesInfoSeriesName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoCity'], row.get('ccoCity'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoName'], row.get('ccoName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoPhone'], row.get('ccoPhone'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStreet1'], row.get('ccoStreet1'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStreet2'], row.get('ccoStreet2'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoZipCode'], row.get('ccoZipCode'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'crdNumber'], row.get('crdNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'isCcoChangedSinceLastFiling'], row.get('isCcoChangedSinceLastFiling'))
        _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'crdNumber'], row.get('directorCrdNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'directorName'], row.get('directorName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'directors', 'director', 'isDirectorInterestedPerson'], row.get('isDirectorInterestedPerson'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo', 'seriesInfo'], 'seriesId', row.get('seriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'legalProceedingSeriesInfo', 'seriesInfo'], 'seriesName', row.get('seriesName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'booksRecordsDesc'], row.get('booksRecordsDesc'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeAddress1'], row.get('officeAddress1'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeAddress2'], row.get('officeAddress2'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeCity'], row.get('officeCity'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeCountry'], row.get('officeCountry'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeName'], row.get('officeName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officePhone'], row.get('officePhone'))
        _add_path_text(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeRecordsZipCode'], row.get('officeRecordsZipCode'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries', 'seriesInfo'], 'seriesId', row.get('paymentErrorSeriesSeriesInfoSeriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'paymentErrorSeries', 'seriesInfo'], 'seriesName', row.get('paymentErrorSeriesSeriesInfoSeriesName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'isPrincipalUnderwriterAffiliatedWithRegistrant'], row.get('isPrincipalUnderwriterAffiliatedWithRegistrant'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterName'], row.get('principalUnderwriterName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterCrdNumber'], row.get('principalUnderwriterCrdNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterFileNumber'], row.get('principalUnderwriterFileNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterLei'], row.get('principalUnderwriterLei'))
        _add_path_text(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderwriterRssdId'], row.get('principalUnderwriterRssdId'))
        _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'pcaobNumber'], row.get('pcaobNumber'))
        _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantName'], row.get('publicAccountantName'))
        _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantLei'], row.get('publicAccountantLei'))
        _add_path_text(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantRssdId'], row.get('publicAccountantRssdId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'releaseNumbers', 'releaseNumberInfo'], 'releaseNumber', row.get('releaseNumber'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo', 'seriesInfo'], 'seriesId', row.get('securityMatterSeriesInfoSeriesInfoSeriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'securityMatterSeriesInfo', 'seriesInfo'], 'seriesName', row.get('securityMatterSeriesInfoSeriesInfoSeriesName'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'seriesId', row.get('terminatedSeriesInfoSeriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'seriesName', row.get('terminatedSeriesInfoSeriesName'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'terminatedSeries', 'terminatedSeriesInfo'], 'terminationDate', row.get('terminationDate'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'assetType'], row.get('assetType'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'assetTypeOtherDesc'], row.get('assetTypeOtherDesc'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'changeExplanation'], row.get('changeExplanation'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'dateOfChange'], row.get('dateOfChange'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'investmentType'], row.get('investmentType'))
        _add_path_text(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'statutoryRegulatoryBasis'], row.get('statutoryRegulatoryBasis'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'websites', 'website'], 'webpage', row.get('webpage'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'contractValueRedeemed', row.get('contractValueRedeemed'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'contractValueRedeemedSection1035', row.get('contractValueRedeemedSection1035'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'grossPremiumReceived', row.get('grossPremiumReceived'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'grossPremiumReceivedSection1035', row.get('grossPremiumReceivedSection1035'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsAffected', row.get('numContractsAffected'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsAffectedRedeemed', row.get('numContractsAffectedRedeemed'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'numContractsSold', row.get('numContractsSold'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountContractId', row.get('separateAccountContractId'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountSecurityName', row.get('separateAccountSecurityName'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'contractSecurities', 'contractSecurity'], 'separateAccountTotalAsset', row.get('separateAccountTotalAsset'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorCrdNo'], row.get('depositorCrdNo'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorLei'], row.get('depositorLei'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorName'], row.get('depositorName'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorUltimateParentname'], row.get('depositorUltimateParentname'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserStateCountry'], 'investmentAdviserState', row.get('investmentAdviserState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserStateCountry'], 'investmentAdviserCountry', row.get('investmentAdviserStateCountryInvestmentAdviserCountry'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'isUitAdminAffiliated'], row.get('isUitAdminAffiliated'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'isUitAdminSubAdmin'], row.get('isUitAdminSubAdmin'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminName'], row.get('uitAdminName'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminDescOtherNumber'], row.get('uitAdminDescOtherNumber'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminLei'], row.get('uitAdminLei'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'issuerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'issuerCredentials', 'cik'], row.get('cik'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportClass', 'classInfo', 'classId'], row.get('classId'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'includeAllClassesFlag'], row.get('includeAllClassesFlag'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'seriesId'], row.get('rptSeriesClassInfoSeriesId'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerStateCountry'], 'brokerDealerState', row.get('brokerDealerState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundName', row.get('masterFundName'))
        _add_path_text(root, ['formData', 'closedEndManagementInvestment', 'rightsOfferingFunds', 'rightsOfferingFund', 'rightsOfferingTypes', 'rightsOfferingType'], row.get('rightsOfferingType'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantCrdNo', row.get('authorizedParticipantCrdNo'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantFileNo', row.get('authorizedParticipantFileNo'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantLei', row.get('authorizedParticipantLei'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantName', row.get('authorizedParticipantName'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantPurchaseValue', row.get('authorizedParticipantPurchaseValue'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'authorizedParticipants', 'authorizedParticipant'], 'authorizedParticipantRedeemValue', row.get('authorizedParticipantRedeemValue'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'securityExchanges', 'securityExchange'], 'fundExchange', row.get('fundExchange'))
        _add_path_attr(root, ['formData', 'exchangeSeriesInfo', 'exchangeTradedFund', 'securityExchanges', 'securityExchange'], 'fundsTickerSymbol', row.get('fundsTickerSymbol'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminCountry'], row.get('adminCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminLei'], row.get('adminLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminName'], row.get('adminName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminOther'], row.get('adminOther'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminRssdId'], row.get('adminRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'idNumberDesc'], row.get('idNumberDesc'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'isAdminAffiliated'], row.get('isAdminAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'isAdminSubAdmin'], row.get('isAdminSubAdmin'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCommission'], row.get('brokerDealerCommission'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCountry'], row.get('brokerDealerCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerCrdNo'], row.get('brokerDealerCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerFileNo'], row.get('brokerDealerFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerLei'], row.get('brokerDealerLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerName'], row.get('brokerDealerName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerRssdId'], row.get('brokerDealerRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerCountry'], row.get('brokerCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerCrdNo'], row.get('brokerCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerFileNo'], row.get('brokerFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerLei'], row.get('brokerLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerName'], row.get('brokerName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerRssdId'], row.get('brokerRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'grossCommission'], row.get('grossCommission'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'collateralManagerLei', row.get('collateralManagerLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'collateralManagerName', row.get('collateralManagerName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'isCollateralManagerAffliliated', row.get('isCollateralManagerAffliliated'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'collateralManagers', 'collateralManager'], 'isCollateralManagerAffliliatedWithFund', row.get('isCollateralManagerAffliliatedWithFund'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianCountry'], row.get('custodianCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianLei'], row.get('custodianLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianName'], row.get('custodianName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianRssdId'], row.get('custodianRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodyType'], row.get('custodyType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'isCustodianAffiliated'], row.get('isCustodianAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'isSubCustodian'], row.get('isSubCustodian'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'otherCustodianDesc'], row.get('otherCustodianDesc'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments', 'foreignInvestment'], 'foreignSubsidiaryLei', row.get('foreignSubsidiaryLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'foreignInvestments', 'foreignInvestment'], 'foreignSubsidiaryName', row.get('foreignSubsidiaryName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo'], 'fundType', row.get('indexFundInfoFundType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDailyStdevAfterExpense'], row.get('indexFundReturnDailyStdevAfterExpense'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDailyStdevBeforeExpense'], row.get('indexFundReturnDailyStdevBeforeExpense'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDiffAfterExpense'], row.get('indexFundReturnDiffAfterExpense'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'indexFundReturnDiffBeforeExpense'], row.get('indexFundReturnDiffBeforeExpense'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'isIndexFundAffiliated'], row.get('isIndexFundAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'indexFundInfo', 'isIndexFundExclusive'], row.get('isIndexFundExclusive'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo'], 'fundType', row.get('masterFeederFundInfoFundType'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails', 'interfundBorrowing'], 'interfundBorrowingDaysOutstanding', row.get('interfundBorrowingDaysOutstanding'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundBorrowingDetails', 'interfundBorrowing'], 'interfundBorrowingLoanAverage', row.get('interfundBorrowingLoanAverage'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails', 'interfundLending'], 'interfundLendingDaysOutstanding', row.get('interfundLendingDaysOutstanding'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'interfundLendingDetails', 'interfundLending'], 'interfundLendingLoanAverage', row.get('interfundLendingLoanAverage'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserCountry'], row.get('investmentAdviserCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserCrdNo'], row.get('investmentAdviserCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserFileNo'], row.get('investmentAdviserFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserLei'], row.get('investmentAdviserLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserName'], row.get('investmentAdviserName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserRssdId'], row.get('investmentAdviserRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'isInvestmentAdviserHired'], row.get('isInvestmentAdviserHired'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedCrdNo'], row.get('investAdviserTerminatedCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedFileNo'], row.get('investAdviserTerminatedFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminatedLei'], row.get('investAdviserTerminatedLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investAdviserTerminationDate'], row.get('investAdviserTerminationDate'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedName'], row.get('investmentAdviserTerminatedName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'assetClassType'], row.get('assetClassType'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'isAffiliatedPerson'], row.get('isAffiliatedPerson'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityName'], row.get('liquidityName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityLei'], row.get('liquidityLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityRssdId'], row.get('liquidityRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'isPricingServiceAffiliated'], row.get('isPricingServiceAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceCountry'], row.get('pricingServiceCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceIdNumberDesc'], row.get('pricingServiceIdNumberDesc'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceLei'], row.get('pricingServiceLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceName'], row.get('pricingServiceName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceOther'], row.get('pricingServiceOther'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceRssdId'], row.get('pricingServiceRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalCountry'], row.get('principalCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalCrdNo'], row.get('principalCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalFileNo'], row.get('principalFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalLei'], row.get('principalLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalName'], row.get('principalName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalRssdId'], row.get('principalRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalTotalPurchaseSale'], row.get('principalTotalPurchaseSale'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'isSecuritiesAgentAffiliated'], row.get('isSecuritiesAgentAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'isSecurityAgentIdemnity'], row.get('isSecurityAgentIdemnity'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securitiesAgentLei'], row.get('securitiesAgentLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securitiesAgentName'], row.get('securitiesAgentName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'isShareholderServiceAgentAffiliated'], row.get('isShareholderServiceAgentAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'isShareholderServiceAgentSubshare'], row.get('isShareholderServiceAgentSubshare'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentCountry'], row.get('shareholderServiceAgentCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentLei'], row.get('shareholderServiceAgentLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentName'], row.get('shareholderServiceAgentName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentOther'], row.get('shareholderServiceAgentOther'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentRssdId'], row.get('shareholderServiceAgentRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceIdNumberDesc'], row.get('shareholderServiceIdNumberDesc'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingClassId', row.get('sharesOutstandingClassId'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingClassName', row.get('sharesOutstandingClassName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'sharesOutstandings', 'sharesOutstanding'], 'sharesOutstandingTickerSymbol', row.get('sharesOutstandingTickerSymbol'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'isSubAdviserAffiliated'], row.get('isSubAdviserAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'isSubAdviserHired'], row.get('isSubAdviserHired'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserCountry'], row.get('subAdviserCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserCrdNo'], row.get('subAdviserCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserFileNo'], row.get('subAdviserFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserLei'], row.get('subAdviserLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserName'], row.get('subAdviserName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserRssdId'], row.get('subAdviserRssdId'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedCountry'], row.get('subAdviserTerminatedCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedCrdNo'], row.get('subAdviserTerminatedCrdNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedFileNo'], row.get('subAdviserTerminatedFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedLei'], row.get('subAdviserTerminatedLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedName'], row.get('subAdviserTerminatedName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminationDate'], row.get('subAdviserTerminationDate'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'isTransferAgentAffiliated'], row.get('isTransferAgentAffiliated'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'isTransferAgentSubAgent'], row.get('isTransferAgentSubAgent'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentCountry'], row.get('transferAgentCountry'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentFileNo'], row.get('transferAgentFileNo'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentLei'], row.get('transferAgentLei'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentName'], row.get('transferAgentName'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentRssdId'], row.get('transferAgentRssdId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStateCountry'], 'ccoCountry', row.get('ccoCountry'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoStateCountry'], 'ccoState', row.get('ccoState'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeStateCountry'], 'officeCountry', row.get('officeStateCountryOfficeCountry'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'locationBooksRecords', 'locationBooksRecord', 'officeStateCountry'], 'officeState', row.get('officeState'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderWriterStateCountry'], 'principalUnderWriterCountry', row.get('principalUnderWriterCountry'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'principalUnderwriters', 'principalUnderwriter', 'principalUnderWriterStateCountry'], 'principalUnderWriterState', row.get('principalUnderWriterState'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantStateCountry'], 'publicAccountantCountry', row.get('publicAccountantCountry'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'publicAccountants', 'publicAccountant', 'publicAccountantStateCountry'], 'publicAccountantState', row.get('publicAccountantState'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorStateCountry'], 'depositorCountry', row.get('depositorCountry'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'depositors', 'depositor', 'depositorStateCountry'], 'depositorState', row.get('depositorState'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'seriesCIKs', 'seriesCIK'], 'cik', row.get('seriesCIKCik'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorCrdNo'], row.get('sponsorCrdNo'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorLei'], row.get('sponsorLei'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorName'], row.get('sponsorName'))
        _add_path_text(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeName'], row.get('trusteeName'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminStateCountry'], 'uitAdminCountry', row.get('uitAdminCountry'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'uitAdmins', 'uitAdmin', 'uitAdminStateCountry'], 'uitAdminState', row.get('uitAdminState'))
        _add_path_text(root, ['headerData', 'seriesClass', 'reportSeriesClass', 'rptSeriesClassInfo', 'classInfo', 'classId'], row.get('classInfoClassId'))
        _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'commonStocks', 'commonStock'], 'commonStockExchange', row.get('commonStockExchange'))
        _add_path_attr(root, ['formData', 'closedEndManagementInvestment', 'securityRelatedItems', 'securityRelatedItem', 'commonStocks', 'commonStock'], 'commonStockTickerSymbol', row.get('commonStockTickerSymbol'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminStateCountry'], 'adminCountry', row.get('adminStateCountryAdminCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'admins', 'admin', 'adminStateCountry'], 'adminState', row.get('adminState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokerDealers', 'brokerDealer', 'brokerDealerStateCountry'], 'brokerDealerCountry', row.get('brokerDealerStateCountryBrokerDealerCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerStateCountry'], 'brokerCountry', row.get('brokerStateCountryBrokerCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'brokers', 'broker', 'brokerStateCountry'], 'brokerState', row.get('brokerState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianStateCountry'], 'custodianCountry', row.get('custodianStateCountryCustodianCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'custodians', 'custodian', 'custodianStateCountry'], 'custodianState', row.get('custodianState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'feederFundName', row.get('feederFundName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundFileNo', row.get('regFeederFundFileNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundLei', row.get('regFeederFundLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'regFeederFundSeriesIdNo', row.get('regFeederFundSeriesIdNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'unregFeederFileNo', row.get('unregFeederFileNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'feederFunds'], 'unregFeederFundLei', row.get('unregFeederFundLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundFileNo', row.get('masterFundFileNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundLei', row.get('masterFundLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'fundTypes', 'masterFeederFundInfo', 'masterFunds'], 'masterFundSECFileNo', row.get('masterFundSECFileNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserHired'], 'isInvestmentAdviserHired', row.get('investmentAdviserHiredIsInvestmentAdviserHired'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisers', 'investmentAdviser', 'investmentAdviserHired', 'investmentAdviserStartDate'], row.get('investmentAdviserStartDate'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedStateCountry'], 'investmentAdviserTerminatedCountry', row.get('investmentAdviserTerminatedCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'investmentAdvisersTerminated', 'investmentAdviserTerminated', 'investmentAdviserTerminatedStateCountry'], 'investmentAdviserTerminatedState', row.get('investmentAdviserTerminatedState'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'isCreditLineCommitted'], row.get('isCreditLineCommitted'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'isCreditLineUsed'], row.get('isCreditLineUsed'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'lineOfCreditSize'], row.get('lineOfCreditSize'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityStateCountry'], 'liquidityCountry', row.get('liquidityCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'liquidityClassifications', 'liquidityClassificationService', 'liquidityStateCountry'], 'liquidityState', row.get('liquidityState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceStateCountry'], 'pricingServiceCountry', row.get('pricingServiceStateCountryPricingServiceCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'pricingServices', 'pricingService', 'pricingServiceStateCountry'], 'pricingServiceState', row.get('pricingServiceState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalStateCountry'], 'principalCountry', row.get('principalStateCountryPrincipalCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'principalTransactions', 'principalTransaction', 'principalStateCountry'], 'principalState', row.get('principalState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity'], 'isSecurityAgentIdemnity', row.get('securityAgentIdemnityIsSecurityAgentIdemnity'))
        _add_path_text(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'didIndemnificationRights'], row.get('didIndemnificationRights'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentStateCountry'], 'shareholderServiceAgentCountry', row.get('shareholderServiceAgentStateCountryShareholderServiceAgentCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'shareholderServicingAgents', 'shareholderServicingAgent', 'shareholderServiceAgentStateCountry'], 'shareholderServiceAgentState', row.get('shareholderServiceAgentState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserHired'], 'isSubAdviserHired', row.get('subAdviserHiredIsSubAdviserHired'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserHired'], 'subAdviserStartDate', row.get('subAdviserStartDate'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserStateCountry'], 'subAdviserCountry', row.get('subAdviserStateCountrySubAdviserCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisers', 'subAdviser', 'subAdviserStateCountry'], 'subAdviserState', row.get('subAdviserState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedStateCountry'], 'subAdviserTerminatedCountry', row.get('subAdviserTerminatedStateCountrySubAdviserTerminatedCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'subAdvisersTerminated', 'subAdviserTerminated', 'subAdviserTerminatedStateCountry'], 'subAdviserTerminatedState', row.get('subAdviserTerminatedState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentStateCountry'], 'transferAgentCountry', row.get('transferAgentStateCountryTransferAgentCountry'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'transferAgents', 'transferAgent', 'transferAgentStateCountry'], 'transferAgentState', row.get('transferAgentState'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoEmployers', 'ccoEmployer'], 'ccoEmployerId', row.get('ccoEmployerId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'chiefComplianceOfficers', 'chiefComplianceOfficer', 'ccoEmployers', 'ccoEmployer'], 'ccoEmployerName', row.get('ccoEmployerName'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'directors', 'director', 'fileNumbers', 'fileNumberInfo'], 'fileNumber', row.get('fileNumberInfoFileNumber'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'valuationMethodsChangeSeries', 'seriesInfo'], 'seriesId', row.get('valuationMethodsChangeSeriesSeriesInfoSeriesId'))
        _add_path_attr(root, ['formData', 'registrantInfo', 'valuationMethodsChanges', 'valuationMethodsChange', 'valuationMethodsChangeSeries', 'seriesInfo'], 'seriesName', row.get('valuationMethodsChangeSeriesSeriesInfoSeriesName'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorStateCountry'], 'sponsorCountry', row.get('sponsorCountry'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'sponsors', 'sponsor', 'sponsorStateCountry'], 'sponsorState', row.get('sponsorState'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeStateCountry'], 'trusteeCountry', row.get('trusteeCountry'))
        _add_path_attr(root, ['formData', 'unitInvestmentTrust', 'notRegistrantSeparateInsuranceAccount', 'trustees', 'trustee', 'trusteeStateCountry'], 'trusteeState', row.get('trusteeState'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'averageCreditLineUsed', row.get('averageCreditLineUsed'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'daysCreditUsed', row.get('daysCreditUsed'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'creditLineUsed'], 'isCreditLineUsed', row.get('creditLineUsedIsCreditLineUsed'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType'], 'creditType', row.get('creditType'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'soleCreditType'], 'creditType', row.get('soleCreditTypeCreditType'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'lineOfCreditInstitutions', 'lineOfCreditInstitution'], 'creditInstitutionName', row.get('creditInstitutionName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType', 'creditUser'], 'fundName', row.get('creditUserFundName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'lineOfCredit', 'lineOfCreditDetails', 'lineOfCreditDetail', 'sharedCreditType', 'creditUser'], 'secFileNo', row.get('secFileNo'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderLei', row.get('idemnityProviderLei'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderName', row.get('idemnityProviderName'))
        _add_path_attr(root, ['formData', 'managementInvestmentQuestionSeriesInfo', 'managementInvestmentQuestion', 'securityLendings', 'securityLending', 'securityAgentIdemnity', 'idemnityProviders', 'idemnityProvider'], 'idemnityProviderRssdId', row.get('idemnityProviderRssdId'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')





