import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_nmfp(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/nmfp')
    root.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    root.set('xmlns:dei', 'http://www.sec.gov/edgar/dei')
    root.set('xmlns:invest', 'http://www.sec.gov/edgar/invest')
    root.set('xmlns:part1', 'http://www.sec.gov/edgar/nmfpfund')
    root.set('xmlns:part2', 'http://www.sec.gov/edgar/nmfpsecurities')
    root.set('xmlns:ratings', 'http://www.sec.gov/edgar/ratings')
    root.set('xmlns:rr', 'http://www.sec.gov/edgar/rr')
    root.set('xmlns:sccom', 'http://www.sec.gov/edgar/sccommon')
    root.set('xmlns:state', 'http://www.sec.gov/edgar/statecodes')
    root.set('xmlns:us-gaap', 'http://www.sec.gov/edgar/us-gaap')
    for row in normalized_rows:
        _add_path_text(root, ['seriesLevelInformation', 'AvailableForSaleSecuritiesAmortizedCost'], row.get('availableForSaleSecuritiesAmortizedCost'))
        _add_path_text(root, ['DocumentPeriodEndDate'], row.get('documentPeriodEndDate'))
        _add_path_text(root, ['EntityCentralIndexKey'], row.get('entityCentralIndexKey'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentMaturityDate'], row.get('investmentMaturityDate'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentOwnedAtFairValue'], row.get('investmentOwnedAtFairValue'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentOwnedBalancePrincipalAmount'], row.get('investmentOwnedBalancePrincipalAmount'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentOwnedPercentOfNetAssets'], row.get('investmentOwnedPercentOfNetAssets'))
        _add_path_text(root, ['totalClassesInSeries'], row.get('totalClassesInSeries'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'doesSecurityHaveDemandFeature'], row.get('doesSecurityHaveDemandFeature'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'doesSecurityHaveEnhancementsOnWhichFundRelying'], row.get('doesSecurityHaveEnhancementsOnWhichFundRelying'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'finalLegalInvestmentMaturityDate'], row.get('finalLegalInvestmentMaturityDate'))
        _add_path_text(root, ['hasFundAcquiredOrMergedWithAnotherFundSinceLastFiling'], row.get('hasFundAcquiredOrMergedWithAnotherFundSinceLastFiling'))
        _add_path_text(root, ['isFundLiquidating'], row.get('isFundLiquidating'))
        _add_path_text(root, ['isFundMergingWithOrBeingAcquiredByAnotherFund'], row.get('isFundMergingWithOrBeingAcquiredByAnotherFund'))
        _add_path_text(root, ['isThisElectronicCopyOfPaperFormat'], row.get('isThisElectronicCopyOfPaperFormat'))
        _add_path_text(root, ['isThisFinalFiling'], row.get('isThisFinalFiling'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'isThisIlliquidSecurity'], row.get('isThisIlliquidSecurity'))
        _add_path_text(root, ['liveTestFlag'], row.get('liveTestFlag'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'rating'], row.get('rating'))
        _add_path_text(root, ['seriesId'], row.get('seriesId'))
        _add_path_text(root, ['submissionType'], row.get('submissionType'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'valueOfSecurityExcludingValueOfCapitalSupportAgreement'], row.get('valueOfSecurityExcludingValueOfCapitalSupportAgreement'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'AssetsSoldUnderAgreementsToRepurchaseCarryingAmounts'], row.get('assetsSoldUnderAgreementsToRepurchaseCarryingAmounts'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'CR'], row.get('cR'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'CashCollateralForBorrowedSecurities'], row.get('cashCollateralForBorrowedSecurities'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'InvestmentIssuer'], row.get('repurchaseAgreementInvestmentIssuer'))
        _add_path_text(root, ['seriesLevelInformation', 'InvestmentTypeDomain'], row.get('investmentTypeDomain'))
        _add_path_text(root, ['seriesLevelInformation', 'AssetsNet'], row.get('assetsNet'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'CUSIPMember'], row.get('cUSIPMember'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentIssuer'], row.get('investmentIssuer'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentTitle'], row.get('investmentTitle'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'doesSecurityHaveGuarantee'], row.get('doesSecurityHaveGuarantee'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'isFundTreatingAsAcquisitionUnderlyingSecurities'], row.get('isFundTreatingAsAcquisitionUnderlyingSecurities'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'AvailableForSaleSecuritiesAmortizedCost'], row.get('scheduleOfPortfolioSecuritiesAvailableForSaleSecuritiesAmortizedCost'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentTypeDomain'], row.get('scheduleOfPortfolioSecuritiesInvestmentTypeDomain'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'guarantorList', 'guarantor', 'O'], row.get('o'))
        _add_path_text(root, ['seriesLevelInformation', 'OtherAssets'], row.get('otherAssets'))
        _add_path_text(root, ['seriesLevelInformation', 'ContainedFileInformationFileNumber'], row.get('containedFileInformationFileNumber'))
        _add_path_text(root, ['seriesLevelInformation', 'Liabilities'], row.get('liabilities'))
        _add_path_text(root, ['seriesLevelInformation', 'MoneyMarketSevenDayYield'], row.get('moneyMarketSevenDayYield'))
        _add_path_text(root, ['seriesLevelInformation', 'dollarWeightedAverageLifeMaturity'], row.get('dollarWeightedAverageLifeMaturity'))
        _add_path_text(root, ['seriesLevelInformation', 'dollarWeightedAveragePortfolioMaturity'], row.get('dollarWeightedAveragePortfolioMaturity'))
        _add_path_text(root, ['seriesLevelInformation', 'isThisFeederFund'], row.get('isThisFeederFund'))
        _add_path_text(root, ['seriesLevelInformation', 'isThisMasterFund'], row.get('isThisMasterFund'))
        _add_path_text(root, ['seriesLevelInformation', 'isThisSeriesPrimarilyUsedToFundInsuranceCompanySeperateAccounts'], row.get('isThisSeriesPrimarilyUsedToFundInsuranceCompanySeperateAccounts'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'InvestmentMaturityDate', 'date'], row.get('date'))
        _add_path_text(root, ['seriesLevelInformation', 'feederFundList', 'feederFund', 'ContainedFileInformationFileNumber'], row.get('feederFundContainedFileInformationFileNumber'))
        _add_path_text(root, ['seriesLevelInformation', 'feederFundList', 'feederFund', 'EntityCentralIndexKey'], row.get('feederFundEntityCentralIndexKey'))
        _add_path_text(root, ['seriesLevelInformation', 'feederFundList', 'feederFund', 'seriesIdentifier'], row.get('feederFundSeriesIdentifier'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'classId'], row.get('classId'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'grossRedemptionsForMonthEnded'], row.get('grossRedemptionsForMonthEnded'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'grossSubscriptionsForMonthEnded'], row.get('grossSubscriptionsForMonthEnded'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'minInitialInvestment'], row.get('minInitialInvestment'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'netAssetValuePerShare'], row.get('netAssetValuePerShare'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'netAssetsOfClass'], row.get('netAssetsOfClass'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'netShareholderFlowActivityForMonthEnded'], row.get('netShareholderFlowActivityForMonthEnded'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'sevenDayNetYield'], row.get('sevenDayNetYield'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'designatedNRSROList', 'designatedNRSRO', 'RAN'], row.get('rAN'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'InvestmentTypeDomain'], row.get('repurchaseAgreementInvestmentTypeDomain'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'categoryOfInvestmentDesc'], row.get('categoryOfInvestmentDesc'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'EntityCentralIndexKey'], row.get('scheduleOfPortfolioSecuritiesEntityCentralIndexKey'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentIdentifier'], row.get('investmentIdentifier'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'InvestmentOwnedInvestmentAdditionalInformation'], row.get('investmentOwnedInvestmentAdditionalInformation'))
        _add_path_text(root, ['seriesLevelInformation', 'administratorList', 'administrator'], row.get('administrator'))
        _add_path_text(root, ['seriesLevelInformation', 'independentPublicAccountant', 'city'], row.get('city'))
        _add_path_text(root, ['seriesLevelInformation', 'independentPublicAccountant', 'name'], row.get('name'))
        _add_path_text(root, ['seriesLevelInformation', 'independentPublicAccountant', 'state'], row.get('state'))
        _add_path_text(root, ['seriesLevelInformation', 'seriesShadowPrice', 'dateCalculatedFornetValuePerShareExcludingCapitalSupportAgreement'], row.get('dateCalculatedFornetValuePerShareExcludingCapitalSupportAgreement'))
        _add_path_text(root, ['seriesLevelInformation', 'seriesShadowPrice', 'dateCalculatedFornetValuePerShareIncludingCapitalSupportAgreement'], row.get('dateCalculatedFornetValuePerShareIncludingCapitalSupportAgreement'))
        _add_path_text(root, ['seriesLevelInformation', 'seriesShadowPrice', 'netValuePerShareExcludingCapitalSupportAgreement'], row.get('netValuePerShareExcludingCapitalSupportAgreement'))
        _add_path_text(root, ['seriesLevelInformation', 'seriesShadowPrice', 'netValuePerShareIncludingCapitalSupportAgreement'], row.get('netValuePerShareIncludingCapitalSupportAgreement'))
        _add_path_text(root, ['seriesLevelInformation', 'masterFund', 'EntityCentralIndexKey'], row.get('masterFundEntityCentralIndexKey'))
        _add_path_text(root, ['seriesLevelInformation', 'masterFund', 'EntityRegistrantName'], row.get('entityRegistrantName'))
        _add_path_text(root, ['seriesLevelInformation', 'masterFund', 'seriesIdentifier'], row.get('seriesIdentifier'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'classShadowPrice', 'netAssetValuePerShareExcludingCapitalSupportAgreement', 'dateAsOfWhichValueWasCalculated'], row.get('dateAsOfWhichValueWasCalculated'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'classShadowPrice', 'netAssetValuePerShareExcludingCapitalSupportAgreement', 'value'], row.get('value'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'demandFeatureIssuerList', 'demandFeatureIssuer', 'InvestmentIssuer'], row.get('demandFeatureIssuerInvestmentIssuer'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'enhancementsList', 'enhancement', 'typeOfEnhancement'], row.get('typeOfEnhancement'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'categoryOfInvestmentDesc'], row.get('repurchaseAgreementCategoryOfInvestmentDesc'))
        _add_path_text(root, ['seriesLevelInformation', 'investmentAdviserList', 'adviser', 'adviserFileNumber'], row.get('adviserFileNumber'))
        _add_path_text(root, ['seriesLevelInformation', 'investmentAdviserList', 'adviser', 'adviserName'], row.get('adviserName'))
        _add_path_text(root, ['seriesLevelInformation', 'transferAgentList', 'transferAgent', 'EntityCentralIndexKey'], row.get('transferAgentEntityCentralIndexKey'))
        _add_path_text(root, ['seriesLevelInformation', 'transferAgentList', 'transferAgent', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['seriesLevelInformation', 'transferAgentList', 'transferAgent', 'name'], row.get('transferAgentName'))
        _add_path_text(root, ['seriesLevelInformation', 'feederFundList', 'feederFund', 'EntityRegistrantName'], row.get('feederFundEntityRegistrantName'))
        _add_path_text(root, ['seriesLevelInformation', 'subAdviserList', 'subAdviser', 'adviserFileNumber'], row.get('subAdviserAdviserFileNumber'))
        _add_path_text(root, ['seriesLevelInformation', 'subAdviserList', 'subAdviser', 'adviserName'], row.get('subAdviserAdviserName'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'classShadowPrice', 'netAssetValuePerShareIncludingCapitalSupportAgreement', 'dateAsOfWhichValueWasCalculated'], row.get('netAssetValuePerShareIncludingCapitalSupportAgreementDateAsOfWhichValueWasCalculated'))
        _add_path_text(root, ['classLevelInformationList', 'classLevelInformation', 'classShadowPrice', 'netAssetValuePerShareIncludingCapitalSupportAgreement', 'value'], row.get('netAssetValuePerShareIncludingCapitalSupportAgreementValue'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'designatedNRSROList', 'designatedNRSRO', 'R'], row.get('r'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'demandFeatureIssuerList', 'demandFeatureIssuer', 'NRSRORatingList', 'NRSROSRating', 'RAN'], row.get('nRSROSRatingRAN'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'guarantorList', 'guarantor', 'NRSRORatingList', 'NRSRORating', 'RAN'], row.get('nRSRORatingRAN'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'enhancementsList', 'enhancement', 'enhancementProviderList', 'Provider', 'enhancementProvider'], row.get('enhancementProvider'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'demandFeatureIssuerList', 'demandFeatureIssuer', 'NRSRORatingList', 'NRSROSRating', 'R'], row.get('nRSROSRatingR'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'guarantorList', 'guarantor', 'NRSRORatingList', 'NRSRORating', 'R'], row.get('nRSRORatingR'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'InvestmentMaturityDate', 'dateRange', 'from'], row.get('from'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'repurchaseAgreementList', 'RepurchaseAgreement', 'InvestmentMaturityDate', 'dateRange', 'to'], row.get('to'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'enhancementsList', 'enhancement', 'enhancementProviderList', 'Provider', 'NRSRORatingList', 'NRSRORating', 'RAN'], row.get('nRSRORatingListNRSRORatingRAN'))
        _add_path_text(root, ['scheduleOfPortfolioSecuritiesList', 'scheduleOfPortfolioSecurities', 'enhancementsList', 'enhancement', 'enhancementProviderList', 'Provider', 'NRSRORatingList', 'NRSRORating', 'R'], row.get('nRSRORatingListNRSRORatingR'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




