import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_nmfp1(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/nmfp1')
    root.set('xmlns:common', 'http://www.sec.gov/edgar/common')
    root.set('xmlns:nmfp1common', 'http://www.sec.gov/edgar/nmfp1common')
    root.set('xmlns:statecodes', 'http://www.sec.gov/edgar/statecodes')
    root.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
    for row in normalized_rows:
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'classesId'], row.get('classesId'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'minInitialInvestment'], row.get('minInitialInvestment'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'nameOfPersonDescExpensePay'], row.get('nameOfPersonDescExpensePay'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetsOfClass'], row.get('netAssetsOfClass'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'numberOfSharesOutstanding'], row.get('numberOfSharesOutstanding'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'personPayForFundFlag'], row.get('personPayForFundFlag'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'sevenDayNetYield'], row.get('sevenDayNetYield'))
        _add_path_text(root, ['formData', 'generalInfo', 'cik'], row.get('cik'))
        _add_path_text(root, ['formData', 'generalInfo', 'finalFilingFlag'], row.get('finalFilingFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'fundAcqrdOrMrgdWthAnthrFlag'], row.get('fundAcqrdOrMrgdWthAnthrFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'fundLiquidatingFlag'], row.get('fundLiquidatingFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'fundMrgOrAcqrdByOthrFlag'], row.get('fundMrgOrAcqrdByOthrFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'registrantLEIId'], row.get('registrantLEIId'))
        _add_path_text(root, ['formData', 'generalInfo', 'reportDate'], row.get('reportDate'))
        _add_path_text(root, ['formData', 'generalInfo', 'seriesId'], row.get('seriesId'))
        _add_path_text(root, ['formData', 'generalInfo', 'totalShareClassesInSeries'], row.get('totalShareClassesInSeries'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'CUSIPMember'], row.get('cUSIPMember'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'ISINId'], row.get('iSINId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'LEIID'], row.get('lEIID'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'briefDescription'], row.get('briefDescription'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'cik'], row.get('scheduleOfPortfolioSecuritiesInfoCik'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'dailyLiquidAssetSecurityFlag'], row.get('dailyLiquidAssetSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'excludingValueOfAnySponsorSupport'], row.get('excludingValueOfAnySponsorSupport'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'explanatoryNotes'], row.get('explanatoryNotes'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'finalLegalInvestmentMaturityDate'], row.get('finalLegalInvestmentMaturityDate'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'fundAcqstnUndrlyngSecurityFlag'], row.get('fundAcqstnUndrlyngSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'illiquidSecurityFlag'], row.get('illiquidSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'includingValueOfAnySponsorSupport'], row.get('includingValueOfAnySponsorSupport'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentCategory'], row.get('investmentCategory'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentMaturityDateWAL'], row.get('investmentMaturityDateWAL'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentMaturityDateWAM'], row.get('investmentMaturityDateWAM'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'nameOfIssuer'], row.get('nameOfIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'otherUniqueId'], row.get('otherUniqueId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'percentageOfMoneyMarketFundNetAssets'], row.get('percentageOfMoneyMarketFundNetAssets'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityCategorizedAtLevel3Flag'], row.get('securityCategorizedAtLevel3Flag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityDemandFeatureFlag'], row.get('securityDemandFeatureFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityEligibilityFlag'], row.get('securityEligibilityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityEnhancementsFlag'], row.get('securityEnhancementsFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityGuaranteeFlag'], row.get('securityGuaranteeFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityRated'], row.get('securityRated'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'titleOfIssuer'], row.get('titleOfIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'totalValueOfFundPosition'], row.get('totalValueOfFundPosition'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'weeklyLiquidAssetSecurityFlag'], row.get('weeklyLiquidAssetSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'yieldOfTheSecurityAsOfReportingDate'], row.get('yieldOfTheSecurityAsOfReportingDate'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'amortizedCostPortfolioSecurities'], row.get('amortizedCostPortfolioSecurities'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'averageLifeMaturity'], row.get('averageLifeMaturity'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'averagePortfolioMaturity'], row.get('averagePortfolioMaturity'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'cash'], row.get('cash'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFundFlag'], row.get('feederFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'fundExemptRetailFlag'], row.get('fundExemptRetailFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFundFlag'], row.get('masterFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'moneyMarketFundCategory'], row.get('moneyMarketFundCategory'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetOfSeries'], row.get('netAssetOfSeries'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'numberOfSharesOutstanding'], row.get('seriesLevelInfoNumberOfSharesOutstanding'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'securitiesActFileNumber'], row.get('securitiesActFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'seriesFundInsuCmpnySepAccntFlag'], row.get('seriesFundInsuCmpnySepAccntFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'sevenDayGrossYield'], row.get('sevenDayGrossYield'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'stablePricePerShare'], row.get('stablePricePerShare'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueLiabilities'], row.get('totalValueLiabilities'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueOtherAssets'], row.get('totalValueOtherAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValuePortfolioSecurities'], row.get('totalValuePortfolioSecurities'))
        _add_path_text(root, ['formData', 'signature', 'nameOfSigningOfficer'], row.get('nameOfSigningOfficer'))
        _add_path_text(root, ['formData', 'signature', 'registrant'], row.get('registrant'))
        _add_path_text(root, ['formData', 'signature', 'signature'], row.get('signature'))
        _add_path_text(root, ['formData', 'signature', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['formData', 'signature', 'titleOfSigningOfficer'], row.get('titleOfSigningOfficer'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek1', 'weeklyGrossRedemptions'], row.get('weeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek1', 'weeklyGrossSubscriptions'], row.get('weeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek2', 'weeklyGrossRedemptions'], row.get('fridayWeek2WeeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek2', 'weeklyGrossSubscriptions'], row.get('fridayWeek2WeeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek3', 'weeklyGrossRedemptions'], row.get('fridayWeek3WeeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek3', 'weeklyGrossSubscriptions'], row.get('fridayWeek3WeeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek4', 'weeklyGrossRedemptions'], row.get('fridayWeek4WeeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek4', 'weeklyGrossSubscriptions'], row.get('fridayWeek4WeeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek5', 'weeklyGrossRedemptions'], row.get('fridayWeek5WeeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'fridayWeek5', 'weeklyGrossSubscriptions'], row.get('fridayWeek5WeeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetPerShare', 'fridayWeek1'], row.get('fridayWeek1'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetPerShare', 'fridayWeek2'], row.get('fridayWeek2'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetPerShare', 'fridayWeek3'], row.get('fridayWeek3'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetPerShare', 'fridayWeek4'], row.get('fridayWeek4'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetPerShare', 'fridayWeek5'], row.get('fridayWeek5'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'totalForTheMonthReported', 'weeklyGrossRedemptions'], row.get('totalForTheMonthReportedWeeklyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'totalForTheMonthReported', 'weeklyGrossSubscriptions'], row.get('totalForTheMonthReportedWeeklyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'cik'], row.get('feederFundCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'seriesId'], row.get('feederFundSeriesId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'NRSRO', 'nameOfNRSRO'], row.get('nameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'NRSRO', 'rating'], row.get('rating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'amountProvidedByDemandFeatureIssuer'], row.get('amountProvidedByDemandFeatureIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureConditionalFlag'], row.get('demandFeatureConditionalFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'identityOfDemandFeatureIssuer'], row.get('identityOfDemandFeatureIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'remainingPeriodDemandFeature'], row.get('remainingPeriodDemandFeature'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'designatedNrsro', 'creditRatingDesignatedNRSRO'], row.get('creditRatingDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'designatedNrsro', 'nameOfDesignatedNRSRO'], row.get('nameOfDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'amountProvidedByEnhancement'], row.get('amountProvidedByEnhancement'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'identityOfTheEnhancementProvider'], row.get('identityOfTheEnhancementProvider'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'typeOfEnhancement'], row.get('typeOfEnhancement'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'amountProvidedByGuarantor'], row.get('amountProvidedByGuarantor'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'identityOfTheGuarantor'], row.get('identityOfTheGuarantor'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'repurchaseAgreementOpenFlag'], row.get('repurchaseAgreementOpenFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'administrator', 'administratorName'], row.get('administratorName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'adviser', 'adviserFileNumber'], row.get('adviserFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'adviser', 'adviserName'], row.get('adviserName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'name'], row.get('name'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'name'], row.get('indpPubAccountantName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'stateCountry'], row.get('stateCountry'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'cik'], row.get('masterFeederFundCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'name'], row.get('masterFeederFundName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'seriesId'], row.get('masterFeederFundSeriesId'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetValue', 'fridayWeek1'], row.get('netAssetValueFridayWeek1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetValue', 'fridayWeek2'], row.get('netAssetValueFridayWeek2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetValue', 'fridayWeek3'], row.get('netAssetValueFridayWeek3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetValue', 'fridayWeek4'], row.get('netAssetValueFridayWeek4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetValue', 'fridayWeek5'], row.get('netAssetValueFridayWeek5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayDay1'], row.get('fridayDay1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayDay2'], row.get('fridayDay2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayDay3'], row.get('fridayDay3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayDay4'], row.get('fridayDay4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayDay5'], row.get('fridayDay5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayWeek1'], row.get('percentageDailyLiquidAssetsFridayWeek1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayWeek2'], row.get('percentageDailyLiquidAssetsFridayWeek2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayWeek3'], row.get('percentageDailyLiquidAssetsFridayWeek3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayWeek4'], row.get('percentageDailyLiquidAssetsFridayWeek4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageDailyLiquidAssets', 'fridayWeek5'], row.get('percentageDailyLiquidAssetsFridayWeek5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageWeeklyLiquidAssets', 'fridayWeek1'], row.get('percentageWeeklyLiquidAssetsFridayWeek1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageWeeklyLiquidAssets', 'fridayWeek2'], row.get('percentageWeeklyLiquidAssetsFridayWeek2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageWeeklyLiquidAssets', 'fridayWeek3'], row.get('percentageWeeklyLiquidAssetsFridayWeek3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageWeeklyLiquidAssets', 'fridayWeek4'], row.get('percentageWeeklyLiquidAssetsFridayWeek4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'percentageWeeklyLiquidAssets', 'fridayWeek5'], row.get('percentageWeeklyLiquidAssetsFridayWeek5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'subAdviser', 'adviserFileNumber'], row.get('subAdviserAdviserFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'subAdviser', 'adviserName'], row.get('subAdviserAdviserName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayDay1'], row.get('totalValueDailyLiquidAssetsFridayDay1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayDay2'], row.get('totalValueDailyLiquidAssetsFridayDay2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayDay3'], row.get('totalValueDailyLiquidAssetsFridayDay3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayDay4'], row.get('totalValueDailyLiquidAssetsFridayDay4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayDay5'], row.get('totalValueDailyLiquidAssetsFridayDay5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayWeek1'], row.get('totalValueDailyLiquidAssetsFridayWeek1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayWeek2'], row.get('totalValueDailyLiquidAssetsFridayWeek2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayWeek3'], row.get('totalValueDailyLiquidAssetsFridayWeek3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayWeek4'], row.get('totalValueDailyLiquidAssetsFridayWeek4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueDailyLiquidAssets', 'fridayWeek5'], row.get('totalValueDailyLiquidAssetsFridayWeek5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueWeeklyLiquidAssets', 'fridayWeek1'], row.get('totalValueWeeklyLiquidAssetsFridayWeek1'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueWeeklyLiquidAssets', 'fridayWeek2'], row.get('totalValueWeeklyLiquidAssetsFridayWeek2'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueWeeklyLiquidAssets', 'fridayWeek3'], row.get('totalValueWeeklyLiquidAssetsFridayWeek3'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueWeeklyLiquidAssets', 'fridayWeek4'], row.get('totalValueWeeklyLiquidAssetsFridayWeek4'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueWeeklyLiquidAssets', 'fridayWeek5'], row.get('totalValueWeeklyLiquidAssetsFridayWeek5'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'cik'], row.get('transferAgentCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'fileNumber'], row.get('transferAgentFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'name'], row.get('transferAgentName'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureRatingOrNRSRO', 'nameOfNRSRO'], row.get('demandFeatureRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureRatingOrNRSRO', 'rating'], row.get('demandFeatureRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'designatedNRSRODemandFeature', 'creditRatingDesignatedNRSRO'], row.get('designatedNRSRODemandFeatureCreditRatingDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'designatedNRSRODemandFeature', 'nameOfDesignatedNRSRO'], row.get('designatedNRSRODemandFeatureNameOfDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'designatedNRSROEnhancement', 'creditRatingDesignatedNRSRO'], row.get('designatedNRSROEnhancementCreditRatingDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'designatedNRSROEnhancement', 'nameOfDesignatedNRSRO'], row.get('designatedNRSROEnhancementNameOfDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'enhancementRatingOrNRSRO', 'nameOfNRSRO'], row.get('enhancementRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'enhancementRatingOrNRSRO', 'rating'], row.get('enhancementRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'designatedNRSROGuarantor', 'creditRatingDesignatedNRSRO'], row.get('designatedNRSROGuarantorCreditRatingDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'designatedNRSROGuarantor', 'nameOfDesignatedNRSRO'], row.get('designatedNRSROGuarantorNameOfDesignatedNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'guarantorRatingOrNRSRO', 'nameOfNRSRO'], row.get('guarantorRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'guarantorRatingOrNRSRO', 'rating'], row.get('guarantorRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'LEIID'], row.get('collateralIssuersLEIID'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'couponOrYield'], row.get('couponOrYield'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'ctgryInvestmentsRprsntsCollateral'], row.get('ctgryInvestmentsRprsntsCollateral'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'nameOfCollateralIssuer'], row.get('nameOfCollateralIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'otherInstrumentBriefDesc'], row.get('otherInstrumentBriefDesc'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'principalAmountToTheNearestCent'], row.get('principalAmountToTheNearestCent'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'valueOfCollateralToTheNearestCent'], row.get('valueOfCollateralToTheNearestCent'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('filerCredentialsCik'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'date'], row.get('date'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'dateRange', 'from'], row.get('from'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'dateRange', 'to'], row.get('to'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




