import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_nmfp3(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/nmfp3')
    root.set('xmlns:ns3', 'http://www.sec.gov/edgar/nmfp3common')
    root.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
    for row in normalized_rows:
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'classFullName'], row.get('classFullName'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'classesId'], row.get('classesId'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'minInitialInvestment'], row.get('minInitialInvestment'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'nameOfPersonDescExpensePay'], row.get('nameOfPersonDescExpensePay'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'netAssetsOfClass'], row.get('netAssetsOfClass'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'numberOfSharesOutstanding'], row.get('numberOfSharesOutstanding'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'otherInvestorTypeDescription'], row.get('otherInvestorTypeDescription'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompBrokerDealer'], row.get('percentShareHolderCompBrokerDealer'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompDepositoryInst'], row.get('percentShareHolderCompDepositoryInst'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompInsurance'], row.get('percentShareHolderCompInsurance'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompMunicipal'], row.get('percentShareHolderCompMunicipal'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompNonFinancialCorp'], row.get('percentShareHolderCompNonFinancialCorp'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompNonProfit'], row.get('percentShareHolderCompNonProfit'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompOther'], row.get('percentShareHolderCompOther'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompPensionPlan'], row.get('percentShareHolderCompPensionPlan'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompPrivateFunds'], row.get('percentShareHolderCompPrivateFunds'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompRegInvestment'], row.get('percentShareHolderCompRegInvestment'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'percentShareHolderCompSovereignFund'], row.get('percentShareHolderCompSovereignFund'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'personPayForFundFlag'], row.get('personPayForFundFlag'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'shareCancellationReportingPeriod'], row.get('shareCancellationReportingPeriod'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'assetBackedCommercialPaperAmt'], row.get('assetBackedCommercialPaperAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'certificateDepositAmt'], row.get('certificateDepositAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'depositionUSTreasuryDebtAmt'], row.get('depositionUSTreasuryDebtAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'financialCompanyCommercialAmt'], row.get('financialCompanyCommercialAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'govtAgencyCouponPayingDebtAmt'], row.get('govtAgencyCouponPayingDebtAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'govtAgencyNonCouponPayingDebtAmt'], row.get('govtAgencyNonCouponPayingDebtAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'insuranceCompanyFundAgreementAmt'], row.get('insuranceCompanyFundAgreementAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'investmentCompanyAmt'], row.get('investmentCompanyAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'nonFinancialCompanyCommercialAmt'], row.get('nonFinancialCompanyCommercialAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'nonNegotiableTimeDepositAmt'], row.get('nonNegotiableTimeDepositAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'nonUSSovereignSupraNationalDebtAmt'], row.get('nonUSSovereignSupraNationalDebtAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'otherAssetBackedSecuritiesAmt'], row.get('otherAssetBackedSecuritiesAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'otherInstrumentAmt'], row.get('otherInstrumentAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'otherInstrumentBriefDescription'], row.get('otherInstrumentBriefDescription'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'otherMunicipalSecurityAmt'], row.get('otherMunicipalSecurityAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'otherRepurchaseAgreementAmt'], row.get('otherRepurchaseAgreementAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'tenderOptionBondAmt'], row.get('tenderOptionBondAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'usGovtAgencyRepurchaseAgreementAmt'], row.get('usGovtAgencyRepurchaseAgreementAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'usTreasuryRepurchaseAgreementAmt'], row.get('usTreasuryRepurchaseAgreementAmt'))
        _add_path_text(root, ['formData', 'dispositionOfPortfolioSecurities', 'variableRateDemandNoteAmt'], row.get('variableRateDemandNoteAmt'))
        _add_path_text(root, ['formData', 'generalInfo', 'cik'], row.get('cik'))
        _add_path_text(root, ['formData', 'generalInfo', 'finalFilingFlag'], row.get('finalFilingFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'fundAcqrdOrMrgdWthAnthrFlag'], row.get('fundAcqrdOrMrgdWthAnthrFlag'))
        _add_path_text(root, ['formData', 'generalInfo', 'leiOfSeries'], row.get('leiOfSeries'))
        _add_path_text(root, ['formData', 'generalInfo', 'nameOfSeries'], row.get('nameOfSeries'))
        _add_path_text(root, ['formData', 'generalInfo', 'registrantFullName'], row.get('registrantFullName'))
        _add_path_text(root, ['formData', 'generalInfo', 'registrantLEIId'], row.get('registrantLEIId'))
        _add_path_text(root, ['formData', 'generalInfo', 'reportDate'], row.get('reportDate'))
        _add_path_text(root, ['formData', 'generalInfo', 'seriesId'], row.get('seriesId'))
        _add_path_text(root, ['formData', 'generalInfo', 'totalShareClassesInSeries'], row.get('totalShareClassesInSeries'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'CUSIPMember'], row.get('cUSIPMember'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'ISINId'], row.get('iSINId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'LEIID'], row.get('lEIID'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'briefDescription'], row.get('briefDescription'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'cik'], row.get('scheduleOfPortfolioSecuritiesInfoCik'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'coupon'], row.get('coupon'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'dailyLiquidAssetSecurityFlag'], row.get('dailyLiquidAssetSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'excludingValueOfAnySponsorSupport'], row.get('excludingValueOfAnySponsorSupport'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'explanatoryNotes'], row.get('explanatoryNotes'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'finalLegalInvestmentMaturityDate'], row.get('finalLegalInvestmentMaturityDate'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'fundAcqstnUndrlyngSecurityFlag'], row.get('fundAcqstnUndrlyngSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'illiquidSecurityFlag'], row.get('illiquidSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'includingValueOfAnySponsorSupport'], row.get('includingValueOfAnySponsorSupport'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentCategory'], row.get('investmentCategory'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentMaturityDateWAL'], row.get('investmentMaturityDateWAL'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'investmentMaturityDateWAM'], row.get('investmentMaturityDateWAM'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'nameOfIssuer'], row.get('nameOfIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'otherUniqueId'], row.get('otherUniqueId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'percentageOfMoneyMarketFundNetAssets'], row.get('percentageOfMoneyMarketFundNetAssets'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityCategorizedAtLevel3Flag'], row.get('securityCategorizedAtLevel3Flag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityDemandFeatureFlag'], row.get('securityDemandFeatureFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityEligibilityFlag'], row.get('securityEligibilityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityEnhancementsFlag'], row.get('securityEnhancementsFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'securityGuaranteeFlag'], row.get('securityGuaranteeFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'titleOfIssuer'], row.get('titleOfIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'weeklyLiquidAssetSecurityFlag'], row.get('weeklyLiquidAssetSecurityFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'yieldOfTheSecurityAsOfReportingDate'], row.get('yieldOfTheSecurityAsOfReportingDate'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'amortizedCostPortfolioSecurities'], row.get('amortizedCostPortfolioSecurities'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'averageLifeMaturity'], row.get('averageLifeMaturity'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'averagePortfolioMaturity'], row.get('averagePortfolioMaturity'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'cash'], row.get('cash'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'cashMgmtVehicleAffliatedFundFlag'], row.get('cashMgmtVehicleAffliatedFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFundFlag'], row.get('feederFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'fundRetailMoneyMarketFlag'], row.get('fundRetailMoneyMarketFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'govMoneyMrktFundFlag'], row.get('govMoneyMrktFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidityFeeFundApplyFlag'], row.get('liquidityFeeFundApplyFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFundFlag'], row.get('masterFundFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'moneyMarketFundCategory'], row.get('moneyMarketFundCategory'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'netAssetOfSeries'], row.get('netAssetOfSeries'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'numberOfSharesOutstanding'], row.get('seriesLevelInfoNumberOfSharesOutstanding'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'securitiesActFileNumber'], row.get('securitiesActFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'seekStablePricePerShare'], row.get('seekStablePricePerShare'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'seriesFundInsuCmpnySepAccntFlag'], row.get('seriesFundInsuCmpnySepAccntFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'stablePricePerShare'], row.get('stablePricePerShare'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueLiabilities'], row.get('totalValueLiabilities'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValueOtherAssets'], row.get('totalValueOtherAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'totalValuePortfolioSecurities'], row.get('totalValuePortfolioSecurities'))
        _add_path_text(root, ['formData', 'signature', 'nameOfSigningOfficer'], row.get('nameOfSigningOfficer'))
        _add_path_text(root, ['formData', 'signature', 'registrant'], row.get('registrant'))
        _add_path_text(root, ['formData', 'signature', 'signature'], row.get('signature'))
        _add_path_text(root, ['formData', 'signature', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['formData', 'signature', 'titleOfSigningOfficer'], row.get('titleOfSigningOfficer'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'beneficialRecordOwnerCategory', 'beneficialRecordOwnerCategoryType'], row.get('beneficialRecordOwnerCategoryType'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'beneficialRecordOwnerCategory', 'otherInvestorCategory'], row.get('otherInvestorCategory'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'beneficialRecordOwnerCategory', 'percentOutstandingSharesBeneficial'], row.get('percentOutstandingSharesBeneficial'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'beneficialRecordOwnerCategory', 'percentOutstandingSharesRecord'], row.get('percentOutstandingSharesRecord'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'dialyShareholderFlowReported', 'dailyShareHolderFlowDate'], row.get('dailyShareHolderFlowDate'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'dailyNetAssetValuePerShareClass', 'dailyNetAssetValuePerShareClass'], row.get('dailyNetAssetValuePerShareClass'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'dailyNetAssetValuePerShareClass', 'dailyNetAssetValuePerShareDateClass'], row.get('dailyNetAssetValuePerShareDateClass'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'dialyShareholderFlowReported', 'dailyGrossRedemptions'], row.get('dailyGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'dialyShareholderFlowReported', 'dailyGrossSubscriptions'], row.get('dailyGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'monthlyShareholderFlowReported', 'totalGrossRedemptions'], row.get('totalGrossRedemptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'monthlyShareholderFlowReported', 'totalGrossSubscriptions'], row.get('totalGrossSubscriptions'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'sevenDayNetYield', 'sevenDayNetYieldDate'], row.get('sevenDayNetYieldDate'))
        _add_path_text(root, ['formData', 'classLevelInfo', 'sevenDayNetYield', 'sevenDayNetYieldValue'], row.get('sevenDayNetYieldValue'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'cik'], row.get('feederFundCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'seriesId'], row.get('feederFundSeriesId'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'assigningNRSRORating', 'nameOfNRSRO'], row.get('nameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'assigningNRSRORating', 'rating'], row.get('rating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'amountProvidedByDemandFeatureIssuer'], row.get('amountProvidedByDemandFeatureIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureConditionalFlag'], row.get('demandFeatureConditionalFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'identityOfDemandFeatureIssuer'], row.get('identityOfDemandFeatureIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'remainingPeriodDemandFeature'], row.get('remainingPeriodDemandFeature'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'amountProvidedByEnhancement'], row.get('amountProvidedByEnhancement'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'identityOfTheEnhancementProvider'], row.get('identityOfTheEnhancementProvider'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'typeOfEnhancement'], row.get('typeOfEnhancement'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'amountProvidedByGuarantor'], row.get('amountProvidedByGuarantor'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'identityOfTheGuarantor'], row.get('identityOfTheGuarantor'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'nameOfCCP'], row.get('nameOfCCP'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'repurchaseAgreementClearedFlag'], row.get('repurchaseAgreementClearedFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'repurchaseAgreementOpenFlag'], row.get('repurchaseAgreementOpenFlag'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'repurchaseAgreementTripartyFlag'], row.get('repurchaseAgreementTripartyFlag'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'administrator', 'administratorName'], row.get('administratorName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'adviser', 'adviserFileNumber'], row.get('adviserFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'adviser', 'adviserName'], row.get('adviserName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'dailyNetAssetValuePerShareSeries', 'dailyNetAssetValuePerShareDateSeries'], row.get('dailyNetAssetValuePerShareDateSeries'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'dailyNetAssetValuePerShareSeries', 'dailyNetAssetValuePerShareSeries'], row.get('dailyNetAssetValuePerShareSeries'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'feederFund', 'name'], row.get('name'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'name'], row.get('indpPubAccountantName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'indpPubAccountant', 'stateCountry'], row.get('stateCountry'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidAssetsDetails', 'percentageDailyLiquidAssets'], row.get('percentageDailyLiquidAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidAssetsDetails', 'percentageWeeklyLiquidAssets'], row.get('percentageWeeklyLiquidAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidAssetsDetails', 'totalLiquidAssetsNearPercentDate'], row.get('totalLiquidAssetsNearPercentDate'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidAssetsDetails', 'totalValueDailyLiquidAssets'], row.get('totalValueDailyLiquidAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'liquidAssetsDetails', 'totalValueWeeklyLiquidAssets'], row.get('totalValueWeeklyLiquidAssets'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'cik'], row.get('masterFeederFundCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'name'], row.get('masterFeederFundName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'masterFeederFund', 'seriesId'], row.get('masterFeederFundSeriesId'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'sevenDayGrossYield', 'sevenDayGrossYieldDate'], row.get('sevenDayGrossYieldDate'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'sevenDayGrossYield', 'sevenDayGrossYieldValue'], row.get('sevenDayGrossYieldValue'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'subAdviser', 'adviserFileNumber'], row.get('subAdviserAdviserFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'subAdviser', 'adviserName'], row.get('subAdviserAdviserName'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'cik'], row.get('transferAgentCik'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'fileNumber'], row.get('transferAgentFileNumber'))
        _add_path_text(root, ['formData', 'seriesLevelInfo', 'transferAgent', 'name'], row.get('transferAgentName'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureRatingOrNRSRO', 'nameOfNRSRO'], row.get('demandFeatureRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'demandFeature', 'demandFeatureRatingOrNRSRO', 'rating'], row.get('demandFeatureRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'enhancementRatingOrNRSRO', 'nameOfNRSRO'], row.get('enhancementRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'enhancementProvider', 'enhancementRatingOrNRSRO', 'rating'], row.get('enhancementRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'guarantorRatingOrNRSRO', 'nameOfNRSRO'], row.get('guarantorRatingOrNRSRONameOfNRSRO'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'guarantor', 'guarantorRatingOrNRSRO', 'rating'], row.get('guarantorRatingOrNRSRORating'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'CUSIPMember'], row.get('collateralIssuersCUSIPMember'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'LEIID'], row.get('collateralIssuersLEIID'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'coupon'], row.get('collateralIssuersCoupon'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'ctgryInvestmentsRprsntsCollateral'], row.get('ctgryInvestmentsRprsntsCollateral'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'nameOfCollateralIssuer'], row.get('nameOfCollateralIssuer'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'principalAmountToTheNearestCent'], row.get('principalAmountToTheNearestCent'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'valueOfCollateralToTheNearestCent'], row.get('valueOfCollateralToTheNearestCent'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'yield'], row.get('yield'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('filerCredentialsCik'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'date'], row.get('date'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'dateRange', 'from'], row.get('from'))
        _add_path_text(root, ['formData', 'scheduleOfPortfolioSecuritiesInfo', 'repurchaseAgreement', 'collateralIssuers', 'maturityDate', 'dateRange', 'to'], row.get('to'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




