import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_sbse(rows: list) -> bytes:

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/sbse/sbsefiler')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    root.set('xmlns:sbse', 'http://www.sec.gov/edgar/sbse_drp')
    for row in rows:
        _add_path_text(root, ['headerData', 'submissionType'], row.get('submissionType'))
        _add_path_text(root, ['formData', 'applicantOne', 'crdNo'], row.get('crdNo'))
        _add_path_text(root, ['formData', 'applicantOne', 'describeBusiness'], row.get('describeBusiness'))
        _add_path_text(root, ['formData', 'applicantOne', 'fullApplicantName'], row.get('fullApplicantName'))
        _add_path_text(root, ['formData', 'applicantOne', 'isDerivativesDealer'], row.get('isDerivativesDealer'))
        _add_path_text(root, ['formData', 'applicantOne', 'isForeignRegulatory'], row.get('isForeignRegulatory'))
        _add_path_text(root, ['formData', 'applicantOne', 'isSubjectToRegulator'], row.get('isSubjectToRegulator'))
        _add_path_text(root, ['formData', 'applicantOne', 'isSwapDealer'], row.get('isSwapDealer'))
        _add_path_text(root, ['formData', 'applicantOne', 'isSwapParticipant'], row.get('isSwapParticipant'))
        _add_path_text(root, ['formData', 'applicantOne', 'registeredAs'], row.get('registeredAs'))
        _add_path_text(root, ['formData', 'applicantOne', 'websiteUrl'], row.get('websiteUrl'))
        _add_path_text(root, ['formData', 'certificationOne', 'applicantName'], row.get('certificationOneApplicantName'))
        _add_path_text(root, ['formData', 'certificationOne', 'cerApplicantName'], row.get('cerApplicantName'))
        _add_path_text(root, ['formData', 'certificationOne', 'cerDate'], row.get('cerDate'))
        _add_path_text(root, ['formData', 'certificationOne', 'name'], row.get('certificationOneName'))
        _add_path_text(root, ['formData', 'certificationOne', 'signature'], row.get('certificationOneSignature'))
        _add_path_text(root, ['formData', 'certificationOne', 'title'], row.get('title'))
        _add_path_text(root, ['formData', 'certificationTwo', 'applicantName'], row.get('certificationTwoApplicantName'))
        _add_path_text(root, ['formData', 'certificationTwo', 'cerApplicantName'], row.get('certificationTwoCerApplicantName'))
        _add_path_text(root, ['formData', 'certificationTwo', 'cerDate'], row.get('certificationTwoCerDate'))
        _add_path_text(root, ['formData', 'certificationTwo', 'name'], row.get('certificationTwoName'))
        _add_path_text(root, ['formData', 'certificationTwo', 'signature'], row.get('certificationTwoSignature'))
        _add_path_text(root, ['formData', 'execution', 'date'], row.get('date'))
        _add_path_text(root, ['formData', 'execution', 'executionDate'], row.get('executionDate'))
        _add_path_text(root, ['formData', 'execution', 'nameOfApplicant'], row.get('nameOfApplicant'))
        _add_path_text(root, ['formData', 'execution', 'nameOfPersonSigning'], row.get('nameOfPersonSigning'))
        _add_path_text(root, ['formData', 'execution', 'signature'], row.get('signature'))
        _add_path_text(root, ['formData', 'execution', 'titleOfPersonSigning'], row.get('titleOfPersonSigning'))
        _add_path_text(root, ['formData', 'principalInfo', 'amendedItemsList'], row.get('amendedItemsList'))
        _add_path_text(root, ['formData', 'principalInfo', 'applicantName'], row.get('principalInfoApplicantName'))
        _add_path_text(root, ['formData', 'principalInfo', 'city'], row.get('city'))
        _add_path_text(root, ['formData', 'principalInfo', 'stateOrCountry'], row.get('stateOrCountry'))
        _add_path_text(root, ['formData', 'principalInfo', 'street1'], row.get('street1'))
        _add_path_text(root, ['formData', 'principalInfo', 'street2'], row.get('street2'))
        _add_path_text(root, ['formData', 'principalInfo', 'zipCode'], row.get('zipCode'))
        _add_path_text(root, ['formData', 'sbseW', 'dateCeasedBusiness'], row.get('dateCeasedBusiness'))
        _add_path_text(root, ['formData', 'sbseW', 'firmName'], row.get('firmName'))
        _add_path_text(root, ['formData', 'sbseW', 'firmOrIndividual'], row.get('firmOrIndividual'))
        _add_path_text(root, ['formData', 'sbseW', 'fullName'], row.get('fullName'))
        _add_path_text(root, ['formData', 'sbseW', 'irsEmplIdentNo'], row.get('irsEmplIdentNo'))
        _add_path_text(root, ['formData', 'sbseW', 'isComplaint'], row.get('isComplaint'))
        _add_path_text(root, ['formData', 'sbseW', 'isHoldCollateral'], row.get('isHoldCollateral'))
        _add_path_text(root, ['formData', 'sbseW', 'isInvestigation'], row.get('isInvestigation'))
        _add_path_text(root, ['formData', 'sbseW', 'islitigation'], row.get('islitigation'))
        _add_path_text(root, ['formData', 'sbseW', 'personTelephoneNumber'], row.get('personTelephoneNumber'))
        _add_path_text(root, ['formData', 'sbseW', 'registrationType'], row.get('registrationType'))
        _add_path_text(root, ['formData', 'sbseW', 'secFileNumber'], row.get('secFileNumber'))
        _add_path_text(root, ['formData', 'sbseW', 'telephoneNumber'], row.get('telephoneNumber'))
        _add_path_text(root, ['formData', 'scheduleA', 'applicantName'], row.get('applicantName'))
        _add_path_text(root, ['formData', 'scheduleA', 'applicantNfaNo'], row.get('applicantNfaNo'))
        _add_path_text(root, ['formData', 'scheduleA', 'isAnyIndirectOwners'], row.get('isAnyIndirectOwners'))
        _add_path_text(root, ['formData', 'scheduleB', 'applicantNFANo'], row.get('scheduleBApplicantNfaNo'))
        _add_path_text(root, ['formData', 'scheduleB', 'applicantName'], row.get('scheduleBApplicantName'))
        _add_path_text(root, ['formData', 'scheduleB', 'initialOrAmended'], row.get('initialOrAmended'))
        _add_path_text(root, ['formData', 'scheduleE', 'applicantName'], row.get('scheduleEApplicantName'))
        _add_path_text(root, ['formData', 'scheduleF', 'applicantNFANo'], row.get('scheduleFApplicantNfaNo'))
        _add_path_text(root, ['formData', 'scheduleF', 'applicantName'], row.get('scheduleFApplicantName'))
        _add_path_text(root, ['formData', 'scheduleF', 'name'], row.get('name'))
        _add_path_text(root, ['formData', 'scheduleF', 'signature'], row.get('scheduleFSignature'))
        _add_path_text(root, ['formData', 'scheduleF', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['formData', 'scheduleF', 'signerName'], row.get('signerName'))
        _add_path_text(root, ['formData', 'scheduleF', 'signerTitle'], row.get('signerTitle'))
        _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], row.get('liveTestFlag'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'applicantName'], row.get('applicantDataPageFiveApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'isEffectTransactions'], row.get('isEffectTransactions'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'isEngagedInNonSecurity'], row.get('isEngagedInNonSecurity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'isForeignRegulatory'], row.get('applicantDataPageFiveIsForeignRegulatory'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'isRegisteredWithCommission'], row.get('isRegisteredWithCommission'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'applicantName'], row.get('applicantDataPageFourApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'applicantCik'], row.get('applicantDataPageOneApplicantCik'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'applicantUic'], row.get('applicantDataPageOneApplicantUic'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'businessName'], row.get('businessName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'businessTelephoneNumber'], row.get('applicantDataPageOneBusinessTelephoneNumber'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'fullApplicantName'], row.get('applicantDataPageOneFullApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'taxIdentificationNo'], row.get('taxIdentificationNo'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'websiteUrl'], row.get('applicantDataPageOneWebsiteUrl'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'applicantName'], row.get('applicantDataPageThreeApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isControlThroughAgreement'], row.get('applicantDataPageThreeIsControlThroughAgreement'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isControlWithBank'], row.get('isControlWithBank'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isEngagedInSecurities'], row.get('isEngagedInSecurities'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isOnBehalf'], row.get('applicantDataPageThreeIsOnBehalf'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isRecordsKept'], row.get('applicantDataPageThreeIsRecordsKept'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'isWhollyOrPartiallyFinance'], row.get('applicantDataPageThreeIsWhollyOrPartiallyFinance'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'applicantName'], row.get('applicantDataPageTwoApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'countryOfFormation'], row.get('countryOfFormation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'dateOfFormation'], row.get('dateOfFormation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'descriptionBusiness'], row.get('applicantDataPageTwoDescriptionBusiness'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isCommissionDetermine'], row.get('applicantDataPageTwoIsCommissionDetermine'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isHoldFunds'], row.get('applicantDataPageTwoIsHoldFunds'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isNonResidentEntity'], row.get('applicantDataPageTwoIsNonResidentEntity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isSelfDetermine'], row.get('applicantDataPageTwoIsSelfDetermine'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isSubjectToRegulator'], row.get('applicantDataPageTwoIsSubjectToRegulator'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isSucceeding'], row.get('applicantDataPageTwoIsSucceeding'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isSwapDealer'], row.get('applicantDataPageTwoIsSwapDealer'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isSwapParticipant'], row.get('applicantDataPageTwoIsSwapParticipant'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'isUseMathModels'], row.get('isUseMathModels'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'legalStatus'], row.get('legalStatus'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'monthApplicantFiscalEnds'], row.get('monthApplicantFiscalEnds'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'stateOfFormation'], row.get('stateOfFormation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'applicantCik'], row.get('applicantCik'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'applicantNFAId'], row.get('applicantNfaId'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'applicantNFANumber'], row.get('applicantNfaNumber'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'applicantUic'], row.get('applicantUic'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'businessTelephoneNumber'], row.get('businessTelephoneNumber'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'fullApplicantName'], row.get('applicantOneFullApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'irsEmplIdentNo'], row.get('applicantOneIrsEmplIdentNo'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'websiteUrl'], row.get('applicantOneWebsiteUrl'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'applicantNFANo'], row.get('applicantThreeApplicantNfaNo'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'applicantName'], row.get('applicantThreeApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isControlThroughAgreement'], row.get('isControlThroughAgreement'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isForeignRegulatory'], row.get('applicantThreeIsForeignRegulatory'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isNotIdentified'], row.get('isNotIdentified'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isOnBehalf'], row.get('isOnBehalf'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isRecordsKept'], row.get('isRecordsKept'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isSucceeding'], row.get('isSucceeding'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'isWhollyOrPartiallyFinance'], row.get('isWhollyOrPartiallyFinance'))
        _add_path_text(root, ['formData', 'applicant', 'applicantThree', 'numberOfPrincipals'], row.get('numberOfPrincipals'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'applicantNFANo'], row.get('applicantTwoApplicantNfaNo'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'applicantName'], row.get('applicantTwoApplicantName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'description3C'], row.get('description3C'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'descriptionBusiness'], row.get('descriptionBusiness'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'foreignFinancialRegulatory'], row.get('foreignFinancialRegulatory'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isCommissionDetermine'], row.get('isCommissionDetermine'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isEngageInOtherBusiness'], row.get('isEngageInOtherBusiness'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isHoldFunds'], row.get('isHoldFunds'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isInvestmentAdvisor'], row.get('isInvestmentAdvisor'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isMathematicalModels'], row.get('isMathematicalModels'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isNonResidentEntity'], row.get('isNonResidentEntity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isRegisteredAsOther'], row.get('isRegisteredAsOther'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isSelfDetermine'], row.get('isSelfDetermine'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isSubjectToRegulator'], row.get('applicantTwoIsSubjectToRegulator'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isSwapDealer'], row.get('applicantTwoIsSwapDealer'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'isSwapParticipant'], row.get('applicantTwoIsSwapParticipant'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'prudentialRegulator'], row.get('prudentialRegulator'))
        _add_path_text(root, ['formData', 'applicant', 'applicantTwo', 'registeredAs'], row.get('applicantTwoRegisteredAs'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'emailAddress'], row.get('chiefComplianceOfficerEmailAddress'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'phone'], row.get('chiefComplianceOfficerPhone'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'title'], row.get('chiefComplianceOfficerTitle'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'emailAddress'], row.get('emailAddress'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'phone'], row.get('phone'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'title'], row.get('contactEmployeeTitle'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'drpFiledFor'], row.get('drpFiledFor'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'initialOrAmended'], row.get('criminalDrpInitialOrAmended'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'drpFiledFor'], row.get('regulatoryDrpDrpFiledFor'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'initialOrAmended'], row.get('regulatoryDrpInitialOrAmended'))
        _add_path_text(root, ['formData', 'sbseW', 'mainAddress', 'city'], row.get('mainAddressCity'))
        _add_path_text(root, ['formData', 'sbseW', 'mainAddress', 'stateOrCountry'], row.get('mainAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'sbseW', 'mainAddress', 'street1'], row.get('mainAddressStreet1'))
        _add_path_text(root, ['formData', 'sbseW', 'mainAddress', 'zipCode'], row.get('mainAddressZipCode'))
        _add_path_text(root, ['formData', 'sbseW', 'personAddress', 'city'], row.get('personAddressCity'))
        _add_path_text(root, ['formData', 'sbseW', 'personAddress', 'stateOrCountry'], row.get('personAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'sbseW', 'personAddress', 'street1'], row.get('personAddressStreet1'))
        _add_path_text(root, ['formData', 'sbseW', 'personAddress', 'zipCode'], row.get('personAddressZipCode'))
        _add_path_text(root, ['formData', 'sbseW', 'reasonsToWithdraw', 'reasonToWithdraw'], row.get('reasonToWithdraw'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'controlPerson'], row.get('controlPerson'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'crdNo'], row.get('scheduleAInfoCrdNo'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'dateBeganWorking'], row.get('dateBeganWorking'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'dateTitleOrStatusAcquired'], row.get('dateTitleOrStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'description'], row.get('scheduleAInfoDescription'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'entityType'], row.get('entityType'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'firmOrIndividual'], row.get('scheduleAInfoFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'fullLegalName'], row.get('fullLegalName'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'haveOwnershipInterest'], row.get('haveOwnershipInterest'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'irsTaxNo'], row.get('irsTaxNo'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'nfaIdentificationNo'], row.get('nfaIdentificationNo'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'ownershipCode'], row.get('ownershipCode'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'titleOrStatus'], row.get('titleOrStatus'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'controlPerson'], row.get('scheduleBInfoControlPerson'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'dateTitleOrStatusAcquired'], row.get('scheduleBInfoDateTitleOrStatusAcquired'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'entityType'], row.get('scheduleBInfoEntityType'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'firmOrIndividual'], row.get('scheduleBInfoFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'foreignBusinessNo'], row.get('foreignBusinessNo'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'fullLegalName'], row.get('scheduleBInfoFullLegalName'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'interestOwnedEntity'], row.get('interestOwnedEntity'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'irsTaxNo'], row.get('scheduleBInfoIrsTaxNo'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'ownershipCode'], row.get('scheduleBInfoOwnershipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'pr'], row.get('pr'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'status'], row.get('status'))
        _add_path_text(root, ['formData', 'scheduleB', 'scheduleBInfo', 'uic'], row.get('uic'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'description'], row.get('sectionFourDescription'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'effectType'], row.get('effectType'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'nameOfPrincipal'], row.get('nameOfPrincipal'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'taxIdentificationNumber'], row.get('taxIdentificationNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'typeOfEntity'], row.get('typeOfEntity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionOne', 'assigningRegulators'], row.get('assigningRegulators'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionOne', 'description'], row.get('description'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionOne', 'uicNumber'], row.get('uicNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'applicantNFANo'], row.get('scheduleDListApplicantNfaNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'applicantName'], row.get('scheduleDListApplicantName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'principalName'], row.get('principalName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'applicantName'], row.get('scheduleDOneApplicantName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'initialOrAmended'], row.get('scheduleDOneInitialOrAmended'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'applicantName'], row.get('scheduleDThreeApplicantName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'controlWithBank'], row.get('controlWithBank'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'initialOrAmended'], row.get('scheduleDThreeInitialOrAmended'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'applicantName'], row.get('scheduleDTwoApplicantName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'engagedInSecurities'], row.get('engagedInSecurities'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'initialOrAmended'], row.get('scheduleDTwoInitialOrAmended'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'associatedPerson'], row.get('associatedPerson'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'businessLocChangeOption'], row.get('businessLocChangeOption'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'effectiveDate'], row.get('effectiveDate'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'institutionName'], row.get('institutionName'))
        _add_path_text(root, ['formData', 'scheduleF', 'foreignFinancialReg', 'foreignBusinessNo'], row.get('foreignFinancialRegForeignBusinessNo'))
        _add_path_text(root, ['formData', 'scheduleF', 'foreignFinancialReg', 'nameOfCountry'], row.get('nameOfCountry'))
        _add_path_text(root, ['formData', 'scheduleF', 'foreignFinancialReg', 'nameOfRegulatory'], row.get('nameOfRegulatory'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'firmName'], row.get('serviceOfProcessFirmName'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'firmOrIndividual'], row.get('serviceOfProcessFirmOrIndividual'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'overrideInternetFlag'], row.get('overrideInternetFlag'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], row.get('returnCopyFlag'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'financialDisclosure', 'hasSubjectOfBankruptcy'], row.get('financialDisclosureHasSubjectOfBankruptcy'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFive', 'financialDisclosure', 'hasTrusteeAppointed'], row.get('financialDisclosureHasTrusteeAppointed'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'civilJudicialActionDisclosure', 'isDismissed'], row.get('civilJudicialActionDisclosureIsDismissed'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'civilJudicialActionDisclosure', 'isEnjoined'], row.get('civilJudicialActionDisclosureIsEnjoined'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'civilJudicialActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('civilJudicialActionDisclosureIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'civilJudicialActionDisclosure', 'isNamedInCivilProceeding'], row.get('civilJudicialActionDisclosureIsNamedInCivilProceeding'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isAuthorizedToActAttorney'], row.get('regulatoryActionDisclosureIsAuthorizedToActAttorney'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isCauseOfDenial'], row.get('regulatoryActionDisclosureIsCauseOfDenial'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isDeniedLicense'], row.get('regulatoryActionDisclosureIsDeniedLicense'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isDisciplined'], row.get('regulatoryActionDisclosureIsDisciplined'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isFoundInCauseOfDenial'], row.get('regulatoryActionDisclosureIsFoundInCauseOfDenial'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isFoundInCauseOfSuspension'], row.get('regulatoryActionDisclosureIsFoundInCauseOfSuspension'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('regulatoryActionDisclosureIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isFoundInViolationOfRules'], row.get('regulatoryActionDisclosureIsFoundInViolationOfRules'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isFoundMadeFalseStatement'], row.get('regulatoryActionDisclosureIsFoundMadeFalseStatement'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isImposedPenalty'], row.get('regulatoryActionDisclosureIsImposedPenalty'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isMadeFalseStatement'], row.get('regulatoryActionDisclosureIsMadeFalseStatement'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isNamedInRegulatoryProceeding'], row.get('regulatoryActionDisclosureIsNamedInRegulatoryProceeding'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isOrderAgainst'], row.get('regulatoryActionDisclosureIsOrderAgainst'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isOrderAgainstActivity'], row.get('regulatoryActionDisclosureIsOrderAgainstActivity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isUnethical'], row.get('regulatoryActionDisclosureIsUnethical'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageFour', 'regulatoryActionDisclosure', 'isViolatedRegulation'], row.get('regulatoryActionDisclosureIsViolatedRegulation'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'emailAddress'], row.get('applicantDataPageOneChiefComplianceOfficerEmailAddress'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'phone'], row.get('applicantDataPageOneChiefComplianceOfficerPhone'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'title'], row.get('applicantDataPageOneChiefComplianceOfficerTitle'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'emailAddress'], row.get('contactEmployeeEmailAddress'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'phone'], row.get('contactEmployeePhone'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'title'], row.get('applicantDataPageOneContactEmployeeTitle'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mailingAddress', 'city'], row.get('mailingAddressCity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mailingAddress', 'stateOrCountry'], row.get('mailingAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mailingAddress', 'street1'], row.get('mailingAddressStreet1'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mailingAddress', 'street2'], row.get('mailingAddressStreet2'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mailingAddress', 'zipCode'], row.get('mailingAddressZipCode'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mainAddress', 'city'], row.get('applicantDataPageOneMainAddressCity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mainAddress', 'stateOrCountry'], row.get('applicantDataPageOneMainAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mainAddress', 'street1'], row.get('applicantDataPageOneMainAddressStreet1'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mainAddress', 'street2'], row.get('mainAddressStreet2'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'mainAddress', 'zipCode'], row.get('applicantDataPageOneMainAddressZipCode'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'criminalDisclosure', 'isChargedMisdemeanor'], row.get('criminalDisclosureIsChargedMisdemeanor'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'criminalDisclosure', 'isChargedWithFelony'], row.get('criminalDisclosureIsChargedWithFelony'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'criminalDisclosure', 'isConvictedMisdemeanor'], row.get('criminalDisclosureIsConvictedMisdemeanor'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageThree', 'criminalDisclosure', 'isConvictedOfFelony'], row.get('criminalDisclosureIsConvictedOfFelony'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'prudentialRegulators', 'prudentialRegulator'], row.get('prudentialRegulatorsPrudentialRegulator'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageTwo', 'swapOptions', 'swapOption'], row.get('swapOption'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'emailAddress'], row.get('applicantOneChiefComplianceOfficerEmailAddress'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'phone'], row.get('applicantOneChiefComplianceOfficerPhone'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'title'], row.get('applicantOneChiefComplianceOfficerTitle'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'emailAddress'], row.get('applicantOneContactEmployeeEmailAddress'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'phone'], row.get('applicantOneContactEmployeePhone'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'title'], row.get('applicantOneContactEmployeeTitle'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mailingAddress', 'city'], row.get('applicantOneMailingAddressCity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mailingAddress', 'stateOrCountry'], row.get('applicantOneMailingAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mailingAddress', 'street1'], row.get('applicantOneMailingAddressStreet1'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mailingAddress', 'street2'], row.get('applicantOneMailingAddressStreet2'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mailingAddress', 'zipCode'], row.get('applicantOneMailingAddressZipCode'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mainAddress', 'city'], row.get('applicantOneMainAddressCity'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mainAddress', 'stateOrCountry'], row.get('applicantOneMainAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mainAddress', 'street1'], row.get('applicantOneMainAddressStreet1'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mainAddress', 'street2'], row.get('applicantOneMainAddressStreet2'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'mainAddress', 'zipCode'], row.get('applicantOneMainAddressZipCode'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'firstName'], row.get('officerNameFirstName'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'lastName'], row.get('officerNameLastName'))
        _add_path_text(root, ['formData', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'middleName'], row.get('officerNameMiddleName'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'firstName'], row.get('contactEmployeeNameFirstName'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'lastName'], row.get('contactEmployeeNameLastName'))
        _add_path_text(root, ['formData', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'middleName'], row.get('contactEmployeeNameMiddleName'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'summaryOfCircumstances'], row.get('summaryOfCircumstances'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'respondingTo', 'responseQuestion'], row.get('responseQuestion'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'respondingTo', 'responseQuestion'], row.get('respondingToResponseQuestion'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'individualName', 'firstName'], row.get('firstName'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'individualName', 'lastName'], row.get('lastName'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'individualName', 'middleName'], row.get('middleName'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'individualName', 'prefix'], row.get('prefix'))
        _add_path_text(root, ['formData', 'scheduleA', 'scheduleAInfo', 'individualName', 'suffix'], row.get('suffix'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'address', 'city'], row.get('addressCity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'address', 'stateOrCountry'], row.get('addressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'address', 'street1'], row.get('addressStreet1'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionFour', 'address', 'zipCode'], row.get('addressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'civilJudicialActionDisclosure', 'isDismissed'], row.get('isDismissed'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'civilJudicialActionDisclosure', 'isEnjoined'], row.get('isEnjoined'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'civilJudicialActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('scheduleDListCivilJudicialActionDisclosureIsFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'civilJudicialActionDisclosure', 'isNamedInCivilProceeding'], row.get('isNamedInCivilProceeding'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'criminalDisclosure', 'isChargedMisdemeanor'], row.get('isChargedMisdemeanor'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'criminalDisclosure', 'isChargedWithFelony'], row.get('isChargedWithFelony'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'criminalDisclosure', 'isConvictedMisdemeanor'], row.get('isConvictedMisdemeanor'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'criminalDisclosure', 'isConvictedOfFelony'], row.get('isConvictedOfFelony'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'financialDisclosure', 'hasSubjectOfBankruptcy'], row.get('hasSubjectOfBankruptcy'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'financialDisclosure', 'hasTrusteeAppointed'], row.get('hasTrusteeAppointed'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isAuthorizedToActAttorney'], row.get('isAuthorizedToActAttorney'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isCauseOfDenial'], row.get('isCauseOfDenial'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isDeniedLicense'], row.get('isDeniedLicense'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isDisciplined'], row.get('isDisciplined'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isFoundInCauseOfDenial'], row.get('isFoundInCauseOfDenial'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isFoundInCauseOfSuspension'], row.get('isFoundInCauseOfSuspension'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isFoundInViolationOfRegulation'], row.get('isFoundInViolationOfRegulation'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isFoundInViolationOfRules'], row.get('isFoundInViolationOfRules'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isFoundMadeFalseStatement'], row.get('isFoundMadeFalseStatement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isImposedPenalty'], row.get('isImposedPenalty'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isMadeFalseStatement'], row.get('isMadeFalseStatement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isNamedInRegulatoryProceeding'], row.get('isNamedInRegulatoryProceeding'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isOrderAgainst'], row.get('isOrderAgainst'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isOrderAgainstActivity'], row.get('isOrderAgainstActivity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isUnethical'], row.get('isUnethical'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDList', 'regulatoryActionDisclosure', 'isViolatedRegulation'], row.get('isViolatedRegulation'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionOne', 'otherName'], row.get('otherName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'countryOfDomicile'], row.get('sectionSixCountryOfDomicile'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'descriptionRelationship'], row.get('sectionSixDescriptionRelationship'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'effectiveDate'], row.get('sectionSixEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'financialInstitutionName'], row.get('financialInstitutionName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionType'], row.get('institutionType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'uicNumber'], row.get('sectionSixUicNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'countryOfDomicile'], row.get('countryOfDomicile'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'descriptionRelationship'], row.get('descriptionRelationship'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'effectiveDate'], row.get('sectionFiveEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'isForeignEntity'], row.get('isForeignEntity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'isInvestmentAdvisoryAct'], row.get('isInvestmentAdvisoryAct'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'isSecurityAct'], row.get('isSecurityAct'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerCorpOrgName'], row.get('partnerCorpOrgName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerCorpOrgType'], row.get('partnerCorpOrgType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerCrdNumber'], row.get('partnerCrdNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerUicNumber'], row.get('partnerUicNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'terminationDate'], row.get('terminationDate'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'applicantAddress', 'city'], row.get('applicantAddressCity'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'applicantAddress', 'stateOrCountry'], row.get('applicantAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'applicantAddress', 'street1'], row.get('applicantAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'applicantAddress', 'street2'], row.get('applicantAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleE', 'scheduleEInfo', 'applicantAddress', 'zipCode'], row.get('applicantAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'serviceAddress', 'city'], row.get('serviceAddressCity'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'serviceAddress', 'stateOrCountry'], row.get('serviceAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'serviceAddress', 'street1'], row.get('serviceAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleF', 'serviceOfProcess', 'serviceAddress', 'zipCode'], row.get('serviceAddressZipCode'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('cik'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'filerCcc'], row.get('filerCcc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'filerCik'], row.get('filerCik'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'officerName', 'firstName'], row.get('chiefComplianceOfficerOfficerNameFirstName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'officerName', 'lastName'], row.get('chiefComplianceOfficerOfficerNameLastName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'chiefComplianceOfficer', 'officerName', 'middleName'], row.get('chiefComplianceOfficerOfficerNameMiddleName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'contactEmployeeName', 'firstName'], row.get('contactEmployeeContactEmployeeNameFirstName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'contactEmployeeName', 'lastName'], row.get('contactEmployeeContactEmployeeNameLastName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantDataPageOne', 'contactEmployee', 'contactEmployeeName', 'middleName'], row.get('contactEmployeeContactEmployeeNameMiddleName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'firstName'], row.get('applicantOneChiefComplianceOfficerOfficerNameFirstName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'lastName'], row.get('applicantOneChiefComplianceOfficerOfficerNameLastName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'middleName'], row.get('applicantOneChiefComplianceOfficerOfficerNameMiddleName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'prefix'], row.get('officerNamePrefix'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'chiefComplianceOfficer', 'officerName', 'suffix'], row.get('officerNameSuffix'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'firstName'], row.get('applicantOneContactEmployeeContactEmployeeNameFirstName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'lastName'], row.get('applicantOneContactEmployeeContactEmployeeNameLastName'))
        _add_path_text(root, ['formData', 'applicant', 'applicantOne', 'contactEmployee', 'contactEmployeeName', 'prefix'], row.get('contactEmployeeNamePrefix'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'crdNumber'], row.get('crdNumber'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'firstName'], row.get('controlAffiliateDetailsFirstName'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isPersonRegistered'], row.get('isPersonRegistered'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isShouldBeRemoved'], row.get('isShouldBeRemoved'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isSubmittedToCRD'], row.get('isSubmittedToCrd'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'lastName'], row.get('controlAffiliateDetailsLastName'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'controlAffiliateDetails', 'personType'], row.get('personType'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'cityOrCounty'], row.get('cityOrCounty'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'courtType'], row.get('courtType'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'descRelationshipWithApplicant'], row.get('descRelationshipWithApplicant'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'docketOrCaseNumber'], row.get('docketOrCaseNumber'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'eventCurrentStatus'], row.get('eventCurrentStatus'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'isEngagedInInvestmentRelatedBusiness'], row.get('isEngagedInInvestmentRelatedBusiness'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'nameOfCourt'], row.get('nameOfCourt'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'organizationName'], row.get('organizationName'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'stateOrCountry'], row.get('criminalDrpDetailsStateOrCountry'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'date'], row.get('dispositionDisclosureDate'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'datePaid'], row.get('datePaid'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'dispositionType'], row.get('dispositionType'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'penaltyFineAmount'], row.get('penaltyFineAmount'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'sentencePenalty'], row.get('sentencePenalty'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'dispositionDisclosure', 'startDatePenalty'], row.get('startDatePenalty'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'crdNumber'], row.get('controlAffiliateDetailsCrdNumber'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'firstName'], row.get('controlAffiliateControlAffiliateDetailsFirstName'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isPersonRegistered'], row.get('controlAffiliateDetailsIsPersonRegistered'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isShouldBeRemoved'], row.get('controlAffiliateDetailsIsShouldBeRemoved'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'isSubmittedToCRD'], row.get('controlAffiliateDetailsIsSubmittedToCrd'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'lastName'], row.get('controlAffiliateControlAffiliateDetailsLastName'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'middleName'], row.get('controlAffiliateDetailsMiddleName'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'nameOfFirm'], row.get('nameOfFirm'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'personType'], row.get('controlAffiliateDetailsPersonType'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'controlAffiliateDetails', 'uicNumber'], row.get('controlAffiliateDetailsUicNumber'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'currentStatus'], row.get('currentStatus'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'descAllegations'], row.get('descAllegations'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'docketOrCaseNumber'], row.get('regulatoryDrpDetailsDocketOrCaseNumber'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'matterResolvedType'], row.get('matterResolvedType'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'monetaryFineAmount'], row.get('monetaryFineAmount'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'otherPrincipalSanction'], row.get('otherPrincipalSanction'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'otherSanctionsOrdered'], row.get('otherSanctionsOrdered'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'principalProductType'], row.get('principalProductType'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'principalProductTypeOtherDesc'], row.get('principalProductTypeOtherDesc'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'principalSanction'], row.get('principalSanction'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'regulatorName'], row.get('regulatorName'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'regulatoryActionInitiatedBy'], row.get('regulatoryActionInitiatedBy'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'sanctionDetail'], row.get('sanctionDetail'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'summaryOfDetails'], row.get('summaryOfDetails'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'descriptionArrangement'], row.get('controlThroughAgreementDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmCikNumber'], row.get('controlThroughAgreementFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmEffectiveDate'], row.get('controlThroughAgreementFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmOrOrganizationName'], row.get('controlThroughAgreementFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmUic'], row.get('controlThroughAgreementFirmUic'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'responseType'], row.get('controlThroughAgreementResponseType'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'descriptionArrangement'], row.get('descriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmCikNumber'], row.get('firmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmCrdNo'], row.get('firmCrdNo'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmEffectiveDate'], row.get('firmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmNfa'], row.get('firmNfa'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmOrOrganizationName'], row.get('firmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmSecFileNumber'], row.get('firmSecFileNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmUic'], row.get('firmUic'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'responseType'], row.get('responseType'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'descriptionArrangement'], row.get('recordsKeptDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmCikNumber'], row.get('recordsKeptFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmEffectiveDate'], row.get('recordsKeptFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmOrOrganizationName'], row.get('recordsKeptFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'responseType'], row.get('recordsKeptResponseType'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'descriptionArrangement'], row.get('whollyOrPartiallyFinanceDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmCikNumber'], row.get('whollyOrPartiallyFinanceFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmCrdNo'], row.get('whollyOrPartiallyFinanceFirmCrdNo'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmEffectiveDate'], row.get('whollyOrPartiallyFinanceFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmOrOrganizationName'], row.get('whollyOrPartiallyFinanceFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmSecFileNumber'], row.get('whollyOrPartiallyFinanceFirmSecFileNumber'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmUic'], row.get('whollyOrPartiallyFinanceFirmUic'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'responseType'], row.get('whollyOrPartiallyFinanceResponseType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionAddress', 'city'], row.get('institutionAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionAddress', 'stateOrCountry'], row.get('institutionAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionAddress', 'street1'], row.get('institutionAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionAddress', 'street2'], row.get('institutionAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDThree', 'sectionSix', 'institutionAddress', 'zipCode'], row.get('institutionAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerAddress', 'city'], row.get('partnerAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerAddress', 'stateOrCountry'], row.get('partnerAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerAddress', 'street1'], row.get('partnerAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerAddress', 'street2'], row.get('partnerAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDTwo', 'sectionFive', 'partnerAddress', 'zipCode'], row.get('partnerAddressZipCode'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'chargeDesc'], row.get('chargeDesc'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'felonyOrMisdemeanor'], row.get('felonyOrMisdemeanor'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'investmentProductType'], row.get('investmentProductType'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'isInvestmentRelated'], row.get('isInvestmentRelated'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'numberOfCounts'], row.get('numberOfCounts'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'criminalCharge', 'plea'], row.get('plea'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'dateFirstCharged', 'date'], row.get('dateFirstChargedDate'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'dateFirstCharged', 'exactOrExplanation'], row.get('dateFirstChargedExactOrExplanation'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'eventStatusDate', 'date'], row.get('eventStatusDateDate'))
        _add_path_text(root, ['formData', 'criminalDrpInfo', 'criminalDrp', 'controlAffiliate', 'criminalDrpDetails', 'eventStatusDate', 'exactOrExplanation'], row.get('exactOrExplanation'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'dateInitiated', 'date'], row.get('dateInitiatedDate'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'dateInitiated', 'exactOrExplanation'], row.get('dateInitiatedExactOrExplanation'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'resolutionDate', 'date'], row.get('resolutionDateDate'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'resolutionDate', 'exactOrExplanation'], row.get('resolutionDateExactOrExplanation'))
        _add_path_text(root, ['formData', 'regulatoryDrpInfo', 'regulatoryDrp', 'controlAffiliate', 'regulatoryDrpDetails', 'sanctionsOrdered', 'sanctionOrdered'], row.get('sanctionOrdered'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'city'], row.get('firmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'stateOrCountry'], row.get('firmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'street1'], row.get('firmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'zipCode'], row.get('firmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'city'], row.get('onBehalfFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'stateOrCountry'], row.get('onBehalfFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'street1'], row.get('onBehalfFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'street2'], row.get('firmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'zipCode'], row.get('onBehalfFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'city'], row.get('recordsKeptFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'stateOrCountry'], row.get('recordsKeptFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'street1'], row.get('recordsKeptFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'street2'], row.get('recordsKeptFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'zipCode'], row.get('recordsKeptFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'city'], row.get('whollyOrPartiallyFinanceFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'stateOrCountry'], row.get('whollyOrPartiallyFinanceFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'street1'], row.get('whollyOrPartiallyFinanceFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'street2'], row.get('whollyOrPartiallyFinanceFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleB', 'sectionTwo', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'zipCode'], row.get('whollyOrPartiallyFinanceFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'descriptionArrangement'], row.get('controlThroughAgreementDetailsControlThroughAgreementDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmCikNumber'], row.get('controlThroughAgreementDetailsControlThroughAgreementFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmEffectiveDate'], row.get('controlThroughAgreementDetailsControlThroughAgreementFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmForeignBusinessNo'], row.get('controlThroughAgreementFirmForeignBusinessNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmNfa'], row.get('controlThroughAgreementFirmNfa'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmOrIndividual'], row.get('controlThroughAgreementFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmOrOrganizationName'], row.get('controlThroughAgreementDetailsControlThroughAgreementFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmUic'], row.get('controlThroughAgreementDetailsControlThroughAgreementFirmUic'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'responseType'], row.get('controlThroughAgreementDetailsControlThroughAgreementResponseType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'descriptionArrangement'], row.get('onBehalfDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmCikNumber'], row.get('onBehalfFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmCrdNo'], row.get('onBehalfFirmCrdNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmEffectiveDate'], row.get('onBehalfFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmForeignBusinessNo'], row.get('firmForeignBusinessNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmNfa'], row.get('onBehalfFirmNfa'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmOrIndividual'], row.get('onBehalfFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmOrOrganizationName'], row.get('onBehalfFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmUic'], row.get('onBehalfFirmUic'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'responseType'], row.get('onBehalfResponseType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'descriptionArrangement'], row.get('recordsKeptDetailsRecordsKeptDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmCikNumber'], row.get('recordsKeptDetailsRecordsKeptFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmEffectiveDate'], row.get('recordsKeptDetailsRecordsKeptFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmOrIndividual'], row.get('recordsKeptFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmOrOrganizationName'], row.get('recordsKeptDetailsRecordsKeptFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmTerminationDate'], row.get('firmTerminationDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmUic'], row.get('recordsKeptFirmUic'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'responseType'], row.get('recordsKeptDetailsRecordsKeptResponseType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'descriptionArrangement'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceDescriptionArrangement'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmCikNumber'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmCikNumber'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmCrdNo'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmCrdNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmEffectiveDate'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmEffectiveDate'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmForeignBusinessNo'], row.get('whollyOrPartiallyFinanceFirmForeignBusinessNo'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmNfa'], row.get('whollyOrPartiallyFinanceFirmNfa'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmOrIndividual'], row.get('whollyOrPartiallyFinanceFirmOrIndividual'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmOrOrganizationName'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmOrOrganizationName'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmUic'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmUic'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'responseType'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceResponseType'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'city'], row.get('controlThroughAgreementFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'stateOrCountry'], row.get('controlThroughAgreementFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'street1'], row.get('controlThroughAgreementFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'street2'], row.get('controlThroughAgreementFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'controlThroughAgreementDetails', 'controlThroughAgreement', 'firmAddress', 'zipCode'], row.get('controlThroughAgreementFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'city'], row.get('onBehalfDetailsOnBehalfFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'stateOrCountry'], row.get('onBehalfDetailsOnBehalfFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'street1'], row.get('onBehalfDetailsOnBehalfFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'street2'], row.get('onBehalfFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'onBehalfDetails', 'onBehalf', 'firmAddress', 'zipCode'], row.get('onBehalfDetailsOnBehalfFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'city'], row.get('recordsKeptDetailsRecordsKeptFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'stateOrCountry'], row.get('recordsKeptDetailsRecordsKeptFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'street1'], row.get('recordsKeptDetailsRecordsKeptFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'street2'], row.get('recordsKeptDetailsRecordsKeptFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'recordsKeptDetails', 'recordsKept', 'firmAddress', 'zipCode'], row.get('recordsKeptDetailsRecordsKeptFirmAddressZipCode'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'city'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmAddressCity'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'stateOrCountry'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'street1'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmAddressStreet1'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'street2'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmAddressStreet2'))
        _add_path_text(root, ['formData', 'scheduleD', 'scheduleDOne', 'sectionFour', 'whollyOrPartiallyFinanceDetails', 'whollyOrPartiallyFinance', 'firmAddress', 'zipCode'], row.get('whollyOrPartiallyFinanceDetailsWhollyOrPartiallyFinanceFirmAddressZipCode'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')





