import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_ta1(rows: list) -> bytes:
    normalized_rows = []
    if rows:
        for row in rows:
            if isinstance(row, dict) or hasattr(row, "get"):
                normalized_rows.append(row)
            else:
                normalized_rows.append(dict(row))
    else:
        normalized_rows = [{}]

    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/ta/taonefiler')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    for row in normalized_rows:
        _add_path_text(root, ['formVersion'], row.get('formVersion'))
        _add_path_text(root, ['regulatoryAgency'], row.get('regulatoryAgency'))
        _add_path_text(root, ['schemaVersion'], row.get('schemaVersion'))
        _add_path_text(root, ['submissionType'], row.get('submissionType'))
        _add_path_text(root, ['testOrLive'], row.get('testOrLive'))
        _add_path_text(root, ['authorizationDeniedOrSuspended', 'involved'], row.get('involved'))
        _add_path_text(root, ['enjoinedInvestmentRelatedActivity', 'involved'], row.get('enjoinedInvestmentRelatedActivityInvolved'))
        _add_path_text(root, ['falseStatementOrOmission', 'involved'], row.get('falseStatementOrOmissionInvolved'))
        _add_path_text(root, ['felonyOrMisdemeanor', 'involved'], row.get('felonyOrMisdemeanorInvolved'))
        _add_path_text(root, ['filer', 'cik'], row.get('cik'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], row.get('finsNumber'))
        _add_path_text(root, ['foreignAgency', 'involved'], row.get('foreignAgencyInvolved'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('headerDataSubmissionType'))
        _add_path_text(root, ['otherControlFinance', 'otherEntity'], row.get('otherEntity'))
        _add_path_text(root, ['otherControlManagement', 'otherEntity'], row.get('otherControlManagementOtherEntity'))
        _add_path_text(root, ['otherFelony', 'involved'], row.get('otherFelonyInvolved'))
        _add_path_text(root, ['registrant', 'conductBusinessInOtherLocations'], row.get('conductBusinessInOtherLocations'))
        _add_path_text(root, ['registrant', 'differentMailingAddress'], row.get('differentMailingAddress'))
        _add_path_text(root, ['registrant', 'engagedAsServiceCompany'], row.get('engagedAsServiceCompany'))
        _add_path_text(root, ['registrant', 'engagedServiceCompany'], row.get('engagedServiceCompany'))
        _add_path_text(root, ['registrant', 'entityName'], row.get('entityName'))
        _add_path_text(root, ['registrant', 'registrantType'], row.get('registrantType'))
        _add_path_text(root, ['registrant', 'selfTransferAgent'], row.get('selfTransferAgent'))
        _add_path_text(root, ['registrant', 'telephoneNumber'], row.get('telephoneNumber'))
        _add_path_text(root, ['registrationDeniedOrSuspended', 'involved'], row.get('registrationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['revokedBond', 'involved'], row.get('revokedBondInvolved'))
        _add_path_text(root, ['signatureData', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['signatureData', 'signatureName'], row.get('signatureName'))
        _add_path_text(root, ['signatureData', 'signaturePhoneNumber'], row.get('signaturePhoneNumber'))
        _add_path_text(root, ['signatureData', 'signatureTitle'], row.get('signatureTitle'))
        _add_path_text(root, ['subjectOfProceedings', 'involved'], row.get('subjectOfProceedingsInvolved'))
        _add_path_text(root, ['unsatisfiedJudgementsOrLiens', 'involved'], row.get('unsatisfiedJudgementsOrLiensInvolved'))
        _add_path_text(root, ['violationOfInvestmentRelatedRegulation', 'involved'], row.get('violationOfInvestmentRelatedRegulationInvolved'))
        _add_path_text(root, ['violationOfRegulations', 'involved'], row.get('violationOfRegulationsInvolved'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'corporationPartnershipData', 'relationshipStartDate'], row.get('corporationPartnershipDataRelationshipStartDate'))
        _add_path_text(root, ['violationOfRegulations', 'violationOfRegulationsDetails', 'actionDescription'], row.get('authorityDescription'))
        _add_path_text(root, ['otherControlManagement', 'otherControlManagementDetails', 'agreementDescription'], row.get('registrantTypeDescription'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'corporationPartnershipData', 'entityName'], row.get('independentRegistrantCorporationPartnershipDataEntityName'))
        _add_path_text(root, ['registrant', 'corporationPartnershipData', 'relationshipStartDate'], row.get('relationshipStartDate'))
        _add_path_text(root, ['formData', 'registrant', 'conductBusinessInOtherLocations'], row.get('registrantConductBusinessInOtherLocations'))
        _add_path_text(root, ['registrant', 'corporationPartnershipData', 'entityName'], row.get('corporationPartnershipDataEntityName'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrAuthorizationDeniedOrSuspended', 'involved'], row.get('fsrAuthorizationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrFalseStatementOrOmission', 'involved'], row.get('fsrFalseStatementOrOmissionInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrFoundOrderAgainstApplicant', 'involved'], row.get('fsrFoundOrderAgainstApplicantInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrRegistrationDeniedOrSuspended', 'involved'], row.get('fsrRegistrationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrRevokedSuspendedLicense', 'involved'], row.get('fsrRevokedSuspendedLicenseInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrViolationOfInvestmentRelatedRegulation', 'involved'], row.get('fsrViolationOfInvestmentRelatedRegulationInvolved'))
        _add_path_text(root, ['formData', 'registrant', 'entityName'], row.get('registrantEntityName'))
        _add_path_text(root, ['formData', 'signature', 'signatureTitle'], row.get('signatureSignatureTitle'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'registrantType'], row.get('independentRegistrantRegistrantType'))
        _add_path_text(root, ['formData', 'registrant', 'differentMailingAddress'], row.get('registrantDifferentMailingAddress'))
        _add_path_text(root, ['formData', 'registrant', 'engagedAsServiceCompany'], row.get('registrantEngagedAsServiceCompany'))
        _add_path_text(root, ['formData', 'registrant', 'engagedServiceCompany'], row.get('registrantEngagedServiceCompany'))
        _add_path_text(root, ['formData', 'registrant', 'finsNumber'], row.get('registrantFinsNumber'))
        _add_path_text(root, ['formData', 'registrant', 'regulatoryAgency'], row.get('registrantRegulatoryAgency'))
        _add_path_text(root, ['formData', 'registrant', 'selfTransferAgent'], row.get('registrantSelfTransferAgent'))
        _add_path_text(root, ['formData', 'registrant', 'telephoneNumber'], row.get('registrantTelephoneNumber'))
        _add_path_text(root, ['formData', 'signature', 'signatureDate'], row.get('signatureSignatureDate'))
        _add_path_text(root, ['formData', 'signature', 'signatureName'], row.get('signatureSignatureName'))
        _add_path_text(root, ['formData', 'signature', 'signaturePhoneNumber'], row.get('signatureSignaturePhoneNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], row.get('liveTestFlag'))
        _add_path_text(root, ['registrant', 'corporationPartnershipData', 'controlPerson'], row.get('controlPerson'))
        _add_path_text(root, ['registrant', 'corporationPartnershipData', 'ownershipCode'], row.get('ownershipCode'))
        _add_path_text(root, ['registrant', 'corporationPartnershipData', 'titleOrStatus'], row.get('titleOrStatus'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'city'], row.get('city'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'stateOrCountry'], row.get('stateOrCountry'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'stateOrCountryCode'], row.get('stateOrCountryCode'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'street1'], row.get('street1'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'street2'], row.get('street2'))
        _add_path_text(root, ['registrant', 'principalOfficeAddress', 'zipCode'], row.get('zipCode'))
        _add_path_text(root, ['selfRegulatoryAgency', 'sraAuthorizationDeniedOrSuspended', 'involved'], row.get('sraAuthorizationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['selfRegulatoryAgency', 'sraFalseStatementOrOmission', 'involved'], row.get('sraFalseStatementOrOmissionInvolved'))
        _add_path_text(root, ['selfRegulatoryAgency', 'sraRevokedSuspendedLicense', 'involved'], row.get('sraRevokedSuspendedLicenseInvolved'))
        _add_path_text(root, ['selfRegulatoryAgency', 'sraViolationOfRules', 'involved'], row.get('sraViolationOfRulesInvolved'))
        _add_path_text(root, ['federalOrStateRegulatoryAgency', 'fsrFoundOrderAgainstApplicant', 'fsrFoundOrderAgainstApplicantDetails', 'entityName'], row.get('soleProprietorshipOtherDataEntityName'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'authorizationDeniedOrSuspended', 'involved'], row.get('authorizationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'enjoinedInvestmentRelatedActivity', 'involved'], row.get('disciplinaryHistoryEnjoinedInvestmentRelatedActivityInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'falseStatementOrOmission', 'involved'], row.get('disciplinaryHistoryFalseStatementOrOmissionInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'felonyOrMisdemeanor', 'involved'], row.get('disciplinaryHistoryFelonyOrMisdemeanorInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'foreignAgency', 'involved'], row.get('disciplinaryHistoryForeignAgencyInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'otherFelony', 'involved'], row.get('disciplinaryHistoryOtherFelonyInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'registrationDeniedOrSuspended', 'involved'], row.get('disciplinaryHistoryRegistrationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'revokedBond', 'involved'], row.get('disciplinaryHistoryRevokedBondInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'subjectOfProceedings', 'involved'], row.get('disciplinaryHistorySubjectOfProceedingsInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'unsatisfiedJudgementsOrLiens', 'involved'], row.get('disciplinaryHistoryUnsatisfiedJudgementsOrLiensInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'violationOfInvestmentRelatedRegulation', 'involved'], row.get('disciplinaryHistoryViolationOfInvestmentRelatedRegulationInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'violationOfRegulations', 'involved'], row.get('disciplinaryHistoryViolationOfRegulationsInvolved'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'corporationPartnershipData', 'controlPerson'], row.get('corporationPartnershipDataControlPerson'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'corporationPartnershipData', 'ownershipCode'], row.get('corporationPartnershipDataOwnershipCode'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'corporationPartnershipData', 'titleOrStatus'], row.get('corporationPartnershipDataTitleOrStatus'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'otherControlFinance', 'otherEntity'], row.get('otherControlFinanceOtherEntity'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'otherControlManagement', 'otherEntity'], row.get('independentRegistrantOtherControlManagementOtherEntity'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'soleProprietorshipOtherData', 'relationshipStartDate'], row.get('soleProprietorshipOtherDataRelationshipStartDate'))
        _add_path_text(root, ['formData', 'independentRegistrant', 'soleProprietorshipOtherData', 'titleOrStatus'], row.get('soleProprietorshipOtherDataTitleOrStatus'))
        _add_path_text(root, ['formData', 'registrant', 'principalOfficeAddress', 'city'], row.get('principalOfficeAddressCity'))
        _add_path_text(root, ['formData', 'registrant', 'principalOfficeAddress', 'stateOrCountry'], row.get('principalOfficeAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'registrant', 'principalOfficeAddress', 'street1'], row.get('principalOfficeAddressStreet1'))
        _add_path_text(root, ['formData', 'registrant', 'principalOfficeAddress', 'street2'], row.get('principalOfficeAddressStreet2'))
        _add_path_text(root, ['formData', 'registrant', 'principalOfficeAddress', 'zipCode'], row.get('principalOfficeAddressZipCode'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], row.get('returnCopyFlag'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrAuthorizationDeniedOrSuspended', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrAuthorizationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrFalseStatementOrOmission', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrFalseStatementOrOmissionInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrFoundOrderAgainstApplicant', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrFoundOrderAgainstApplicantInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrRegistrationDeniedOrSuspended', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrRegistrationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrRevokedSuspendedLicense', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrRevokedSuspendedLicenseInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'federalOrStateRegulatoryAgency', 'fsrViolationOfInvestmentRelatedRegulation', 'involved'], row.get('federalOrStateRegulatoryAgencyFsrViolationOfInvestmentRelatedRegulationInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'selfRegulatoryAgency', 'sraAuthorizationDeniedOrSuspended', 'involved'], row.get('selfRegulatoryAgencySraAuthorizationDeniedOrSuspendedInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'selfRegulatoryAgency', 'sraFalseStatementOrOmission', 'involved'], row.get('selfRegulatoryAgencySraFalseStatementOrOmissionInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'selfRegulatoryAgency', 'sraRevokedSuspendedLicense', 'involved'], row.get('selfRegulatoryAgencySraRevokedSuspendedLicenseInvolved'))
        _add_path_text(root, ['formData', 'disciplinaryHistory', 'selfRegulatoryAgency', 'sraViolationOfRules', 'involved'], row.get('selfRegulatoryAgencySraViolationOfRulesInvolved'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('filerCredentialsCik'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




