import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_ta2(rows: list) -> bytes:
    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/ta/tatwofiler')
    for row in rows:
        _add_path_text(root, ['formVersion'], row.get('formVersion'))
        _add_path_text(root, ['periodOfReport'], row.get('periodOfReport'))
        _add_path_text(root, ['regulatoryAgency'], row.get('regulatoryAgency'))
        _add_path_text(root, ['schemaVersion'], row.get('schemaVersion'))
        _add_path_text(root, ['submissionType'], row.get('submissionType'))
        _add_path_text(root, ['testOrLive'], row.get('testOrLive'))
        _add_path_text(root, ['engagedAsServiceCompany', 'function'], row.get('function'))
        _add_path_text(root, ['engagedServiceCompany', 'function'], row.get('engagedServiceCompanyFunction'))
        _add_path_text(root, ['filer', 'cik'], row.get('cik'))
        _add_path_text(root, ['filer', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('headerDataSubmissionType'))
        _add_path_text(root, ['inaccurateIncompleteMisleading', 'additionalInformation'], row.get('additionalInformation'))
        _add_path_text(root, ['inaccurateIncompleteMisleading', 'amendmentFiled'], row.get('amendmentFiled'))
        _add_path_text(root, ['registrant', 'entityName'], row.get('entityName'))
        _add_path_text(root, ['serviceCompanyData', 'numberDirectRegistSystemAccounts'], row.get('numberDirectRegistSystemAccounts'))
        _add_path_text(root, ['serviceCompanyData', 'numberDivReinvDirPurPlanAccounts'], row.get('numberDivReinvDirPurPlanAccounts'))
        _add_path_text(root, ['serviceCompanyData', 'numberIndividualAccounts'], row.get('numberIndividualAccounts'))
        _add_path_text(root, ['serviceCompanyData', 'numberItemsReceivedForTransfer'], row.get('numberItemsReceivedForTransfer'))
        _add_path_text(root, ['serviceCompanyData', 'numberLostAccountsRemittedToStates'], row.get('numberLostAccountsRemittedToStates'))
        _add_path_text(root, ['serviceCompanyData', 'numberMasterSecurityHolderFilings'], row.get('numberMasterSecurityHolderFilings'))
        _add_path_text(root, ['signatureData', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['signatureData', 'signatureName'], row.get('signatureName'))
        _add_path_text(root, ['signatureData', 'signaturePhoneNumber'], row.get('signaturePhoneNumber'))
        _add_path_text(root, ['signatureData', 'signatureTitle'], row.get('signatureTitle'))
        _add_path_text(root, ['engagedAsServiceCompany', 'asServiceCompanyTransferAgent', 'entityName'], row.get('asServiceCompanyTransferAgentEntityName'))
        _add_path_text(root, ['engagedAsServiceCompany', 'asServiceCompanyTransferAgent', 'fileNumber'], row.get('asServiceCompanyTransferAgentFileNumber'))
        _add_path_text(root, ['engagedServiceCompany', 'serviceCompanyTransferAgent', 'entityName'], row.get('serviceCompanyTransferAgentEntityName'))
        _add_path_text(root, ['engagedServiceCompany', 'serviceCompanyTransferAgent', 'fileNumber'], row.get('serviceCompanyTransferAgentFileNumber'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'registrantEngagedService'], row.get('registrantEngagedService'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'serviceCompany'], row.get('serviceCompany'))
        _add_path_text(root, ['formData', 'registrantRegulatoryAgency', 'additionalInformation'], row.get('registrantRegulatoryAgencyAdditionalInformation'))
        _add_path_text(root, ['formData', 'registrantRegulatoryAgency', 'amendmentFiled'], row.get('registrantRegulatoryAgencyAmendmentFiled'))
        _add_path_text(root, ['formData', 'registrantRegulatoryAgency', 'regulatoryAgency'], row.get('registrantRegulatoryAgencyRegulatoryAgency'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberDirectRegistSystemAccounts'], row.get('serviceCompanyDataNumberDirectRegistSystemAccounts'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberDivReinvDirPurPlanAccounts'], row.get('serviceCompanyDataNumberDivReinvDirPurPlanAccounts'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberIndividualAccounts'], row.get('serviceCompanyDataNumberIndividualAccounts'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberItemsReceivedForTransfer'], row.get('serviceCompanyDataNumberItemsReceivedForTransfer'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberLostAccountsRemittedToStates'], row.get('serviceCompanyDataNumberLostAccountsRemittedToStates'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'numberMasterSecurityHolderFilings'], row.get('serviceCompanyDataNumberMasterSecurityHolderFilings'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureDate'], row.get('signatureDataSignatureDate'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureName'], row.get('signatureDataSignatureName'))
        _add_path_text(root, ['formData', 'signatureData', 'signaturePhoneNumber'], row.get('signatureDataSignaturePhoneNumber'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureTitle'], row.get('signatureDataSignatureTitle'))
        _add_path_text(root, ['headerData', 'filerInfo', 'entityName'], row.get('filerInfoEntityName'))
        _add_path_text(root, ['headerData', 'filerInfo', 'periodOfReport'], row.get('filerInfoPeriodOfReport'))
        _add_path_text(root, ['headerData', 'filerInfo', 'testOrLive'], row.get('filerInfoTestOrLive'))
        _add_path_text(root, ['serviceCompanyData', 'databaseSearch', 'databaseSearchDate'], row.get('databaseSearchDate'))
        _add_path_text(root, ['serviceCompanyData', 'databaseSearch', 'numberAddressesFromSearch'], row.get('numberAddressesFromSearch'))
        _add_path_text(root, ['serviceCompanyData', 'databaseSearch', 'numberLostAccountsSearched'], row.get('numberLostAccountsSearched'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'debtSecurity'], row.get('debtSecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'equitySecurity'], row.get('equitySecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'limitedPartnership'], row.get('limitedPartnership'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'municipalDebt'], row.get('municipalDebt'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'openEndInvestmentCompany'], row.get('openEndInvestmentCompany'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderAccounts', 'other'], row.get('other'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'asServiceCompanyTransferAgent', 'entityName'], row.get('engagedServiceCompanyAsServiceCompanyTransferAgentEntityName'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'asServiceCompanyTransferAgent', 'fileNumber'], row.get('engagedServiceCompanyAsServiceCompanyTransferAgentFileNumber'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'serviceCompanyTransferAgent', 'entityName'], row.get('engagedServiceCompanyServiceCompanyTransferAgentEntityName'))
        _add_path_text(root, ['formData', 'engagedServiceCompany', 'serviceCompanyTransferAgent', 'fileNumber'], row.get('engagedServiceCompanyServiceCompanyTransferAgentFileNumber'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'databaseSearches', 'databaseSearchDate'], row.get('databaseSearchesDatabaseSearchDate'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'databaseSearches', 'numberAddressesFromSearch'], row.get('databaseSearchesNumberAddressesFromSearch'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'databaseSearches', 'numberLostAccountsSearched'], row.get('databaseSearchesNumberLostAccountsSearched'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'debtSecurity'], row.get('securityHolderAccountsDebtSecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'equitySecurity'], row.get('securityHolderAccountsEquitySecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'limitedPartnership'], row.get('securityHolderAccountsLimitedPartnership'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'municipalDebt'], row.get('securityHolderAccountsMunicipalDebt'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'openEndInvestmentCompany'], row.get('securityHolderAccountsOpenEndInvestmentCompany'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderAccounts', 'other'], row.get('securityHolderAccountsOther'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'alwaysCompliant'], row.get('alwaysCompliant'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'directRegistrationSystem'], row.get('directRegistrationSystem'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'dividendReinvDirectPurchasePlan'], row.get('dividendReinvDirectPurchasePlan'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'numberFiled'], row.get('numberFiled'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'total'], row.get('total'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'totalOtherThanReceiptOrderDate'], row.get('totalOtherThanReceiptOrderDate'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'fileNumber'], row.get('filerFileNumber'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'isFilingAmendment'], row.get('isFilingAmendment'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopy'], row.get('returnCopy'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'currentAgent', 'amountIssues'], row.get('amountIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'currentAgent', 'numberIssues'], row.get('numberIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'directRegistrationSystem', 'numberIssues'], row.get('directRegistrationSystemNumberIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'dividendAndInterest', 'amountIssues'], row.get('dividendAndInterestAmountIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'dividendAndInterest', 'numberIssues'], row.get('dividendAndInterestNumberIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'dividendReinvDirectPurchasePlan', 'numberIssues'], row.get('dividendReinvDirectPurchasePlanNumberIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'debtSecurity'], row.get('notTransMaintMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'equitySecurity'], row.get('notTransMaintMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'limitedPartnership'], row.get('notTransMaintMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'municipalDebt'], row.get('notTransMaintMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'openEndInvestmentCompany'], row.get('notTransMaintMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'other'], row.get('notTransMaintMasterSecHolderOther'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'priorAgent', 'amountIssues'], row.get('priorAgentAmountIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'priorAgent', 'numberIssues'], row.get('priorAgentNumberIssues'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'purchaseRedemptionPricingShares', 'total'], row.get('purchaseRedemptionPricingSharesTotal'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'purchaseRedemptionPricingShares', 'totalOtherThanReceiptOrderDate'], row.get('purchaseRedemptionPricingSharesTotalOtherThanReceiptOrderDate'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'quarterlyReportsRegardingBuyIns', 'numberFiled'], row.get('quarterlyReportsRegardingBuyInsNumberFiled'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'debtSecurity'], row.get('transMaintainMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'equitySecurity'], row.get('transMaintainMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'limitedPartnership'], row.get('transMaintainMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'municipalDebt'], row.get('transMaintainMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'openEndInvestmentCompany'], row.get('transMaintainMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'other'], row.get('transMaintainMasterSecHolderOther'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'debtSecurity'], row.get('transNotMaintMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'equitySecurity'], row.get('transNotMaintMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'limitedPartnership'], row.get('transNotMaintMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'municipalDebt'], row.get('transNotMaintMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'openEndInvestmentCompany'], row.get('transNotMaintMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'other'], row.get('transNotMaintMasterSecHolderOther'))
        _add_path_text(root, ['serviceCompanyData', 'securityHolderData', 'turnaroundCompliant', 'alwaysCompliant'], row.get('turnaroundCompliantAlwaysCompliant'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'currentAgent', 'amountIssues'], row.get('currentAgentAmountIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'currentAgent', 'numberIssues'], row.get('currentAgentNumberIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'dividendAndInterest', 'amountIssues'], row.get('securityHolderDataDividendAndInterestAmountIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'dividendAndInterest', 'numberIssues'], row.get('securityHolderDataDividendAndInterestNumberIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'debtSecurity'], row.get('securityHolderDataNotTransMaintMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'equitySecurity'], row.get('securityHolderDataNotTransMaintMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'limitedPartnership'], row.get('securityHolderDataNotTransMaintMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'municipalDebt'], row.get('securityHolderDataNotTransMaintMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'openEndInvestmentCompany'], row.get('securityHolderDataNotTransMaintMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'notTransMaintMasterSecHolder', 'other'], row.get('securityHolderDataNotTransMaintMasterSecHolderOther'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'priorAgent', 'amountIssues'], row.get('securityHolderDataPriorAgentAmountIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'priorAgent', 'numberIssues'], row.get('securityHolderDataPriorAgentNumberIssues'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'debtSecurity'], row.get('securityHolderDataTransMaintainMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'equitySecurity'], row.get('securityHolderDataTransMaintainMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'limitedPartnership'], row.get('securityHolderDataTransMaintainMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'municipalDebt'], row.get('securityHolderDataTransMaintainMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'openEndInvestmentCompany'], row.get('securityHolderDataTransMaintainMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transMaintainMasterSecHolder', 'other'], row.get('securityHolderDataTransMaintainMasterSecHolderOther'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'debtSecurity'], row.get('securityHolderDataTransNotMaintMasterSecHolderDebtSecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'equitySecurity'], row.get('securityHolderDataTransNotMaintMasterSecHolderEquitySecurity'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'limitedPartnership'], row.get('securityHolderDataTransNotMaintMasterSecHolderLimitedPartnership'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'municipalDebt'], row.get('securityHolderDataTransNotMaintMasterSecHolderMunicipalDebt'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'openEndInvestmentCompany'], row.get('securityHolderDataTransNotMaintMasterSecHolderOpenEndInvestmentCompany'))
        _add_path_text(root, ['formData', 'serviceCompanyData', 'securityHolderData', 'transNotMaintMasterSecHolder', 'other'], row.get('securityHolderDataTransNotMaintMasterSecHolderOther'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('filerCredentialsCik'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




