import io
import xml.etree.ElementTree as ET

from ..utils import _add_created_with_comment, _add_path_text


def construct_taw(rows: list) -> bytes:
    root = ET.Element('edgarSubmission')
    root.set('xmlns', 'http://www.sec.gov/edgar/ta/tawfiler')
    root.set('xmlns:com', 'http://www.sec.gov/edgar/common')
    for row in rows:
        _add_path_text(root, ['formVersion'], row.get('formVersion'))
        _add_path_text(root, ['schemaVersion'], row.get('schemaVersion'))
        _add_path_text(root, ['submissionType'], row.get('submissionType'))
        _add_path_text(root, ['testOrLive'], row.get('testOrLive'))
        _add_path_text(root, ['filer', 'cik'], row.get('cik'))
        _add_path_text(root, ['filer', 'fileNumber'], row.get('fileNumber'))
        _add_path_text(root, ['headerData', 'submissionType'], row.get('headerDataSubmissionType'))
        _add_path_text(root, ['registrant', 'entityName'], row.get('entityName'))
        _add_path_text(root, ['registrant', 'futureTransferAgentFunctions'], row.get('futureTransferAgentFunctions'))
        _add_path_text(root, ['registrant', 'lastActionDate'], row.get('lastActionDate'))
        _add_path_text(root, ['registrant', 'withdrawalDescription'], row.get('withdrawalDescription'))
        _add_path_text(root, ['signatureData', 'signatureDate'], row.get('signatureDate'))
        _add_path_text(root, ['signatureData', 'signatureName'], row.get('signatureName'))
        _add_path_text(root, ['signatureData', 'signaturePhoneNumber'], row.get('signaturePhoneNumber'))
        _add_path_text(root, ['signatureData', 'signatureTitle'], row.get('signatureTitle'))
        _add_path_text(root, ['formData', 'documentRetention', 'successorTransferAgents'], row.get('successorTransferAgents'))
        _add_path_text(root, ['formData', 'legalAction', 'involved'], row.get('involved'))
        _add_path_text(root, ['formData', 'legalAction', 'unsatisfiedJudgmentsInvolved'], row.get('unsatisfiedJudgmentsInvolved'))
        _add_path_text(root, ['formData', 'registrant', 'entityName'], row.get('registrantEntityName'))
        _add_path_text(root, ['formData', 'registrant', 'fileNumber'], row.get('registrantFileNumber'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureDate'], row.get('signatureDataSignatureDate'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureName'], row.get('signatureDataSignatureName'))
        _add_path_text(root, ['formData', 'signatureData', 'signaturePhoneNumber'], row.get('signatureDataSignaturePhoneNumber'))
        _add_path_text(root, ['formData', 'signatureData', 'signatureTitle'], row.get('signatureDataSignatureTitle'))
        _add_path_text(root, ['formData', 'withdrawal', 'futureTransferAgentFunctions'], row.get('withdrawalFutureTransferAgentFunctions'))
        _add_path_text(root, ['formData', 'withdrawal', 'lastActionDate'], row.get('withdrawalLastActionDate'))
        _add_path_text(root, ['formData', 'withdrawal', 'withdrawalDescription'], row.get('withdrawalWithdrawalDescription'))
        _add_path_text(root, ['headerData', 'filerInfo', 'liveTestFlag'], row.get('liveTestFlag'))
        _add_path_text(root, ['registrant', 'businessAddress', 'city'], row.get('city'))
        _add_path_text(root, ['registrant', 'businessAddress', 'stateOrCountry'], row.get('stateOrCountry'))
        _add_path_text(root, ['registrant', 'businessAddress', 'stateOrCountryCode'], row.get('stateOrCountryCode'))
        _add_path_text(root, ['registrant', 'businessAddress', 'street1'], row.get('street1'))
        _add_path_text(root, ['registrant', 'businessAddress', 'street2'], row.get('street2'))
        _add_path_text(root, ['registrant', 'businessAddress', 'zipCode'], row.get('zipCode'))
        _add_path_text(root, ['registrant', 'subjectOfProceedings', 'involved'], row.get('subjectOfProceedingsInvolved'))
        _add_path_text(root, ['registrant', 'unsatisfiedJudgementsOrLiens', 'involved'], row.get('unsatisfiedJudgementsOrLiensInvolved'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'entityName'], row.get('tawCustodiansEntityName'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'successorTransferAgents'], row.get('tawSuccessorsSuccessorTransferAgents'))
        _add_path_text(root, ['formData', 'documentRetention', 'tawCustodians', 'entityName'], row.get('documentRetentionTawCustodiansEntityName'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'successorRegistered'], row.get('successorRegistered'))
        _add_path_text(root, ['formData', 'registrant', 'businessAddress', 'city'], row.get('businessAddressCity'))
        _add_path_text(root, ['formData', 'registrant', 'businessAddress', 'stateOrCountry'], row.get('businessAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'registrant', 'businessAddress', 'street1'], row.get('businessAddressStreet1'))
        _add_path_text(root, ['formData', 'registrant', 'businessAddress', 'street2'], row.get('businessAddressStreet2'))
        _add_path_text(root, ['formData', 'registrant', 'businessAddress', 'zipCode'], row.get('businessAddressZipCode'))
        _add_path_text(root, ['headerData', 'filerInfo', 'flags', 'returnCopyFlag'], row.get('returnCopyFlag'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'entityName'], row.get('tawSuccessorDetailsEntityName'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'city'], row.get('tawCustodianAddressCity'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'stateOrCountry'], row.get('tawCustodianAddressStateOrCountry'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'stateOrCountryCode'], row.get('tawCustodianAddressStateOrCountryCode'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'street1'], row.get('tawCustodianAddressStreet1'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'street2'], row.get('tawCustodianAddressStreet2'))
        _add_path_text(root, ['tawDetails', 'tawCustodians', 'tawCustodianAddress', 'zipCode'], row.get('tawCustodianAddressZipCode'))
        _add_path_text(root, ['formData', 'documentRetention', 'tawCustodians', 'tawCustodianAddress', 'city'], row.get('tawCustodiansTawCustodianAddressCity'))
        _add_path_text(root, ['formData', 'documentRetention', 'tawCustodians', 'tawCustodianAddress', 'stateOrCountry'], row.get('tawCustodiansTawCustodianAddressStateOrCountry'))
        _add_path_text(root, ['formData', 'documentRetention', 'tawCustodians', 'tawCustodianAddress', 'street1'], row.get('tawCustodiansTawCustodianAddressStreet1'))
        _add_path_text(root, ['formData', 'documentRetention', 'tawCustodians', 'tawCustodianAddress', 'zipCode'], row.get('tawCustodiansTawCustodianAddressZipCode'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'tawSuccessorAddress', 'city'], row.get('tawSuccessorAddressCity'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'tawSuccessorAddress', 'stateOrCountry'], row.get('tawSuccessorAddressStateOrCountry'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'tawSuccessorAddress', 'street1'], row.get('tawSuccessorAddressStreet1'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'tawSuccessorAddress', 'zipCode'], row.get('tawSuccessorAddressZipCode'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'ccc'], row.get('ccc'))
        _add_path_text(root, ['headerData', 'filerInfo', 'filer', 'filerCredentials', 'cik'], row.get('filerCredentialsCik'))
        _add_path_text(root, ['tawDetails', 'tawSuccessors', 'tawSuccessorDetails', 'tawSuccessorAddress', 'stateOrCountryCode'], row.get('tawSuccessorAddressStateOrCountryCode'))
    _add_created_with_comment(root)

    tree = ET.ElementTree(root)
    ET.indent(tree, space='\t')

    output = io.StringIO()
    output.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    tree.write(output, encoding='unicode', xml_declaration=False)
    return output.getvalue().encode('utf-8')




